/* Komut Ansiklopedisi — genişletme (ek paket) */
(function () {
    const extra = [
        // —— Daha fazla dosya / metin ——
        { cmd: 'install', cat: 'Dosya', en: 'Install', tr: 'Kopyala + izin ayarla', origin: 'Kurulum script’lerinden: dosyayı hedefe koyup mode/owner set eder.', example: 'install -m 755 bin/app /usr/local/bin/', tip: 'cp + chmod birleşimi', aliases: ['kurulum kopyala'] },
        { cmd: 'install -d', cat: 'Dosya', en: 'Install Directory', tr: 'Dizin oluştur (install)', origin: 'install -d ≈ mkdir -p', example: 'install -d /opt/app/bin', tip: 'Paket Makefile’larında sık', aliases: ['dizin kur'] },
        { cmd: 'shred', cat: 'Dosya', en: 'Shred', tr: 'Güvenli sil (üzerine yaz)', origin: 'shred = parçala. Veriyi üzerine yazarak silmeye çalışır.', example: 'shred -u gizli.txt', tip: 'SSD’de garantili değil', aliases: ['güvenli sil', 'iz bırakmadan sil'] },
        { cmd: 'wipe', cat: 'Dosya', en: 'Wipe', tr: 'Sil / temizle', origin: 'wipe = silip süpürmek.', example: 'wipe -r klasor', tip: 'Paket ayrı kurulabilir', aliases: ['süpür'] },
        { cmd: 'sync', cat: 'Dosya', en: 'Synchronize', tr: 'Disk önbelleğini yaz', origin: 'bellekteki dirty page’leri diske zorla yazar.', example: 'sync', tip: 'USB çıkarmadan önce', aliases: ['diske yaz', 'flush'] },
        { cmd: 'truncate', cat: 'Dosya', en: 'Truncate', tr: 'Boyutu kırp / sıfırla', origin: 'truncate = kesmek. Dosyayı verilen boyuta getirir.', example: 'truncate -s 0 log.txt', tip: 'Log’u silmeden boşaltır', aliases: ['dosyayı boşalt', 'boyut kırp'] },
        { cmd: 'split', cat: 'Dosya', en: 'Split', tr: 'Böl', origin: 'split = bölmek. Büyük dosyayı parçalara ayırır.', example: 'split -b 100M big.iso parca.', tip: 'cat parca.* > big.iso', aliases: ['parçala', 'dosya böl'] },
        { cmd: 'csplit', cat: 'Dosya', en: 'Context Split', tr: 'Desene göre böl', origin: 'context split — satır desenine göre parçalar.', example: 'csplit file.txt /Pattern/', tip: 'Nadiren gerekir' },
        { cmd: 'paste', cat: 'Metin', en: 'Paste', tr: 'Yan yana birleştir', origin: 'paste = yapıştırmak. Satırları sütun gibi birleştirir.', example: 'paste a.txt b.txt', tip: 'cut’ın tersi gibi', aliases: ['sütun birleştir'] },
        { cmd: 'join', cat: 'Metin', en: 'Join', tr: 'Ortak alana göre birleştir', origin: 'join = birleşim (SQL join benzeri).', example: 'join -t: file1 file2', tip: 'Önce sort şart', aliases: ['dosya join'] },
        { cmd: 'comm', cat: 'Metin', en: 'Common', tr: 'Ortak / fark satırlar', origin: 'common lines — iki sıralı dosyayı karşılaştırır.', example: 'comm -12 a.txt b.txt', tip: 'sort edilmiş olmalı' },
        { cmd: 'tr', cat: 'Metin', en: 'Translate', tr: 'Karakter dönüştür', origin: 'translate/delete characters.', example: "tr 'a-z' 'A-Z' < f", tip: 'CRLF→LF: tr -d "\\r"', aliases: ['harf değiştir', 'büyük harf'] },
        { cmd: 'rev', cat: 'Metin', en: 'Reverse', tr: 'Satırı ters çevir', origin: 'reverse = tersine çevir.', example: 'echo abc | rev', tip: 'tac satır sırası; rev karakter' },
        { cmd: 'nl', cat: 'Metin', en: 'Number Lines', tr: 'Satır numarala', origin: 'number lines.', example: 'nl dosya.txt', tip: 'cat -n benzeri' },
        { cmd: 'fold', cat: 'Metin', en: 'Fold', tr: 'Satır kır', origin: 'fold = katlamak. Uzun satırları genişliğe böler.', example: 'fold -w 80 dosya', tip: 'Terminal genişliği için' },
        { cmd: 'fmt', cat: 'Metin', en: 'Format', tr: 'Paragraf biçimle', origin: 'basit metin formatter.', example: 'fmt -w 72 mektup.txt', tip: 'E-posta/README için' },
        { cmd: 'column', cat: 'Metin', en: 'Column', tr: 'Sütun hizala', origin: 'çıktıyı tablo gibi hizalar.', example: 'mount | column -t', tip: 'Okunabilirlik' },
        { cmd: 'expand', cat: 'Metin', en: 'Expand', tr: 'Tab → boşluk', origin: 'tab karakterlerini boşluğa çevirir.', example: 'expand -t 4 file', tip: 'unexpand tersi' },
        { cmd: 'unexpand', cat: 'Metin', en: 'Unexpand', tr: 'Boşluk → tab', origin: 'expand’in tersi.', example: 'unexpand -t 4 file' },
        { cmd: 'od', cat: 'Metin', en: 'Octal Dump', tr: 'Sekizlik / binary döküm', origin: 'octal dump — baytları gösterir.', example: 'od -An -tx1 file', tip: 'hexdump alternatifi' },
        { cmd: 'hexdump', cat: 'Metin', en: 'Hex Dump', tr: 'Onaltılık döküm', origin: 'hexadecimal dump.', example: 'hexdump -C file | head', tip: 'Binary inceleme', aliases: ['hex bak'] },
        { cmd: 'xxd', cat: 'Metin', en: 'Hex Dump (vim)', tr: 'Hex görüntüle / geri çevir', origin: 'vim ile gelen hex dump aracı.', example: 'xxd file | head', tip: 'xxd -r ile geri' },
        { cmd: 'strings', cat: 'Metin', en: 'Strings', tr: 'Okunabilir dizgileri çıkar', origin: 'binary içinden printable string’leri çeker.', example: 'strings /bin/ls | head', tip: 'Malware/teşhis', aliases: ['string çıkar'] },
        { cmd: 'base64', cat: 'Metin', en: 'Base64', tr: 'Base64 kodla/çöz', origin: 'MIME base64 encoding.', example: 'echo hi | base64', tip: 'decode: base64 -d', aliases: ['base64encode'] },
        { cmd: 'md5sum', cat: 'Dosya', en: 'MD5 Checksum', tr: 'MD5 özeti', origin: 'Message Digest 5 hash.', example: 'md5sum file.iso', tip: 'Bütünlük kontrolü (zayıf kriptografi)', aliases: ['md5', 'dosya hash'] },
        { cmd: 'sha256sum', cat: 'Dosya', en: 'SHA-256 Checksum', tr: 'SHA-256 özeti', origin: 'Secure Hash Algorithm 256-bit.', example: 'sha256sum file.iso', tip: 'İndirme doğrulama', aliases: ['sha256', 'checksum'] },
        { cmd: 'sha1sum', cat: 'Dosya', en: 'SHA-1 Checksum', tr: 'SHA-1 özeti', origin: 'Eski SHA-1; mümkünse sha256.', example: 'sha1sum file' },
        { cmd: 'cksum', cat: 'Dosya', en: 'Checksum', tr: 'CRC checksum', origin: 'POSIX CRC ve byte sayısı.', example: 'cksum file' },
        { cmd: 'cmp', cat: 'Dosya', en: 'Compare', tr: 'Bayt bayt karşılaştır', origin: 'compare — ilk farkın yerini söyler.', example: 'cmp a.bin b.bin', tip: 'diff metin; cmp binary' },
        { cmd: 'yes', cat: 'Shell', en: 'Yes', tr: 'Sürekli “y” bas', origin: 'Onay diyaloglarını otomatikleştirir.', example: 'yes | apt install -y pkg 2>/dev/null; yes | head', tip: 'Dikkatli kullan' },
        { cmd: 'true', cat: 'Shell', en: 'True', tr: 'Hep başarılı (exit 0)', origin: 'Boolean true — hiçbir şey yapmadan 0 döner.', example: 'true && echo ok', tip: 'Placeholder komut' },
        { cmd: 'false', cat: 'Shell', en: 'False', tr: 'Hep başarısız (exit 1)', origin: 'Boolean false.', example: 'false || echo fail' },
        { cmd: 'test', cat: 'Shell', en: 'Test', tr: 'Koşul test et', origin: '[ ] ile aynı aile; dosya/string karşılaştırma.', example: 'test -f /etc/hosts && echo var', tip: 'Script if’lerinde', aliases: ['koşul', 'if test'] },
        { cmd: '[', cat: 'Shell', en: 'Test builtin', tr: 'Koşul ([ ])', origin: 'test komutunun kapanışı ].', example: '[ -d /tmp ] && echo dir', tip: 'Boşluklara dikkat' },
        { cmd: 'expr', cat: 'Shell', en: 'Evaluate Expression', tr: 'İfade hesapla', origin: 'Eski aritmetik/string aracı; $(( )) tercih edilir.', example: 'expr 3 + 4' },
        { cmd: 'bc', cat: 'Shell', en: 'Basic Calculator', tr: 'Hesap makinesi', origin: 'arbitrary-precision calculator.', example: 'echo "scale=2; 10/3" | bc', tip: 'Script hesapları', aliases: ['hesap makinesi'] },
        { cmd: 'dc', cat: 'Shell', en: 'Desk Calculator', tr: 'RPN hesap', origin: 'ters Polonyalı notasyon hesap makinesi.', example: 'echo "2 3 + p" | dc' },
        { cmd: 'factor', cat: 'Shell', en: 'Factor', tr: 'Asal çarpanlara ayır', origin: 'sayıyı çarpanlarına böler.', example: 'factor 12' },
        { cmd: 'seq', cat: 'Shell', en: 'Sequence', tr: 'Sayı dizisi üret', origin: 'sequence of numbers.', example: 'seq 1 5', tip: 'for i in $(seq 1 10)', aliases: ['sayı üret'] },
        { cmd: 'shuf', cat: 'Metin', en: 'Shuffle', tr: 'Karıştır', origin: 'satırları rastgele karıştırır.', example: 'shuf -n 1 isimler.txt', tip: 'Rastgele seçim', aliases: ['rastgele satır'] },
        { cmd: 'sort -R', cat: 'Metin', en: 'Sort Random', tr: 'Rastgele sırala', origin: 'sort -R ≈ shuf benzeri.', example: 'sort -R file | head' },
        { cmd: 'tee -a', cat: 'Metin', en: 'Tee Append', tr: 'Dosyaya ekleyerek yaz', origin: 'tee append mode.', example: 'echo x | tee -a log.txt' },

        // —— Kullanıcı / grup ——
        { cmd: 'useradd', cat: 'Yetki', en: 'User Add', tr: 'Kullanıcı ekle', origin: 'user + add. Düşük seviye hesap oluşturma.', example: 'sudo useradd -m -s /bin/bash ali', tip: 'adduser daha etkileşimli (Debian)', aliases: ['kullanıcı ekle', 'yeni kullanıcı'] },
        { cmd: 'adduser', cat: 'Yetki', en: 'Add User', tr: 'Kullanıcı ekle (yardımcı)', origin: 'Debian’da useradd sarmalayıcısı; soru sorar.', example: 'sudo adduser ali', tip: 'Yeni başlayan için kolay', aliases: ['kullanıcı oluştur'] },
        { cmd: 'userdel', cat: 'Yetki', en: 'User Delete', tr: 'Kullanıcı sil', origin: 'user + delete.', example: 'sudo userdel -r ali', tip: '-r home’u da siler', aliases: ['kullanıcı sil'] },
        { cmd: 'usermod', cat: 'Yetki', en: 'User Modify', tr: 'Kullanıcıyı değiştir', origin: 'user + modify. Grup, shell, home…', example: 'sudo usermod -aG sudo ali', tip: '-aG gruba ekle', aliases: ['gruba ekle', 'kullanıcı düzenle'] },
        { cmd: 'groupadd', cat: 'Yetki', en: 'Group Add', tr: 'Grup ekle', origin: 'group + add.', example: 'sudo groupadd developers', aliases: ['grup oluştur'] },
        { cmd: 'groupdel', cat: 'Yetki', en: 'Group Delete', tr: 'Grup sil', origin: 'group + delete.', example: 'sudo groupdel developers' },
        { cmd: 'groups', cat: 'Yetki', en: 'Groups', tr: 'Gruplarım', origin: 'kullanıcının grup üyeliğini listeler.', example: 'groups', tip: 'id daha detaylı' },
        { cmd: 'getent', cat: 'Yetki', en: 'Get Entries', tr: 'NSS veritabanı oku', origin: 'passwd/group/hosts… kayıtlarını Name Service Switch üzerinden alır.', example: 'getent passwd root', tip: 'LDAP’lı ortamlarda kritik', aliases: ['passwd bak'] },
        { cmd: 'who', cat: 'Sistem', en: 'Who', tr: 'Kim giriş yapmış', origin: 'who is logged in.', example: 'who', tip: 'w daha zengin', aliases: ['kim bağlı'] },
        { cmd: 'w', cat: 'Sistem', en: 'What / Who', tr: 'Kim + ne yapıyor', origin: 'who + ne çalıştırıyor + load.', example: 'w', tip: 'uptime + who birleşimi' },
        { cmd: 'last', cat: 'Sistem', en: 'Last', tr: 'Son girişler', origin: 'wtmp’den son login kayıtları.', example: 'last -n 20', tip: 'Güvenlik incelemesi', aliases: ['son oturum', 'kim girdi'] },
        { cmd: 'lastb', cat: 'Sistem', en: 'Last Bad', tr: 'Başarısız girişler', origin: 'bad login attempts (btmp).', example: 'sudo lastb | head', tip: 'Brute-force izi' },
        { cmd: 'lastlog', cat: 'Sistem', en: 'Last Log', tr: 'Kullanıcı bazlı son giriş', origin: 'her hesabın son login zamanı.', example: 'lastlog | head' },
        { cmd: 'login', cat: 'Sistem', en: 'Login', tr: 'Oturum aç', origin: 'login prompt sürecinin komutu.', example: 'login', tip: 'Genelde getty çağırır' },
        { cmd: 'logout', cat: 'Sistem', en: 'Logout', tr: 'Oturumu kapat', origin: 'shell’den çıkış (login shell).', example: 'logout', tip: 'exit de olur' },
        { cmd: 'exit', cat: 'Shell', en: 'Exit', tr: 'Çık', origin: 'shell/script’ten çıkış koduyla ayrıl.', example: 'exit 0', tip: 'SSH oturumunu kapatır', aliases: ['çıkış', 'oturumu kapat'] },
        { cmd: 'newgrp', cat: 'Yetki', en: 'New Group', tr: 'Aktif grubu değiştir', origin: 'geçici primary group değiştirir.', example: 'newgrp docker' },
        { cmd: 'sg', cat: 'Yetki', en: 'Set Group id', tr: 'Grup kimliğiyle çalıştır', origin: 'komutu başka GID ile çalıştırır.', example: 'sg docker -c "docker ps"' },
        { cmd: 'runuser', cat: 'Yetki', en: 'Run User', tr: 'Kullanıcı olarak çalıştır', origin: 'su benzeri, PAM’sız senaryolar için.', example: 'runuser -u www-data -- ls' },
        { cmd: 'chroot', cat: 'Sistem', en: 'Change Root', tr: 'Kök dizini değiştir', origin: 'process için / kökünü başka dizine kaydırır (jail hissi).', example: 'sudo chroot /mnt/sysroot /bin/bash', tip: 'Rescue / build', aliases: ['jail', 'kök değiştir'] },
        { cmd: 'unshare', cat: 'Sistem', en: 'Unshare namespaces', tr: 'Namespace ayır', origin: 'Linux namespace’lerini paylaşmadan çalıştır (container temeli).', example: 'unshare -m /bin/bash', tip: 'İleri seviye' },
        { cmd: 'nsenter', cat: 'Sistem', en: 'Namespace Enter', tr: 'Namespace’e gir', origin: 'başka sürecin namespace’ine gir (konteyner debug).', example: 'nsenter -t PID -m -u -n -i', tip: 'docker exec alternatifi teşhis' },

        // —— Süreç / performans ——
        { cmd: 'pstree', cat: 'Süreç', en: 'Process Tree', tr: 'Süreç ağacı', origin: 'process tree — ebeveyn/çocuk ilişkisi.', example: 'pstree -p', tip: 'PID 1’den dallanma', aliases: ['süreç ağacı'] },
        { cmd: 'pidof', cat: 'Süreç', en: 'PID Of', tr: 'İsmin PID’i', origin: 'program adından PID bulur.', example: 'pidof sshd', tip: 'pgrep alternatifi' },
        { cmd: 'time', cat: 'Süreç', en: 'Time', tr: 'Süre ölç', origin: 'komutun real/user/sys süresini ölçer.', example: 'time ls -R /etc', tip: '/usr/bin/time daha detaylı', aliases: ['ne kadar sürdü'] },
        { cmd: 'timeout', cat: 'Süreç', en: 'Timeout', tr: 'Süre aşımında kes', origin: 'N saniye sonra komutu öldürür.', example: 'timeout 5s ping 1.1.1.1', tip: 'Asılı script önleme', aliases: ['zaman aşımı'] },
        { cmd: 'watch', cat: 'Süreç', en: 'Watch', tr: 'Periyodik çalıştır / izle', origin: 'komutu tekrar tekrar çalıştırıp ekranı yeniler.', example: 'watch -n 1 df -h', tip: 'Canlı izleme', aliases: ['sürekli izle', 'her saniye'] },
        { cmd: 'vmstat', cat: 'Sistem', en: 'Virtual Memory Stat', tr: 'VM / CPU / IO özeti', origin: 'virtual memory statistics.', example: 'vmstat 1 5', tip: 'si/so swap izi', aliases: ['swap bak'] },
        { cmd: 'iostat', cat: 'Disk', en: 'I/O Stat', tr: 'Disk IO istatistiği', origin: 'input/output statistics (sysstat).', example: 'iostat -xz 1', tip: 'apt install sysstat', aliases: ['disk io', 'yavaş disk'] },
        { cmd: 'mpstat', cat: 'Sistem', en: 'Multiprocessor Stat', tr: 'CPU başına istatistik', origin: 'her CPU çekirdeği için.', example: 'mpstat -P ALL 1', tip: 'sysstat paketi' },
        { cmd: 'sar', cat: 'Sistem', en: 'System Activity Reporter', tr: 'Sistem aktivite raporu', origin: 'tarihsel performans arşivi.', example: 'sar -u 1 3', tip: 'sysstat' },
        { cmd: 'pidstat', cat: 'Süreç', en: 'PID Stat', tr: 'Süreç bazlı CPU/IO', origin: 'process-level stats.', example: 'pidstat 1', tip: 'sysstat' },
        { cmd: 'free -m', cat: 'Sistem', en: 'Free (MB)', tr: 'Bellek (MB)', origin: 'free -m megabayt cinsinden.', example: 'free -m' },
        { cmd: 'uptime -p', cat: 'Sistem', en: 'Uptime Pretty', tr: 'Okunur uptime', origin: 'pretty print.', example: 'uptime -p' },
        { cmd: 'nproc', cat: 'Sistem', en: 'Number of Processors', tr: 'CPU sayısı', origin: 'kaç işlemci (çekirdek) kullanılabilir.', example: 'nproc', tip: 'make -j$(nproc)', aliases: ['kaç çekirdek'] },
        { cmd: 'lscpu', cat: 'Sistem', en: 'List CPU', tr: 'CPU mimarisi', origin: 'CPU topolojisi ve bayrakları.', example: 'lscpu', tip: 'Sanallaştırma bayrakları', aliases: ['işlemci bilgisi'] },
        { cmd: 'lsusb', cat: 'Sistem', en: 'List USB', tr: 'USB cihazları listele', origin: 'USB bus cihazları.', example: 'lsusb', aliases: ['usb listele'] },
        { cmd: 'lspci', cat: 'Sistem', en: 'List PCI', tr: 'PCI cihazları', origin: 'PCI bus (ağ, GPU…).', example: 'lspci -nn', tip: '-k sürücü', aliases: ['ekran kartı', 'ağ kartı pci'] },
        { cmd: 'lsmod', cat: 'Sistem', en: 'List Modules', tr: 'Kernel modülleri', origin: 'yüklü kernel module listesi.', example: 'lsmod | head', tip: 'modprobe ile yükle', aliases: ['driver modül'] },
        { cmd: 'modprobe', cat: 'Sistem', en: 'Module Probe', tr: 'Modül yükle/kaldır', origin: 'bağımlılıklarla birlikte module yükler.', example: 'sudo modprobe overlay', tip: '-r kaldırır' },
        { cmd: 'insmod', cat: 'Sistem', en: 'Insert Module', tr: 'Modül sok', origin: 'düşük seviye module insert.', example: 'sudo insmod mymod.ko', tip: 'Genelde modprobe kullanın' },
        { cmd: 'rmmod', cat: 'Sistem', en: 'Remove Module', tr: 'Modül çıkar', origin: 'module unload.', example: 'sudo rmmod mymod' },
        { cmd: 'sysctl', cat: 'Sistem', en: 'System Control', tr: 'Kernel parametresi', origin: '/proc/sys değerlerini okur/yazar.', example: 'sysctl -a | head; sysctl net.ipv4.ip_forward', tip: 'Kalıcı: /etc/sysctl.d/', aliases: ['kernel ayarı', 'ip forward'] },
        { cmd: 'hostnamectl', cat: 'Sistem', en: 'Hostname Control', tr: 'Makine adı / OS bilgisi', origin: 'systemd hostname yöneticisi.', example: 'hostnamectl', tip: 'set-hostname ile değiştir' },
        { cmd: 'timedatectl', cat: 'Sistem', en: 'Time Date Control', tr: 'Saat / saat dilimi', origin: 'systemd zaman yöneticisi.', example: 'timedatectl status', tip: 'NTP sync', aliases: ['saat ayarla', 'timezone'] },
        { cmd: 'localectl', cat: 'Sistem', en: 'Locale Control', tr: 'Dil / klavye', origin: 'locale ve keymap.', example: 'localectl status', aliases: ['klavye dili'] },
        { cmd: 'loginctl', cat: 'Sistem', en: 'Login Control', tr: 'Oturum / seat yönetimi', origin: 'systemd-logind arayüzü.', example: 'loginctl list-sessions' },
        { cmd: 'resolvectl', cat: 'Ağ', en: 'Resolve Control', tr: 'DNS çözümleyici kontrol', origin: 'systemd-resolved arayüzü.', example: 'resolvectl status', tip: 'DNS teşhisi', aliases: ['dns ayarı'] },
        { cmd: 'networkctl', cat: 'Ağ', en: 'Network Control', tr: 'systemd-networkd durum', origin: 'link/network birimleri.', example: 'networkctl status' },

        // —— Disk / FS ——
        { cmd: 'blkid', cat: 'Disk', en: 'Block ID', tr: 'UUID / etiket gör', origin: 'block device kimlikleri.', example: 'sudo blkid', tip: 'fstab için UUID', aliases: ['uuid bak'] },
        { cmd: 'findmnt', cat: 'Disk', en: 'Find Mount', tr: 'Mount ağacını bul', origin: 'hangi FS nereye bağlı — ağaç görünüm.', example: 'findmnt', tip: 'mount’tan okunaklı', aliases: ['nereye bağlı'] },
        { cmd: 'df -i', cat: 'Disk', en: 'Disk Free Inodes', tr: 'Inode doluluğu', origin: 'df -i inode kullanımı.', example: 'df -i', tip: 'Küçük dosya bombası', aliases: ['inode doldu'] },
        { cmd: 'du -sh', cat: 'Disk', en: 'Disk Usage Summary', tr: 'Özet boyut', origin: 'du -s human.', example: 'du -sh /var/*', aliases: ['klasör boyutu'] },
        { cmd: 'ncdu', cat: 'Disk', en: 'NCurses Du', tr: 'İnteraktif disk kullanımı', origin: 'du + ncurses arayüz.', example: 'ncdu /', tip: 'apt install ncdu', aliases: ['disk nereye gitti'] },
        { cmd: 'lsblk -f', cat: 'Disk', en: 'List Block FS', tr: 'FS tipi ile bloklar', origin: 'lsblk -f.', example: 'lsblk -f' },
        { cmd: 'parted', cat: 'Disk', en: 'Partition Editor', tr: 'Bölüm düzenleyici', origin: 'GPT/MBR partition aracı.', example: 'sudo parted -l', tip: 'Dikkat: yıkıcı', aliases: ['partisyon'] },
        { cmd: 'mkfs.ext4', cat: 'Disk', en: 'Make Filesystem ext4', tr: 'ext4 dosya sistemi oluştur', origin: 'make filesystem.', example: 'sudo mkfs.ext4 /dev/sdX1', tip: 'VERİ SİLER', aliases: ['format at', 'biçimlendir'] },
        { cmd: 'mkfs.xfs', cat: 'Disk', en: 'Make Filesystem XFS', tr: 'XFS oluştur', origin: 'XFS FS format.', example: 'sudo mkfs.xfs /dev/sdX1' },
        { cmd: 'fsck', cat: 'Disk', en: 'File System Check', tr: 'Dosya sistemi kontrol/onar', origin: 'filesystem check.', example: 'sudo fsck /dev/sdX1', tip: 'Unmount iken', aliases: ['disk onar', 'bozuk disk'] },
        { cmd: 'e2fsck', cat: 'Disk', en: 'ext2/3/4 fsck', tr: 'ext FS kontrol', origin: 'ext ailesi için fsck.', example: 'sudo e2fsck -f /dev/sdX1' },
        { cmd: 'resize2fs', cat: 'Disk', en: 'Resize ext FS', tr: 'ext boyutlandır', origin: 'ext filesystem büyüt/küçült.', example: 'sudo resize2fs /dev/sdX1' },
        { cmd: 'tune2fs', cat: 'Disk', en: 'Tune ext FS', tr: 'ext ayarları', origin: 'etiket, mount count, UUID…', example: 'sudo tune2fs -l /dev/sdX1' },
        { cmd: 'xfs_repair', cat: 'Disk', en: 'XFS Repair', tr: 'XFS onar', origin: 'XFS fsck karşılığı.', example: 'sudo xfs_repair /dev/sdX1' },
        { cmd: 'mount -a', cat: 'Disk', en: 'Mount All', tr: 'fstab’takilerin hepsini bağla', origin: 'mount all from fstab.', example: 'sudo mount -a', tip: 'fstab test', aliases: ['fstab bağla'] },
        { cmd: 'umount -l', cat: 'Disk', en: 'Lazy Unmount', tr: 'Tembel ayır', origin: 'lazy unmount — meşgulse sonra ayırır.', example: 'sudo umount -l /mnt' },
        { cmd: 'losetup', cat: 'Disk', en: 'Loop Setup', tr: 'Loop cihazı bağla', origin: 'dosyayı blok cihaz gibi gösterir (ISO).', example: 'sudo losetup -fP image.img', aliases: ['iso bağla'] },
        { cmd: 'dd', cat: 'Disk', en: 'Data Description / Disk Dump', tr: 'Ham kopya / imaj', origin: 'tarihî “convert and copy”; disk klon, ISO yazma.', example: 'sudo dd if=/dev/sdX of=disk.img bs=4M status=progress', tip: 'if/of karıştırma felakettir', aliases: ['disk kopyala', 'iso yaz', 'usb yaz'] },
        { cmd: 'pvcreate', cat: 'Disk', en: 'PV Create', tr: 'LVM fiziksel hacim', origin: 'Physical Volume oluştur.', example: 'sudo pvcreate /dev/sdX', tip: 'LVM zinciri: pv→vg→lv' },
        { cmd: 'vgcreate', cat: 'Disk', en: 'VG Create', tr: 'LVM volume group', origin: 'Volume Group.', example: 'sudo vgcreate vg0 /dev/sdX' },
        { cmd: 'lvcreate', cat: 'Disk', en: 'LV Create', tr: 'LVM mantıksal hacim', origin: 'Logical Volume.', example: 'sudo lvcreate -L 10G -n data vg0', aliases: ['lvm oluştur'] },
        { cmd: 'lvs', cat: 'Disk', en: 'LV Status', tr: 'LV listele', origin: 'logical volumes.', example: 'sudo lvs' },
        { cmd: 'vgs', cat: 'Disk', en: 'VG Status', tr: 'VG listele', origin: 'volume groups.', example: 'sudo vgs' },
        { cmd: 'pvs', cat: 'Disk', en: 'PV Status', tr: 'PV listele', origin: 'physical volumes.', example: 'sudo pvs' },
        { cmd: 'cryptsetup', cat: 'Disk', en: 'Crypt Setup', tr: 'Disk şifreleme (LUKS)', origin: 'dm-crypt/LUKS yönetimi.', example: 'sudo cryptsetup luksOpen /dev/sdX1 secret', tip: 'Şifreli disk', aliases: ['disk şifrele', 'luks'] },
        { cmd: 'smartctl', cat: 'Disk', en: 'SMART Control', tr: 'Disk sağlık (SMART)', origin: 'Self-Monitoring Analysis Reporting Technology.', example: 'sudo smartctl -a /dev/sda', tip: 'apt install smartmontools', aliases: ['disk sağlığı', 'hdd bozuluyor'] },
        { cmd: 'hdparm', cat: 'Disk', en: 'Hard Disk Parameters', tr: 'Disk parametre / hız testi', origin: 'ATA disk ayarları.', example: 'sudo hdparm -Tt /dev/sda' },

        // —— Arşiv ek ——
        { cmd: 'bzip2', cat: 'Arşiv', en: 'Burrows-Wheeler Zip', tr: 'bzip2 sıkıştır', origin: 'gzip’ten farklı algoritma; .bz2.', example: 'bzip2 -k file', tip: 'tar -j' },
        { cmd: 'xz', cat: 'Arşiv', en: 'XZ Utils', tr: 'xz sıkıştır', origin: 'yüksek oranlı sıkıştırma; .xz.', example: 'xz -k file', tip: 'tar -J', aliases: ['xz sıkıştır'] },
        { cmd: 'zstd', cat: 'Arşiv', en: 'Zstandard', tr: 'zstd sıkıştır', origin: 'Facebook kaynaklı hızlı sıkıştırma.', example: 'zstd -T0 file', tip: 'Modern yedeklerde popüler' },
        { cmd: 'tar -xvf', cat: 'Arşiv', en: 'Tar Extract Verbose', tr: 'Arşivi aç (ayrıntılı)', origin: 'extract verbose file.', example: 'tar -xvf archive.tar', aliases: ['tar aç', 'arşiv aç'] },
        { cmd: 'tar -czvf', cat: 'Arşiv', en: 'Tar Create gz', tr: 'gzip tar oluştur', origin: 'create gzip verbose file.', example: 'tar -czvf a.tgz dir/', aliases: ['tar oluştur', 'sıkıştırılmış yedek'] },
        { cmd: 'cpio', cat: 'Arşiv', en: 'Copy In/Out', tr: 'cpio arşivi', origin: 'copy in/out — initramfs vb.', example: 'find . | cpio -o > arch.cpio' },
        { cmd: 'ar', cat: 'Arşiv', en: 'Archiver', tr: 'Statik kütüphane arşivi', origin: '.a dosyaları; eski arşivleyici.', example: 'ar t libfoo.a' },
        { cmd: 'rpm', cat: 'Paket', en: 'RPM Package Manager', tr: 'RPM paket aracı', origin: 'Red Hat Package Manager.', example: 'rpm -qa | head', tip: 'RHEL ailesi' },
        { cmd: 'rpm -i', cat: 'Paket', en: 'RPM Install', tr: 'RPM kur', origin: 'install rpm file.', example: 'sudo rpm -ivh pkg.rpm' },
        { cmd: 'alien', cat: 'Paket', en: 'Alien', tr: 'Paket formatı çevir', origin: 'rpm↔deb dönüştürücü.', example: 'sudo alien -d pkg.rpm' },
        { cmd: 'snap', cat: 'Paket', en: 'Snap', tr: 'Snap paket', origin: 'Canonical’ın konteynerimsi paketleri.', example: 'snap list', aliases: ['snap kur'] },
        { cmd: 'flatpak', cat: 'Paket', en: 'Flatpak', tr: 'Flatpak uygulama', origin: 'sandbox’lı masaüstü uygulama dağıtımı.', example: 'flatpak list' },
        { cmd: 'pip', cat: 'Paket', en: 'Pip Installs Packages', tr: 'Python paket kurucu', origin: 'pip installs packages (recursive joke).', example: 'pip install requests', tip: 'venv içinde kullanın', aliases: ['python paket'] },
        { cmd: 'npm', cat: 'Paket', en: 'Node Package Manager', tr: 'Node paket yöneticisi', origin: 'JavaScript paket ekosistemi.', example: 'npm install', aliases: ['node paket'] },
        { cmd: 'gem', cat: 'Paket', en: 'RubyGem', tr: 'Ruby paket', origin: 'Ruby gem’leri.', example: 'gem list' },
        { cmd: 'cargo', cat: 'Geliştirme', en: 'Cargo', tr: 'Rust paket/derleme', origin: 'Rust’un “kargo” gemisi — build & deps.', example: 'cargo build --release' },
        { cmd: 'go', cat: 'Geliştirme', en: 'Go toolchain', tr: 'Go dili aracı', origin: 'Go programlama dili CLI.', example: 'go build .' },

        // —— Ağ geniş ——
        { cmd: 'ip addr', cat: 'Ağ', en: 'IP Address', tr: 'IP adreslerini göster', origin: 'ip addr show.', example: 'ip addr show', aliases: ['ip adresim', 'ip bak'] },
        { cmd: 'ip route', cat: 'Ağ', en: 'IP Route', tr: 'Rota tablosu', origin: 'routing table.', example: 'ip route', aliases: ['gateway', 'varsayılan ağ geçidi'] },
        { cmd: 'ip link', cat: 'Ağ', en: 'IP Link', tr: 'Arayüz link durumu', origin: 'network interface link.', example: 'ip link set eth0 up', aliases: ['arayüz aç'] },
        { cmd: 'ip neigh', cat: 'Ağ', en: 'IP Neighbor', tr: 'ARP komşuları', origin: 'neighbor/ARP tablosu.', example: 'ip neigh', tip: 'Eski: arp -a' },
        { cmd: 'arp', cat: 'Ağ', en: 'ARP', tr: 'ARP tablosu (eski)', origin: 'Address Resolution Protocol aracı.', example: 'arp -n' },
        { cmd: 'route', cat: 'Ağ', en: 'Route', tr: 'Rota (eski)', origin: 'eski routing komutu; yerine ip route.', example: 'route -n' },
        { cmd: 'ethtool', cat: 'Ağ', en: 'Ethernet Tool', tr: 'NIC ayar / hız', origin: 'ethernet kartı parametreleri.', example: 'sudo ethtool eth0', tip: 'Link speed/duplex' },
        { cmd: 'iwconfig', cat: 'Ağ', en: 'Wireless Config', tr: 'Kablosuz (eski)', origin: 'wireless extension; yerine iw.', example: 'iwconfig' },
        { cmd: 'iw', cat: 'Ağ', en: 'Wireless nl80211', tr: 'Kablosuz modern araç', origin: 'nl80211 wireless CLI.', example: 'iw dev', aliases: ['wifi'] },
        { cmd: 'nmcli', cat: 'Ağ', en: 'NetworkManager CLI', tr: 'NetworkManager komut satırı', origin: 'NM’yi CLI ile yönet.', example: 'nmcli device status', tip: 'Masaüstü distrolar', aliases: ['wifi bağlan', 'ağ bağlan'] },
        { cmd: 'nmtui', cat: 'Ağ', en: 'NetworkManager TUI', tr: 'NM metin arayüzü', origin: 'text user interface.', example: 'nmtui', tip: 'Menülü ağ ayarı' },
        { cmd: 'hostname -I', cat: 'Ağ', en: 'Hostname IPs', tr: 'Tüm IP’leri yazdır', origin: 'hostname -I.', example: 'hostname -I' },
        { cmd: 'ping6', cat: 'Ağ', en: 'Ping IPv6', tr: 'IPv6 ping', origin: 'IPv6 için ping.', example: 'ping6 -c 3 ::1' },
        { cmd: 'traceroute6', cat: 'Ağ', en: 'Traceroute IPv6', tr: 'IPv6 rota izle', origin: 'IPv6 traceroute.', example: 'traceroute6 example.com' },
        { cmd: 'mtr', cat: 'Ağ', en: 'My Traceroute', tr: 'Canlı traceroute+ping', origin: 'traceroute + ping birleşimi.', example: 'mtr -r example.com', tip: 'apt install mtr', aliases: ['ağ gecikme'] },
        { cmd: 'tracepath', cat: 'Ağ', en: 'Trace Path', tr: 'MTU ile yol izle', origin: 'root gerektirmeden path/MTU.', example: 'tracepath example.com' },
        { cmd: 'ss -s', cat: 'Ağ', en: 'Socket Summary', tr: 'Soket özeti', origin: 'ss summary.', example: 'ss -s' },
        { cmd: 'ss -tulpn', cat: 'Ağ', en: 'Sockets Listening', tr: 'Dinleyen portlar + PID', origin: 'tcp/udp listening numeric processes.', example: 'ss -tulpn', aliases: ['hangi port dinliyor', 'port listele'] },
        { cmd: 'curl -O', cat: 'Ağ', en: 'Curl Output file', tr: 'URL’den dosya indir (adıyla)', origin: 'remote name ile kaydet.', example: 'curl -O https://example.com/f.zip' },
        { cmd: 'curl -I', cat: 'Ağ', en: 'Curl Headers', tr: 'Sadece HTTP başlıkları', origin: 'HEAD benzeri.', example: 'curl -I https://example.com', aliases: ['http başlık'] },
        { cmd: 'wget -c', cat: 'Ağ', en: 'Wget Continue', tr: 'İndirmeye devam et', origin: 'continue partial download.', example: 'wget -c URL', aliases: ['indirmenin devamı'] },
        { cmd: 'scp -r', cat: 'Ağ', en: 'SCP Recursive', tr: 'Dizin güvenli kopyala', origin: 'scp recursive.', example: 'scp -r dir user@host:/tmp/' },
        { cmd: 'sftp', cat: 'Ağ', en: 'SSH File Transfer', tr: 'Etkileşimli güvenli FTP', origin: 'SSH üzerinde FTP benzeri.', example: 'sftp user@host', aliases: ['dosya gönder ssh'] },
        { cmd: 'rsync -avz', cat: 'Arşiv', en: 'Rsync Archive Compress', tr: 'Arşiv + sıkıştır eşitle', origin: 'klasik rsync bayrak seti.', example: 'rsync -avz src/ user@host:dst/', aliases: ['uzak yedek'] },
        { cmd: 'ssh-keygen', cat: 'Ağ', en: 'SSH Key Generate', tr: 'SSH anahtarı üret', origin: 'asimetrik anahtar çifti oluşturur.', example: 'ssh-keygen -t ed25519', tip: 'Parola koyun', aliases: ['ssh anahtar', 'key oluştur'] },
        { cmd: 'ssh-copy-id', cat: 'Ağ', en: 'SSH Copy ID', tr: 'Public key’i sunucuya kopyala', origin: 'authorized_keys’e ekler.', example: 'ssh-copy-id user@host', tip: 'Şifresiz giriş', aliases: ['şifresiz ssh'] },
        { cmd: 'ssh-add', cat: 'Ağ', en: 'SSH Add', tr: 'Anahtarı agent’a ekle', origin: 'ssh-agent’a private key yükler.', example: 'ssh-add ~/.ssh/id_ed25519' },
        { cmd: 'nc -l', cat: 'Ağ', en: 'Netcat Listen', tr: 'Port dinle', origin: 'netcat listen mode.', example: 'nc -l -p 1234', tip: 'Lab/transfer' },
        { cmd: 'socat', cat: 'Ağ', en: 'SOcket CAT', tr: 'Gelişmiş soket rölesi', origin: 'netcat’in İsviçre çakısı hali.', example: 'socat - TCP:host:80' },
        { cmd: 'telnet', cat: 'Ağ', en: 'Teletype Network', tr: 'Telnet (eski/ham TCP)', origin: 'şifresiz uzak terminal; bugün port testi için.', example: 'telnet host 25', tip: 'Prod yönetim için SSH kullanın' },
        { cmd: 'ftp', cat: 'Ağ', en: 'File Transfer Protocol', tr: 'FTP istemci', origin: 'klasik FTP — şifresiz; sftp tercih.', example: 'ftp host' },
        { cmd: 'openssl', cat: 'Güvenlik', en: 'OpenSSL', tr: 'TLS/sertifika araç kutusu', origin: 'açık kaynak SSL/TLS kütüphanesi CLI.', example: 'openssl s_client -connect example.com:443', tip: 'Sertifika teşhisi', aliases: ['sertifika bak', 'ssl test'] },
        { cmd: 'gpg', cat: 'Güvenlik', en: 'GNU Privacy Guard', tr: 'Şifreleme / imza', origin: 'OpenPGP uygulaması.', example: 'gpg --gen-key', aliases: ['pgp', 'dosya şifrele'] },
        { cmd: 'ufw', cat: 'Güvenlik', en: 'Uncomplicated Firewall', tr: 'Basit güvenlik duvarı', origin: 'iptables/nft’ye basit arayüz (Ubuntu).', example: 'sudo ufw allow 22/tcp', tip: 'sudo ufw enable', aliases: ['firewall aç', 'port aç ufw'] },
        { cmd: 'firewall-cmd', cat: 'Güvenlik', en: 'FirewallCMD', tr: 'firewalld kontrol', origin: 'RHEL firewalld CLI.', example: 'sudo firewall-cmd --list-all', aliases: ['firewalld'] },
        { cmd: 'iptables -L', cat: 'Güvenlik', en: 'IPTables List', tr: 'iptables kurallarını listele', origin: 'list filter rules.', example: 'sudo iptables -L -n -v', aliases: ['firewall kuralları'] },
        { cmd: 'nft', cat: 'Güvenlik', en: 'Netfilter Tables', tr: 'nftables aracı', origin: 'iptables’ın moderni.', example: 'sudo nft list ruleset' },
        { cmd: 'fail2ban-client', cat: 'Güvenlik', en: 'Fail2Ban Client', tr: 'Fail2ban yönetimi', origin: 'brute-force ban sistemi.', example: 'sudo fail2ban-client status sshd', aliases: ['ban listesi', 'brute force koruma'] },
        { cmd: 'ausearch', cat: 'Güvenlik', en: 'Audit Search', tr: 'Audit log ara', origin: 'Linux auditd kayıtlarında ara.', example: 'sudo ausearch -m USER_LOGIN', tip: 'auditd' },
        { cmd: 'aureport', cat: 'Güvenlik', en: 'Audit Report', tr: 'Audit raporu', origin: 'audit özet raporları.', example: 'sudo aureport -au' },
        { cmd: 'getfacl', cat: 'Yetki', en: 'Get File ACL', tr: 'ACL izinlerini gör', origin: 'Access Control List oku.', example: 'getfacl dosya', aliases: ['acl bak'] },
        { cmd: 'setfacl', cat: 'Yetki', en: 'Set File ACL', tr: 'ACL izni ver', origin: 'ACL yaz.', example: 'setfacl -m u:ali:rw dosya', aliases: ['acl ver'] },
        { cmd: 'lsattr', cat: 'Dosya', en: 'List Attributes', tr: 'ext öznitelikleri listele', origin: 'immutable vb. attribute.', example: 'lsattr file', tip: 'chattr +i' },
        { cmd: 'chattr', cat: 'Dosya', en: 'Change Attributes', tr: 'ext öznitelik değiştir', origin: '+i = silinemez/değiştirilemez.', example: 'sudo chattr +i /etc/resolv.conf', tip: 'Kilitli config', aliases: ['dosya kilitle', 'immutable'] },
        { cmd: 'setcap', cat: 'Yetki', en: 'Set Capabilities', tr: 'Capability ver', origin: 'Linux capabilities bitleri.', example: 'sudo setcap cap_net_bind_service=+ep bin', tip: 'SUID alternatifi' },
        { cmd: 'getcap', cat: 'Yetki', en: 'Get Capabilities', tr: 'Capability gör', origin: 'dosyadaki capability’leri listeler.', example: 'getcap -r / 2>/dev/null | head', aliases: ['capability ara'] },
        { cmd: 'sestatus', cat: 'Güvenlik', en: 'SELinux Status', tr: 'SELinux durumu', origin: 'SELinux enforcing/permissive.', example: 'sestatus', tip: 'RHEL', aliases: ['selinux'] },
        { cmd: 'getenforce', cat: 'Güvenlik', en: 'Get Enforce', tr: 'SELinux modu', origin: 'Enforcing/Permissive/Disabled.', example: 'getenforce' },
        { cmd: 'setenforce', cat: 'Güvenlik', en: 'Set Enforce', tr: 'SELinux modunu ayarla', origin: 'geçici enforcing aç/kapa.', example: 'sudo setenforce 0', tip: 'Prod’da kalıcı kapatmayın' },
        { cmd: 'aa-status', cat: 'Güvenlik', en: 'AppArmor Status', tr: 'AppArmor durumu', origin: 'Ubuntu/SUSE MAC profil durumu.', example: 'sudo aa-status', aliases: ['apparmor'] },

        // —— Güvenlik araçları ——
        { cmd: 'nmap -sV', cat: 'Güvenlik', en: 'Nmap Service Version', tr: 'Servis sürüm keşfi', origin: 'nmap service/version detection.', example: 'nmap -sV 127.0.0.1', aliases: ['port tarama detay'] },
        { cmd: 'nmap -sS', cat: 'Güvenlik', en: 'Nmap SYN Scan', tr: 'SYN taraması', origin: 'half-open TCP scan.', example: 'sudo nmap -sS target', tip: 'Yetkili ortam', aliases: ['syn scan'] },
        { cmd: 'nmap -sn', cat: 'Güvenlik', en: 'Nmap Ping Scan', tr: 'Host keşfi (ping sweep)', origin: 'no port scan — kim ayakta.', example: 'nmap -sn 192.168.1.0/24', aliases: ['ağda kim var'] },
        { cmd: 'masscan', cat: 'Güvenlik', en: 'Mass Scan', tr: 'Çok hızlı port tarama', origin: 'internet-scale port scanner.', example: 'sudo masscan -p80,443 10.0.0.0/8 --rate 1000', tip: 'Yasal kapsam!' },
        { cmd: 'nikto', cat: 'Güvenlik', en: 'Nikto', tr: 'Web zafiyet tarayıcı', origin: 'isim: Nikto (film); web misconfig tarar.', example: 'nikto -h http://127.0.0.1', aliases: ['web tarama'] },
        { cmd: 'sqlmap', cat: 'Güvenlik', en: 'SQL Map', tr: 'SQL injection otomasyonu', origin: 'SQL injection’ı haritalar/istismar eder (yetkili test).', example: 'sqlmap -u "http://lab?id=1" --batch', tip: 'Yalnızca izinli lab', aliases: ['sql injection'] },
        { cmd: 'hydra', cat: 'Güvenlik', en: 'Hydra', tr: 'Ağ login brute-force', origin: 'çok başlı canavar miti — çok protokol brute force.', example: 'hydra -h', tip: 'Yetkili test', aliases: ['brute force'] },
        { cmd: 'john', cat: 'Güvenlik', en: 'John the Ripper', tr: 'Parola kırıcı (hash)', origin: 'efsane hash cracker.', example: 'john --wordlist=rockyou.txt hashes.txt', aliases: ['şifre kır hash'] },
        { cmd: 'hashcat', cat: 'Güvenlik', en: 'Hashcat', tr: 'GPU hash kırıcı', origin: '“hash” + “cat”/catalyze.', example: 'hashcat -m 0 hashes.txt wordlist' },
        { cmd: 'tcpdump -i', cat: 'Güvenlik', en: 'TCPDump Interface', tr: 'Arayüzde paket yakala', origin: 'tcpdump -i any.', example: 'sudo tcpdump -i any port 53', aliases: ['paket yakala'] },
        { cmd: 'tshark', cat: 'Güvenlik', en: 'Terminal Wireshark', tr: 'Wireshark CLI', origin: 'Wireshark’ın terminal hali.', example: 'tshark -i eth0 -c 20', aliases: ['wireshark cli'] },
        { cmd: 'wireshark', cat: 'Güvenlik', en: 'Wireshark', tr: 'Grafik paket analiz', origin: 'köpekbalığı (shark) — ağ paketlerini “avlar”.', example: 'wireshark', aliases: ['paket analiz'] },
        { cmd: 'burpsuite', cat: 'Güvenlik', en: 'Burp Suite', tr: 'HTTP proxy / web test', origin: '“burp” = geğirti — web trafiğini yakalar.', example: 'burpsuite', tip: 'Proxy 8080', aliases: ['burp', 'http proxy'] },
        { cmd: 'metasploit', cat: 'Güvenlik', en: 'Metasploit Framework', tr: 'Exploit çerçevesi', origin: 'sömürü (exploit) framework’ü.', example: 'msfconsole', tip: 'Yetkili lab', aliases: ['msfconsole', 'exploit'] },
        { cmd: 'searchsploit', cat: 'Güvenlik', en: 'Search ExploitDB', tr: 'Exploit veritabanında ara', origin: 'Exploit-DB offline arama.', example: 'searchsploit apache 2.4', aliases: ['exploit ara'] },
        { cmd: 'dirb', cat: 'Güvenlik', en: 'DIRB', tr: 'Web dizin brute-force', origin: 'directory brute.', example: 'dirb http://target/', aliases: ['gizli klasör bul'] },
        { cmd: 'gobuster', cat: 'Güvenlik', en: 'Go Buster', tr: 'Hızlı dizin/DNS brute', origin: 'Go ile yazılmış busting aracı.', example: 'gobuster dir -u http://t -w wordlist.txt' },
        { cmd: 'ffuf', cat: 'Güvenlik', en: 'Fuzz Faster U Fool', tr: 'Web fuzzer', origin: 'hızlı web fuzzing.', example: 'ffuf -u http://t/FUZZ -w wordlist' },
        { cmd: 'whatweb', cat: 'Güvenlik', en: 'WhatWeb', tr: 'Web teknolojisi tespit', origin: 'site hangi stack?', example: 'whatweb http://target' },
        { cmd: 'wpscan', cat: 'Güvenlik', en: 'WordPress Scan', tr: 'WordPress tarayıcı', origin: 'WP zafiyet/plugin tarama.', example: 'wpscan --url http://target' },
        { cmd: 'enum4linux', cat: 'Güvenlik', en: 'Enum for Linux', tr: 'SMB/Windows enum', origin: 'Samba/Windows bilgi toplama.', example: 'enum4linux -a target' },
        { cmd: 'smbclient', cat: 'Ağ', en: 'SMB Client', tr: 'SMB/CIFS istemci', origin: 'Windows paylaşımlarına bağlan.', example: 'smbclient -L //host -N', aliases: ['windows paylaşım'] },
        { cmd: 'mount.cifs', cat: 'Disk', en: 'Mount CIFS', tr: 'SMB paylaşımı bağla', origin: 'CIFS mount yardımcı.', example: 'sudo mount -t cifs //h/share /mnt -o user=u' },
        { cmd: 'nfsstat', cat: 'Ağ', en: 'NFS Stat', tr: 'NFS istatistik', origin: 'Network File System stats.', example: 'nfsstat -c' },
        { cmd: 'showmount', cat: 'Ağ', en: 'Show Mount', tr: 'NFS export listele', origin: 'uzak NFS paylaşımlarını gösterir.', example: 'showmount -e nfs-server' },

        // —— Systemd / log ——
        { cmd: 'systemctl start', cat: 'Sistem', en: 'Start Unit', tr: 'Servisi başlat', origin: 'unit’i hemen başlatır.', example: 'sudo systemctl start nginx', aliases: ['servis başlat'] },
        { cmd: 'systemctl stop', cat: 'Sistem', en: 'Stop Unit', tr: 'Servisi durdur', origin: 'unit’i durdurur.', example: 'sudo systemctl stop nginx', aliases: ['servis durdur'] },
        { cmd: 'systemctl restart', cat: 'Sistem', en: 'Restart Unit', tr: 'Servisi yeniden başlat', origin: 'stop+start.', example: 'sudo systemctl restart nginx', aliases: ['servisi yeniden başlat', 'servis restart'] },
        { cmd: 'systemctl reload', cat: 'Sistem', en: 'Reload Unit', tr: 'Config’i yeniden yükle', origin: 'mümkünse process öldürmeden reload.', example: 'sudo systemctl reload nginx', aliases: ['config reload'] },
        { cmd: 'systemctl enable', cat: 'Sistem', en: 'Enable Unit', tr: 'Boot’ta otomatik başlat', origin: 'kalıcı enable.', example: 'sudo systemctl enable nginx', aliases: ['otomatik başlat'] },
        { cmd: 'systemctl disable', cat: 'Sistem', en: 'Disable Unit', tr: 'Boot’tan çıkar', origin: 'enable tersi.', example: 'sudo systemctl disable nginx' },
        { cmd: 'systemctl status', cat: 'Sistem', en: 'Status Unit', tr: 'Servis durumu', origin: 'aktif mi, son log satırları.', example: 'systemctl status ssh', aliases: ['servis durumu'] },
        { cmd: 'systemctl daemon-reload', cat: 'Sistem', en: 'Daemon Reload', tr: 'Unit dosyalarını yeniden yükle', origin: 'unit dosyası değişince şart.', example: 'sudo systemctl daemon-reload', aliases: ['systemd yenile'] },
        { cmd: 'systemctl mask', cat: 'Sistem', en: 'Mask Unit', tr: 'Servisi tamamen engelle', origin: 'start edilemez hale getirir.', example: 'sudo systemctl mask bluetooth' },
        { cmd: 'systemctl list-units', cat: 'Sistem', en: 'List Units', tr: 'Birimleri listele', origin: 'yüklü unit’ler.', example: 'systemctl list-units --type=service' },
        { cmd: 'systemctl list-timers', cat: 'Zaman', en: 'List Timers', tr: 'Systemd zamanlayıcılar', origin: 'cron alternatifi timer’lar.', example: 'systemctl list-timers', aliases: ['systemd cron'] },
        { cmd: 'journalctl -xe', cat: 'Sistem', en: 'Journal Explain', tr: 'Son hatalar + açıklama', origin: '-x explanation, -e end.', example: 'journalctl -xe', aliases: ['son hata', 'neden fail'] },
        { cmd: 'journalctl -f', cat: 'Sistem', en: 'Journal Follow', tr: 'Canlı journal', origin: 'tail -f benzeri.', example: 'journalctl -f', aliases: ['canlı log'] },
        { cmd: 'journalctl -u', cat: 'Sistem', en: 'Journal Unit', tr: 'Servis logu', origin: 'belirli unit logları.', example: 'journalctl -u nginx -n 100', aliases: ['servis log'] },
        { cmd: 'journalctl --since', cat: 'Sistem', en: 'Journal Since', tr: 'Zamandan beri log', origin: 'zaman filtresi.', example: 'journalctl --since "1 hour ago"' },
        { cmd: 'logger', cat: 'Sistem', en: 'Logger', tr: 'Syslog’a mesaj yaz', origin: 'script’ten syslog’a yazmak için.', example: 'logger "yedek bitti"', tip: 'Cron log’ları' },
        { cmd: 'logrotate', cat: 'Sistem', en: 'Log Rotate', tr: 'Log döndür / budama', origin: 'eski log’ları sıkıştırıp yeniler.', example: 'sudo logrotate -f /etc/logrotate.conf', aliases: ['log temizle', 'log rotate'] },
        { cmd: 'dmesg -w', cat: 'Sistem', en: 'Dmesg Wait', tr: 'Canlı kernel log', origin: 'dmesg follow.', example: 'dmesg -w', aliases: ['canlı kernel log'] },

        // —— Editör / geliştirme ek ——
        { cmd: 'vimdiff', cat: 'Editör', en: 'Vim Diff', tr: 'Vim ile fark gör', origin: 'iki dosyayı yan yana diff.', example: 'vimdiff a.conf b.conf' },
        { cmd: 'view', cat: 'Editör', en: 'View', tr: 'Salt okunur vim', origin: 'vim -R.', example: 'view /etc/passwd' },
        { cmd: 'ed', cat: 'Editör', en: 'Editor', tr: 'Satır editörü (antik)', origin: 'orijinal Unix editörü.', example: 'ed file', tip: 'Öğretici merak' },
        { cmd: 'make -j', cat: 'Geliştirme', en: 'Make Parallel', tr: 'Paralel derle', origin: 'job sayısı kadar paralel.', example: 'make -j$(nproc)' },
        { cmd: 'cmake', cat: 'Geliştirme', en: 'CMake', tr: 'Çapraz platform build', origin: 'cross-platform makefile generator.', example: 'cmake -B build && cmake --build build' },
        { cmd: 'gcc -o', cat: 'Geliştirme', en: 'GCC Output', tr: 'Çıktı binary adı', origin: '-o output.', example: 'gcc -Wall -o app app.c' },
        { cmd: 'g++', cat: 'Geliştirme', en: 'GNU C++ Compiler', tr: 'C++ derleyici', origin: 'gplusplus.', example: 'g++ -o app app.cpp' },
        { cmd: 'clang', cat: 'Geliştirme', en: 'C Language Family Frontend', tr: 'LLVM C/C++ derleyici', origin: 'LLVM projesi derleyicisi.', example: 'clang -o app app.c' },
        { cmd: 'ldd', cat: 'Geliştirme', en: 'List Dynamic Dependencies', tr: 'Paylaşımlı kütüphane bağımlılıkları', origin: 'binary’nin .so ihtiyaçları.', example: 'ldd /bin/ls', tip: 'Missing library teşhisi', aliases: ['kütüphane eksik'] },
        { cmd: 'nm', cat: 'Geliştirme', en: 'Name list', tr: 'Sembol tablosu', origin: 'object/binary sembolleri.', example: 'nm -D /lib/x86_64-linux-gnu/libc.so.6 | head' },
        { cmd: 'objdump', cat: 'Geliştirme', en: 'Object Dump', tr: 'Nesne/disassemble döküm', origin: 'binary içeriğini dök.', example: 'objdump -d a.out | head' },
        { cmd: 'readelf', cat: 'Geliştirme', en: 'Read ELF', tr: 'ELF başlık oku', origin: 'ELF format bilgisi.', example: 'readelf -h /bin/ls' },
        { cmd: 'strip', cat: 'Geliştirme', en: 'Strip', tr: 'Sembol sil (küçült)', origin: 'debug sembollerini çıkarır.', example: 'strip app' },
        { cmd: 'gdb', cat: 'Geliştirme', en: 'GNU Debugger', tr: 'GNU hata ayıklayıcı', origin: 'debugger.', example: 'gdb ./app', tip: 'coredump analizi', aliases: ['debug', 'çökme analizi'] },
        { cmd: 'strace -p', cat: 'Sistem', en: 'Strace Attach', tr: 'Çalışan sürece bağlan', origin: 'PID’e attach.', example: 'sudo strace -p 1234', aliases: ['süreç izle'] },
        { cmd: 'ltrace', cat: 'Sistem', en: 'Library Trace', tr: 'Kütüphane çağrılarını izle', origin: 'library call trace (strace’in userspace hali).', example: 'ltrace ls' },
        { cmd: 'perf', cat: 'Sistem', en: 'Performance', tr: 'Linux performans profiler', origin: 'CPU profiling, flamegraph kaynağı.', example: 'perf top', tip: 'İleri performans', aliases: ['cpu profil'] },
        { cmd: 'valgrind', cat: 'Geliştirme', en: 'Valgrind', tr: 'Bellek hata ayıklayıcı', origin: 'memcheck vb. araçlar.', example: 'valgrind ./app', aliases: ['memory leak'] },
        { cmd: 'git', cat: 'Geliştirme', en: 'Git', tr: 'Versiyon kontrol', origin: 'İngilizce slang “git” + Linus’un esprisi; dağıtık VCS.', example: 'git status', tip: 'Modern yazılım temeli', aliases: ['versiyon kontrol', 'commit'] },
        { cmd: 'git clone', cat: 'Geliştirme', en: 'Git Clone', tr: 'Depoyu kopyala', origin: 'uzak repo’yu klonla.', example: 'git clone https://…', aliases: ['repo indir'] },
        { cmd: 'git pull', cat: 'Geliştirme', en: 'Git Pull', tr: 'Uzaktan çek + birleştir', origin: 'fetch + merge.', example: 'git pull', aliases: ['güncelle repo'] },
        { cmd: 'git commit', cat: 'Geliştirme', en: 'Git Commit', tr: 'Değişikliği kaydet', origin: 'commit = taahhüt / kayıt.', example: 'git commit -m "mesaj"' },
        { cmd: 'git push', cat: 'Geliştirme', en: 'Git Push', tr: 'Uzağa gönder', origin: 'push = itmek.', example: 'git push origin main' },
        { cmd: 'git diff', cat: 'Geliştirme', en: 'Git Diff', tr: 'Değişiklik farkı', origin: 'diff staged/unstaged.', example: 'git diff' },
        { cmd: 'git log', cat: 'Geliştirme', en: 'Git Log', tr: 'Commit geçmişi', origin: 'history of commits.', example: 'git log --oneline | head' },
        { cmd: 'diff -u', cat: 'Metin', en: 'Unified Diff', tr: 'Birleşik fark formatı', origin: 'patch için standart format.', example: 'diff -u old new > f.patch' },
        { cmd: 'patch', cat: 'Metin', en: 'Patch', tr: 'Yama uygula', origin: 'diff çıktısını dosyaya uygular.', example: 'patch -p1 < fix.patch', aliases: ['yama', 'diff uygula'] },

        // —— Shell güç ——
        { cmd: 'bash', cat: 'Shell', en: 'Bourne Again Shell', tr: 'Bash kabuğu', origin: 'Bourne shell’in “yeniden doğuşu” (pun: born again).', example: 'bash --version', aliases: ['kabuk'] },
        { cmd: 'sh', cat: 'Shell', en: 'Shell', tr: 'POSIX shell', origin: 'klasik shell; çoğu yerde bash/dash symlink.', example: 'sh script.sh' },
        { cmd: 'zsh', cat: 'Shell', en: 'Z Shell', tr: 'Z kabuğu', origin: 'güçlü tamamlama/theme ekosistemi.', example: 'zsh' },
        { cmd: 'fish', cat: 'Shell', en: 'Friendly Interactive Shell', tr: 'Dostça etkileşimli shell', origin: 'kullanıcı dostu defaults.', example: 'fish' },
        { cmd: 'screen', cat: 'Shell', en: 'Screen', tr: 'Terminal çoklayıcı (eski)', origin: 'oturumu arka planda tutar.', example: 'screen -S isim', tip: 'tmux daha modern', aliases: ['oturum tut'] },
        { cmd: 'tmux', cat: 'Shell', en: 'Terminal Multiplexer', tr: 'Terminal çoklayıcı', origin: 'bir terminalde çok pencere/oturum.', example: 'tmux new -s work', tip: 'SSH kopunca iş sürer', aliases: ['oturum kaydet', 'ssh kopmasın'] },
        { cmd: 'byobu', cat: 'Shell', en: 'Byobu', tr: 'tmux/screen sarmalayıcı', origin: 'Japonca byōbu (paravan) — hazır tuşlar.', example: 'byobu' },
        { cmd: 'script', cat: 'Shell', en: 'Script', tr: 'Oturum kaydı tut', origin: 'terminaldeki her şeyi dosyaya kaydeder.', example: 'script oturum.log', tip: 'Kanıt / eğitim', aliases: ['ekran kaydı terminal'] },
        { cmd: 'scriptreplay', cat: 'Shell', en: 'Script Replay', tr: 'Oturum kaydını oynat', origin: 'script -t ile kaydı tekrar oynatır.', example: 'scriptreplay timing log' },
        { cmd: 'pushd', cat: 'Gezinme', en: 'Push Directory', tr: 'Dizini yığına koy & git', origin: 'directory stack.', example: 'pushd /var/log', tip: 'popd ile geri', aliases: ['geri döneceğim dizin'] },
        { cmd: 'popd', cat: 'Gezinme', en: 'Pop Directory', tr: 'Yığından geri dön', origin: 'pushd yığınından çık.', example: 'popd' },
        { cmd: 'dirs', cat: 'Gezinme', en: 'Directories stack', tr: 'Dizin yığını', origin: 'pushd stack’ini gösterir.', example: 'dirs -v' },
        { cmd: 'realpath -s', cat: 'Dosya', en: 'Realpath without resolve', tr: 'Symlink çözmeden yol', origin: 'canonicalize without expansion.', example: 'realpath -s link' },
        { cmd: 'readlink', cat: 'Dosya', en: 'Read Link', tr: 'Symlink hedefini oku', origin: 'symbolic link değeri.', example: 'readlink -f /usr/bin/java', aliases: ['symlink nereye'] },
        { cmd: 'stat -c', cat: 'Dosya', en: 'Stat Custom', tr: 'Özel formatlı stat', origin: 'format string ile alan seç.', example: 'stat -c "%a %n" file', tip: 'İzin sayısal' },
        { cmd: 'namei', cat: 'Dosya', en: 'Name inode', tr: 'Yol bileşenlerini çözümle', origin: 'path’i adım adım permission ile gösterir.', example: 'namei -l /var/log/syslog', tip: 'Permission denied teşhisi' },
        { cmd: 'pathchk', cat: 'Dosya', en: 'Path Check', tr: 'Yol adını doğrula', origin: 'taşınabilirlik için path kontrol.', example: 'pathchk -p "a b"' },
        { cmd: 'mktemp', cat: 'Dosya', en: 'Make Temporary', tr: 'Geçici dosya/dizin oluştur', origin: 'güvenli rastgele temp path.', example: 'tmp=$(mktemp)', tip: 'Script’lerde /tmp/foo yasak', aliases: ['geçici dosya'] },
        { cmd: 'tempfile', cat: 'Dosya', en: 'Temp File', tr: 'Geçici dosya (eski)', origin: 'debian yardımcı; mktemp tercih.', example: 'tempfile' },
        { cmd: 'iconv', cat: 'Metin', en: 'International Convert', tr: 'Karakter seti dönüştür', origin: 'encoding dönüşümü.', example: 'iconv -f ISO-8859-9 -t UTF-8 f > g', aliases: ['encoding', 'türkçe karakter bozuldu'] },
        { cmd: 'recode', cat: 'Metin', en: 'Recode', tr: 'Kodlama dönüştür', origin: 'iconv benzeri eski araç.', example: 'recode ..UTF-8 < f' },
        { cmd: 'dos2unix', cat: 'Metin', en: 'DOS to Unix', tr: 'CRLF → LF', origin: 'Windows satır sonunu Unix’e çevirir.', example: 'dos2unix script.sh', tip: 'Bash\\r hatası', aliases: ['satır sonu düzelt', 'crlf'] },
        { cmd: 'unix2dos', cat: 'Metin', en: 'Unix to DOS', tr: 'LF → CRLF', origin: 'tersi.', example: 'unix2dos file.txt' },
        { cmd: 'file -i', cat: 'Dosya', en: 'File MIME', tr: 'MIME / charset söyle', origin: 'file --mime.', example: 'file -i dosya.txt' },
        { cmd: 'watch -d', cat: 'Süreç', en: 'Watch Differences', tr: 'Değişeni vurgula', origin: 'watch highlight diffs.', example: 'watch -d free -h' },
        { cmd: 'parallel', cat: 'Shell', en: 'GNU Parallel', tr: 'Paralel iş çalıştır', origin: 'xargs’ın parallel güçlüsü.', example: 'ls | parallel gzip', tip: 'apt install parallel' },
        { cmd: 'expect', cat: 'Shell', en: 'Expect', tr: 'Etkileşimli diyaloğu otomatikleştir', origin: 'spawn/expect/send — şifre prompt otomasyonu.', example: 'expect script.exp', tip: 'SSH key tercih edilir' },
        { cmd: 'dialog', cat: 'Shell', en: 'Dialog', tr: 'Metin kutusu UI', origin: 'shell script’e TUI pencere.', example: 'dialog --msgbox "Merhaba" 5 30' },
        { cmd: 'whiptail', cat: 'Shell', en: 'Whiptail', tr: 'Newt tabanlı dialog', origin: 'Debian installer tarzı kutular.', example: 'whiptail --yesno "Devam?" 8 40' },

        // —— Konteyner / virt ——
        { cmd: 'docker', cat: 'Geliştirme', en: 'Docker', tr: 'Konteyner motoru', origin: 'liman işçisi — konteyner “yükler”.', example: 'docker ps', aliases: ['konteyner', 'container'] },
        { cmd: 'docker ps', cat: 'Geliştirme', en: 'Docker PS', tr: 'Çalışan konteynerler', origin: 'process list analogu.', example: 'docker ps -a', aliases: ['konteyner listele'] },
        { cmd: 'docker images', cat: 'Geliştirme', en: 'Docker Images', tr: 'İmajları listele', origin: 'local images.', example: 'docker images' },
        { cmd: 'docker build', cat: 'Geliştirme', en: 'Docker Build', tr: 'Dockerfile’dan imaj yap', origin: 'image build.', example: 'docker build -t app .', aliases: ['imaj oluştur'] },
        { cmd: 'docker run', cat: 'Geliştirme', en: 'Docker Run', tr: 'Konteyner çalıştır', origin: 'container çalıştır.', example: 'docker run --rm -it ubuntu bash', aliases: ['konteyner çalıştır'] },
        { cmd: 'docker exec', cat: 'Geliştirme', en: 'Docker Exec', tr: 'Konteyner içinde komut', origin: 'çalışan konteynere gir.', example: 'docker exec -it cname bash', aliases: ['konteynere gir'] },
        { cmd: 'docker logs', cat: 'Geliştirme', en: 'Docker Logs', tr: 'Konteyner logları', origin: 'stdout/stderr log.', example: 'docker logs -f cname' },
        { cmd: 'docker compose', cat: 'Geliştirme', en: 'Docker Compose', tr: 'Çok konteyner orkestrasyon (tek host)', origin: 'compose.yaml ile ayağa kaldır.', example: 'docker compose up -d', aliases: ['compose'] },
        { cmd: 'podman', cat: 'Geliştirme', en: 'Pod Manager', tr: 'Daemonless konteyner', origin: 'Red Hat; docker-compatible.', example: 'podman ps' },
        { cmd: 'kubectl', cat: 'Geliştirme', en: 'Kubernetes Control', tr: 'Kubernetes kontrol aracı', origin: 'kube + control.', example: 'kubectl get pods -A', aliases: ['k8s', 'kubernetes'] },
        { cmd: 'helm', cat: 'Geliştirme', en: 'Helm', tr: 'Kubernetes paket yöneticisi', origin: 'dümen — k8s chart’ları.', example: 'helm list' },
        { cmd: 'virsh', cat: 'Sistem', en: 'Virtualization Shell', tr: 'libvirt VM yönetimi', origin: 'KVM/QEMU yönetir.', example: 'virsh list --all', aliases: ['sanal makine', 'vm listele'] },
        { cmd: 'qemu-img', cat: 'Disk', en: 'QEMU Image', tr: 'VM disk imajı', origin: 'qcow2/raw imaj işlemleri.', example: 'qemu-img info disk.qcow2' },

        // —— Zaman / cron ek ——
        { cmd: 'crontab -l', cat: 'Zaman', en: 'Crontab List', tr: 'Cron işlerini listele', origin: 'list user crontab.', example: 'crontab -l', aliases: ['cron listele'] },
        { cmd: 'crontab -e', cat: 'Zaman', en: 'Crontab Edit', tr: 'Cron düzenle', origin: 'edit crontab.', example: 'crontab -e', aliases: ['cron ekle'] },
        { cmd: 'crontab -r', cat: 'Zaman', en: 'Crontab Remove', tr: 'Tüm cron’u sil', origin: 'remove crontab — dikkat!', example: 'crontab -r' },
        { cmd: 'anacron', cat: 'Zaman', en: 'Anacron', tr: 'Kaçırılan cron’u yakala', origin: 'sürekli açık olmayan makineler için.', example: 'sudo anacron -n' },
        { cmd: 'atq', cat: 'Zaman', en: 'At Queue', tr: 'at kuyruğunu göster', origin: 'at jobs queue.', example: 'atq' },
        { cmd: 'atrm', cat: 'Zaman', en: 'At Remove', tr: 'at işini sil', origin: 'remove at job.', example: 'atrm 3' },
        { cmd: 'date -u', cat: 'Sistem', en: 'Date UTC', tr: 'UTC saat', origin: 'Coordinated Universal Time.', example: 'date -u' },
        { cmd: 'hwclock', cat: 'Sistem', en: 'Hardware Clock', tr: 'Donanım saati', origin: 'BIOS/UEFI RTC.', example: 'sudo hwclock --show' },
        { cmd: 'cal -y', cat: 'Sistem', en: 'Calendar Year', tr: 'Yıllık takvim', origin: 'cal year.', example: 'cal -y' },
        { cmd: 'sleep', cat: 'Shell', en: 'Sleep', tr: 'Bekle / uyu', origin: 'N saniye pause.', example: 'sleep 5', tip: 'Script beklemesi', aliases: ['bekle', 'saniye bekle'] },
        { cmd: 'usleep', cat: 'Shell', en: 'Micro Sleep', tr: 'Mikrosaniye bekle (eski)', origin: 'microsecond sleep; sleep 0.1 tercih.', example: 'usleep 500000' },

        // —— Paket ek ——
        { cmd: 'apt update', cat: 'Paket', en: 'APT Update', tr: 'Paket listesini yenile', origin: 'repo indekslerini çek.', example: 'sudo apt update', aliases: ['paket listesi güncelle'] },
        { cmd: 'apt upgrade', cat: 'Paket', en: 'APT Upgrade', tr: 'Paketleri yükselt', origin: 'kurulu paketleri güncelle.', example: 'sudo apt upgrade', aliases: ['sistem güncelle'] },
        { cmd: 'apt full-upgrade', cat: 'Paket', en: 'APT Full Upgrade', tr: 'Gerekirse paket çıkararak yükselt', origin: 'dist-upgrade mantığı.', example: 'sudo apt full-upgrade' },
        { cmd: 'apt remove', cat: 'Paket', en: 'APT Remove', tr: 'Paket kaldır', origin: 'binary’leri sil; config kalabilir.', example: 'sudo apt remove pkg', aliases: ['program kaldır'] },
        { cmd: 'apt purge', cat: 'Paket', en: 'APT Purge', tr: 'Paket + config sil', origin: 'purge configs too.', example: 'sudo apt purge pkg' },
        { cmd: 'apt search', cat: 'Paket', en: 'APT Search', tr: 'Paket ara', origin: 'repo’da isim ara.', example: 'apt search htop', aliases: ['paket ara'] },
        { cmd: 'apt show', cat: 'Paket', en: 'APT Show', tr: 'Paket detayı', origin: 'metadata göster.', example: 'apt show curl' },
        { cmd: 'apt-cache policy', cat: 'Paket', en: 'APT Policy', tr: 'Hangi sürüm nereden', origin: 'candidate version.', example: 'apt-cache policy nginx' },
        { cmd: 'dpkg -i', cat: 'Paket', en: 'DPKG Install', tr: 'deb dosyasından kur', origin: 'local .deb install.', example: 'sudo dpkg -i pkg.deb', tip: 'Eksik bağımlılık: apt -f install' },
        { cmd: 'dpkg -l', cat: 'Paket', en: 'DPKG List', tr: 'Kurulu deb paketleri', origin: 'list packages.', example: 'dpkg -l | grep nginx' },
        { cmd: 'dpkg -L', cat: 'Paket', en: 'DPKG List files', tr: 'Paketin dosyaları', origin: 'which files belong to pkg.', example: 'dpkg -L curl', aliases: ['paket nereye kurdu'] },
        { cmd: 'dpkg -S', cat: 'Paket', en: 'DPKG Search file', tr: 'Dosya hangi pakette', origin: 'reverse search.', example: 'dpkg -S /bin/ls', aliases: ['bu dosya hangi paket'] },
        { cmd: 'apt-file', cat: 'Paket', en: 'APT File', tr: 'Repo’da dosya ara', origin: 'kurulu olmayan paketlerde dosya arar.', example: 'apt-file search bin/htop', tip: 'apt install apt-file && apt-file update' },
        { cmd: 'dnf install', cat: 'Paket', en: 'DNF Install', tr: 'DNF ile kur', origin: 'Fedora/RHEL.', example: 'sudo dnf install htop' },
        { cmd: 'dnf update', cat: 'Paket', en: 'DNF Update', tr: 'DNF güncelle', origin: 'upgrade packages.', example: 'sudo dnf update' },
        { cmd: 'dnf search', cat: 'Paket', en: 'DNF Search', tr: 'DNF paket ara', origin: 'search.', example: 'dnf search nginx' },
        { cmd: 'pacman', cat: 'Paket', en: 'Package Manager', tr: 'Arch paket yöneticisi', origin: 'paket “bekçisi”.', example: 'sudo pacman -Syu', tip: 'Arch/Manjaro' },
        { cmd: 'zypper', cat: 'Paket', en: 'Zypper', tr: 'openSUSE paket', origin: 'zipper/zypper kelime oyunu.', example: 'sudo zypper install htop' },
        { cmd: 'apk', cat: 'Paket', en: 'Alpine Package Keeper', tr: 'Alpine paket', origin: 'Alpine Linux.', example: 'apk add curl' },
        { cmd: 'brew', cat: 'Paket', en: 'Homebrew', tr: 'macOS/Linux paket (brew)', origin: 'ev yapımı bira — kullanıcı alanı paketler.', example: 'brew install wget', tip: 'Linux’ta da var' },

        // —— Bilgi / yardım ek ——
        { cmd: 'man -k', cat: 'Yardım', en: 'Man Keyword', tr: 'Konuyla man ara', origin: '≈ apropos.', example: 'man -k password', aliases: ['konu ara man'] },
        { cmd: 'man 5', cat: 'Yardım', en: 'Man Section 5', tr: 'Dosya formatı kılavuzu', origin: 'section 5: file formats (fstab, sudoers).', example: 'man 5 sudoers' },
        { cmd: 'man 7', cat: 'Yardım', en: 'Man Section 7', tr: 'Genel kavramlar', origin: 'section 7: conventions, signal…', example: 'man 7 signal' },
        { cmd: 'tldr', cat: 'Yardım', en: 'Too Long; Didn’t Read', tr: 'Kısa örnekli yardım', origin: 'man’in pratik özeti.', example: 'tldr tar', tip: 'npm/pip ile kurulur', aliases: ['kısa yardım', 'örnek komut'] },
        { cmd: 'cheat', cat: 'Yardım', en: 'Cheat Sheet', tr: 'Çalışma kağıdı', origin: 'kişisel cheatsheet CLI.', example: 'cheat curl' },
        { cmd: 'help set', cat: 'Yardım', en: 'Help Set', tr: 'Bash set yardımı', origin: 'shell builtin help.', example: 'help set' },
        { cmd: 'type -a', cat: 'Yardım', en: 'Type All', tr: 'Tüm eşleşmeler', origin: 'alias+builtin+file hepsini göster.', example: 'type -a ls' },
        { cmd: 'command -v', cat: 'Yardım', en: 'Command Path', tr: 'Komut yolu (POSIX)', origin: 'which benzeri portable.', example: 'command -v python3' },
        { cmd: 'hash', cat: 'Shell', en: 'Hash', tr: 'Shell komut önbelleği', origin: 'bulunan komut yollarını cache’ler.', example: 'hash -r', tip: 'PATH değişince hash -r' },
        { cmd: 'bind', cat: 'Shell', en: 'Bind', tr: 'Readline tuş bağla', origin: 'bash keybindings.', example: 'bind -P | head' },
        { cmd: 'set', cat: 'Shell', en: 'Set', tr: 'Shell seçenek / değişken', origin: 'set -euo pipefail vb.', example: 'set -x', tip: 'Debug: set -x', aliases: ['debug aç'] },
        { cmd: 'unset', cat: 'Shell', en: 'Unset', tr: 'Değişkeni kaldır', origin: 'environment/shell var sil.', example: 'unset FOO' },
        { cmd: 'readonly', cat: 'Shell', en: 'Read Only', tr: 'Salt okunur değişken', origin: 'değiştirilemez var.', example: 'readonly PI=3.14' },
        { cmd: 'source', cat: 'Shell', en: 'Source', tr: 'Dosyayı bu shell’de çalıştır', origin: 'script’i alt süreç açmadan oku (. dosya).', example: 'source ~/.bashrc', tip: 'alias hemen gelsin', aliases: ['bashrc yükle', 'dot source'] },
        { cmd: '.', cat: 'Shell', en: 'Dot source', tr: 'source kısayolu', origin: 'POSIX . komutu = source.', example: '. ~/.bashrc' },
        { cmd: 'exec', cat: 'Shell', en: 'Execute', tr: 'Mevcut süreci değiştir', origin: 'shell’i başka programla değiştirir (PID aynı).', example: 'exec bash', tip: 'Script son satırı' },
        { cmd: 'eval', cat: 'Shell', en: 'Evaluate', tr: 'String’i komut gibi çalıştır', origin: 'dikkat: injection riski.', example: 'eval "$cmd"', tip: 'Mümkünse kaçının' },
        { cmd: 'printf %q', cat: 'Shell', en: 'Printf Quote', tr: 'Shell-escape bas', origin: 'güvenli quoting.', example: 'printf %q "$var"' },
        { cmd: 'column -s', cat: 'Metin', en: 'Column Separator', tr: 'Ayırıcıyla sütunla', origin: 'custom delimiter.', example: "column -t -s ':' /etc/passwd | head" },
        { cmd: 'jq', cat: 'Metin', en: 'JSON Query', tr: 'JSON işle', origin: 'JSON query — sed’in JSON hali.', example: 'curl -s api | jq .', tip: 'apt install jq', aliases: ['json parse', 'json bak'] },
        { cmd: 'yq', cat: 'Metin', en: 'YAML Query', tr: 'YAML işle', origin: 'jq’nin YAML kuzeni.', example: 'yq . file.yaml' },
        { cmd: 'xmllint', cat: 'Metin', en: 'XML Lint', tr: 'XML doğrula / sorgula', origin: 'libxml2 aracı.', example: 'xmllint --format file.xml' },
        { cmd: 'sqlite3', cat: 'Geliştirme', en: 'SQLite 3', tr: 'Gömülü SQL DB CLI', origin: 'SQL + lite.', example: 'sqlite3 db.sqlite ".tables"' },
        { cmd: 'psql', cat: 'Geliştirme', en: 'PostgreSQL', tr: 'PostgreSQL istemci', origin: 'postgres shell.', example: 'psql -U postgres -d mydb', aliases: ['postgres'] },
        { cmd: 'mysql', cat: 'Geliştirme', en: 'MySQL client', tr: 'MySQL/MariaDB istemci', origin: 'mysql CLI.', example: 'mysql -u root -p', aliases: ['mariadb'] },
        { cmd: 'redis-cli', cat: 'Geliştirme', en: 'Redis CLI', tr: 'Redis istemci', origin: 'in-memory DB konsolu.', example: 'redis-cli ping' },
        { cmd: 'mongosh', cat: 'Geliştirme', en: 'MongoDB Shell', tr: 'Mongo kabuğu', origin: 'modern mongo shell.', example: 'mongosh' },
        { cmd: 'curl -X POST', cat: 'Ağ', en: 'Curl POST', tr: 'HTTP POST isteği', origin: 'method POST.', example: 'curl -X POST -d "a=1" http://localhost/api', aliases: ['api post'] },
        { cmd: 'httpie', cat: 'Ağ', en: 'HTTPie', tr: 'Kullanıcı dostu HTTP istemci', origin: 'http komutu; JSON odaklı.', example: 'http GET example.com', tip: 'pip/apt httpie' },
        { cmd: 'dig +trace', cat: 'Ağ', en: 'DNS Trace', tr: 'DNS çözüm yolunu izle', origin: 'root’tan itibaren trace.', example: 'dig +trace example.com' },
        { cmd: 'host', cat: 'Ağ', en: 'Host', tr: 'Basit DNS bak', origin: 'hızlı name→IP.', example: 'host example.com' },
        { cmd: 'whois', cat: 'Ağ', en: 'Who Is', tr: 'Domain kayıt bilgisi', origin: 'whois veritabanı sorgusu.', example: 'whois example.com', aliases: ['domain sahibi'] },
        { cmd: 'ipcalc', cat: 'Ağ', en: 'IP Calculator', tr: 'Subnet hesapla', origin: 'CIDR/mask hesabı.', example: 'ipcalc 192.168.1.0/24', aliases: ['subnet hesap'] },
        { cmd: 'sipcalc', cat: 'Ağ', en: 'SIP Calc', tr: 'Gelişmiş IP hesap', origin: 'subnet calculator.', example: 'sipcalc 10.0.0.0/8' },
    ];

    window.COMMANDS = (window.COMMANDS || []).concat(extra);

    // ek Türkçe ifadeler
    Object.assign(window.SEARCH_PHRASES || (window.SEARCH_PHRASES = {}), {
        'servisi yeniden başlat': ['systemctl restart', 'systemctl'],
        'servis başlat': ['systemctl start', 'systemctl'],
        'servis durdur': ['systemctl stop', 'systemctl'],
        'format at': ['mkfs.ext4', 'mkfs.xfs', 'dd'],
        'usb yaz': ['dd'],
        'konteyner': ['docker', 'podman', 'docker ps'],
        'kubernetes': ['kubectl', 'helm'],
        'bellek sızıntısı': ['valgrind', 'free'],
        'satır sonu': ['dos2unix', 'unix2dos'],
        'şifresiz giriş': ['ssh-copy-id', 'ssh-keygen'],
        'port dinliyor': ['ss -tulpn', 'ss', 'lsof'],
        'ağda kim var': ['nmap -sn', 'nmap'],
        'json': ['jq'],
        'immutable': ['chattr', 'lsattr'],
        'lvm': ['pvcreate', 'vgcreate', 'lvcreate', 'lvs'],
        'disk sağlığı': ['smartctl'],
        'otomatik başlat': ['systemctl enable', 'crontab'],
        'canlı log': ['journalctl -f', 'tail'],
        'tmux': ['tmux', 'screen'],
        'ssh kopmasın': ['tmux', 'screen', 'nohup'],
    });

    window.CMD_CATEGORIES = ['Tümü', ...Array.from(new Set(window.COMMANDS.map(c => c.cat)))];

    // aliases zenginleştir (ana dosyadaki ile aynı mantık)
    const byCmd = {};
    Object.entries(window.SEARCH_PHRASES || {}).forEach(([phrase, cmds]) => {
        cmds.forEach(cmd => {
            if (!byCmd[cmd]) byCmd[cmd] = [];
            byCmd[cmd].push(phrase);
        });
    });
    window.COMMANDS.forEach(c => {
        const extraA = byCmd[c.cmd] || [];
        c.aliases = Array.from(new Set([...(c.aliases || []), ...extraA, c.tr]));
    });
})();
