/* Komut Ansiklopedisi — köken (İngilizce) + Türkçe karşılık */
window.COMMANDS = [
    // —— Gezinme & dosya ——
    { cmd: 'pwd', cat: 'Gezinme', en: 'Print Working Directory', tr: 'Çalışılan dizini yazdır', origin: 'print (yazdır) + working directory (üzerinde çalıştığın klasör). “Şu an neredeyim?”', example: 'pwd', tip: 'Prompt’taki yolu doğrulamak için ilk bakış.' },
    { cmd: 'cd', cat: 'Gezinme', en: 'Change Directory', tr: 'Dizin değiştir', origin: 'change (değiştir) + directory (dizin/klasör). Unix’ten beri kısa tutulmuş.', example: 'cd /var/log', tip: 'cd tek başına veya cd ~ → home’a döner. cd .. → bir üst.' },
    { cmd: 'ls', cat: 'Gezinme', en: 'List', tr: 'Listele', origin: 'list’in kısaltması. Klasör içeriğini listeler.', example: 'ls -lah', tip: '-l uzun, -a gizli (.), -h insan okunur boyut.' },
    { cmd: 'tree', cat: 'Gezinme', en: 'Tree', tr: 'Ağaç görünümü', origin: 'İngilizce tree = ağaç. Dizinleri ağaç şeklinde basar.', example: 'tree -L 2 /etc', tip: 'Apt ile kurulur: apt install tree' },
    { cmd: 'find', cat: 'Dosya', en: 'Find', tr: 'Bul', origin: 'find = bulmak. Ada, boyuta, izne göre dosya arar.', example: 'find /etc -name "*.conf"', tip: 'İçerik aramak için grep; isim/özellik için find.' },
    { cmd: 'locate', cat: 'Dosya', en: 'Locate', tr: 'Konumunu bul', origin: 'locate = yerini tespit et. Önceden indekslenmiş veritabanında hızlı arar.', example: 'locate passwd', tip: 'updatedb ile indeks yenilenir.' },
    { cmd: 'touch', cat: 'Dosya', en: 'Touch', tr: 'Dokun / oluştur', origin: 'touch = dokunmak. Dosyanın zaman damgasına “dokunur”; yoksa boş dosya yaratır.', example: 'touch notlar.txt', tip: 'Boş dosya oluşturmanın en hızlı yolu.' },
    { cmd: 'mkdir', cat: 'Dosya', en: 'Make Directory', tr: 'Dizin yap', origin: 'make + directory. Klasör oluştur.', example: 'mkdir -p a/b/c', tip: '-p üst dizinleri de oluşturur, hata vermez.' },
    { cmd: 'rmdir', cat: 'Dosya', en: 'Remove Directory', tr: 'Dizin kaldır', origin: 'remove + directory. Sadece boş dizini siler.', example: 'rmdir bos_klasor', tip: 'Dolu dizin için rm -r gerekir.' },
    { cmd: 'cp', cat: 'Dosya', en: 'Copy', tr: 'Kopyala', origin: 'copy’nin kısa hali.', example: 'cp a.txt b.txt', tip: 'Dizin için cp -r' },
    { cmd: 'mv', cat: 'Dosya', en: 'Move', tr: 'Taşı / yeniden adlandır', origin: 'move = taşımak. Aynı diskte yeniden adlandırma da mv ile yapılır.', example: 'mv eski.txt yeni.txt', tip: 'Windows’taki kes-yapıştır + rename birleşimi.' },
    { cmd: 'rm', cat: 'Dosya', en: 'Remove', tr: 'Kaldır / sil', origin: 'remove = kaldırmak. Geri dönüşüm kutusu yoktur.', example: 'rm dosya.txt', tip: 'rm -rf tehlikeli — yolu iki kez oku.' },
    { cmd: 'ln', cat: 'Dosya', en: 'Link', tr: 'Bağlantı oluştur', origin: 'link = bağ. Hard veya symbolic link yapar.', example: 'ln -s /etc/hosts ~/h', tip: '-s symlink (kısayol).' },
    { cmd: 'cat', cat: 'Metin', en: 'Concatenate', tr: 'Birleştir / göster', origin: 'concatenate = uç uca eklemek. Birden fazla dosyayı ardışık basar; tek dosyada “göster” gibi kullanılır.', example: 'cat /etc/hostname', tip: 'Uzun log için less/tail kullan.' },
    { cmd: 'tac', cat: 'Metin', en: 'Reverse of cat', tr: 'Ters cat', origin: 'cat’in tersi (ters yazılmış). Satırları sondan başa basar.', example: 'tac dosya.txt', tip: 'Log’un sonunu başa almak için.' },
    { cmd: 'less', cat: 'Metin', en: 'Less', tr: 'Sayfa sayfa oku', origin: '“less is more” — eski more komutundan daha yetenekli sayfalayıcı. less = daha az (kaynak kullanır / daha çevik).', example: 'less /var/log/syslog', tip: 'q çık, / ara, G sona git.' },
    { cmd: 'more', cat: 'Metin', en: 'More', tr: 'Daha fazla (sayfala)', origin: 'more = daha fazla. Klasik sayfalayıcı; less tercih edilir.', example: 'more dosya.txt', tip: 'Modern sistemlerde less kullanın.' },
    { cmd: 'head', cat: 'Metin', en: 'Head', tr: 'Baş / ilk satırlar', origin: 'head = kafa/baş. Dosyanın başlangıcını gösterir.', example: 'head -n 20 dosya', tip: 'Varsayılan 10 satır.' },
    { cmd: 'tail', cat: 'Metin', en: 'Tail', tr: 'Kuyruk / son satırlar', origin: 'tail = kuyruk. Dosyanın sonunu gösterir.', example: 'tail -f /var/log/auth.log', tip: '-f follow = canlı izle.' },
    { cmd: 'wc', cat: 'Metin', en: 'Word Count', tr: 'Kelime / satır say', origin: 'word count = kelime sayımı. Satır (-l), kelime (-w), byte (-c) sayar.', example: 'wc -l dosya.txt', tip: 'Log satır sayısı için wc -l.' },
    { cmd: 'grep', cat: 'Metin', en: 'Global Regular Expression Print', tr: 'Desen ara / süz', origin: 'ed/unix geleneği: g/re/p → global / regular expression / print. “Desene uyan satırları yazdır.”', example: 'grep -n error log.txt', tip: '-i duyarsız, -v tersine çevir, -R özyinelemeli.' },
    { cmd: 'egrep', cat: 'Metin', en: 'Extended Grep', tr: 'Gelişmiş grep', origin: 'extended grep. Artık grep -E tercih edilir.', example: 'grep -E "error|fail" log', tip: 'egrep = grep -E' },
    { cmd: 'sed', cat: 'Metin', en: 'Stream Editor', tr: 'Akış düzenleyici', origin: 'stream editor = akan metni satır satır düzenler (bul-değiştir).', example: "sed 's/eski/yeni/g' dosya", tip: 'Dosyayı yerinde: sed -i' },
    { cmd: 'awk', cat: 'Metin', en: 'Aho Weinberger Kernighan', tr: 'Sütun/metin işleme dili', origin: 'Yazarların soyadlarından: Aho, Weinberger, Kernighan. Alan (sütun) işlemek için doğdu.', example: "awk '{print $1}' dosya", tip: 'CSV/log sütunları için güçlü.' },
    { cmd: 'cut', cat: 'Metin', en: 'Cut', tr: 'Kes / alan al', origin: 'cut = kesmek. Satırdan sütun/karakter dilimler.', example: 'cut -d: -f1 /etc/passwd', tip: '-d ayırıcı, -f alan no.' },
    { cmd: 'sort', cat: 'Metin', en: 'Sort', tr: 'Sırala', origin: 'sort = sıralamak.', example: 'sort dosya.txt', tip: 'uniq ile sık birlikte: sort | uniq' },
    { cmd: 'uniq', cat: 'Metin', en: 'Unique', tr: 'Tekilleştir', origin: 'unique = benzersiz. Ardışık tekrarları birleştirir (önce sort gerekir).', example: 'sort a.txt | uniq -c', tip: '-c tekrar sayısını yazar.' },
    { cmd: 'diff', cat: 'Metin', en: 'Difference', tr: 'Fark', origin: 'difference = fark. İki dosyayı karşılaştırır.', example: 'diff a.conf b.conf', tip: 'Patch üretmek için -u' },
    { cmd: 'tee', cat: 'Metin', en: 'Tee (T-junction)', tr: 'Hem ekrana hem dosyaya', origin: 'T şeklindeki boru eklemesi (tee fitting): suyu iki yöne böler. Çıktıyı hem ekrana hem dosyaya yazar.', example: 'dmesg | tee boot.txt', tip: 'Log kaydederken çıktıyı da görmek için.' },

    // —— Yetki ——
    { cmd: 'chmod', cat: 'Yetki', en: 'Change Mode', tr: 'İzin kipini değiştir', origin: 'change + mode (dosya kip/izin modu).', example: 'chmod 755 script.sh', tip: 'r=4 w=2 x=1 → 755 = rwxr-xr-x' },
    { cmd: 'chown', cat: 'Yetki', en: 'Change Owner', tr: 'Sahibi değiştir', origin: 'change + owner (sahip).', example: 'sudo chown user:group dosya', tip: 'Genelde root gerekir.' },
    { cmd: 'chgrp', cat: 'Yetki', en: 'Change Group', tr: 'Grubu değiştir', origin: 'change + group.', example: 'chgrp developers proje/', tip: 'chown user:group ile birleşik de yapılır.' },
    { cmd: 'umask', cat: 'Yetki', en: 'User Mask', tr: 'Kullanıcı izin maskesi', origin: 'user file-creation mode mask. Yeni dosyalardan düşülecek izin bitleri.', example: 'umask 027', tip: '022 → dosyalar genelde 644.' },
    { cmd: 'sudo', cat: 'Yetki', en: 'Superuser Do', tr: 'Süper kullanıcı olarak yap', origin: 'superuser do = “yönetici olarak şunu yap”.', example: 'sudo apt update', tip: 'sudo -l ile yetkilerinizi görün.' },
    { cmd: 'su', cat: 'Yetki', en: 'Substitute User', tr: 'Kullanıcı değiştir', origin: 'substitute/switch user. Başka kullanıcıya (çoğunlukla root) geç.', example: 'su -', tip: 'Modern pratikte sudo tercih edilir.' },
    { cmd: 'passwd', cat: 'Yetki', en: 'Password', tr: 'Parola değiştir', origin: 'password’ün kısaltılmış komut adı.', example: 'passwd', tip: 'SUID root binary — /etc/shadow yazar.' },
    { cmd: 'id', cat: 'Yetki', en: 'Identity', tr: 'Kimlik bilgisi', origin: 'identity = kimlik. UID/GID/grupları basar.', example: 'id', tip: 'whoami’den daha detaylı.' },
    { cmd: 'whoami', cat: 'Yetki', en: 'Who Am I?', tr: 'Ben kimim?', origin: 'Düz İngilizce soru: who am I?', example: 'whoami', tip: 'sudo whoami → root olmalı.' },

    // —— Süreç ——
    { cmd: 'ps', cat: 'Süreç', en: 'Process Status', tr: 'Süreç durumu', origin: 'process status. Çalışan süreçlerin anlık listesi.', example: 'ps aux', tip: 'PID sütununu kill için not alın.' },
    { cmd: 'top', cat: 'Süreç', en: 'Table Of Processes', tr: 'Süreç tablosu (canlı)', origin: 'Süreçleri “üstte” canlı gösterir; table of processes çağrışımı.', example: 'top', tip: 'Çıkış: q. Modern alternatif: htop.' },
    { cmd: 'htop', cat: 'Süreç', en: 'Hisham’s Top', tr: 'Gelişmiş top', origin: 'Yazar Hisham’ın top benzeri aracı; renkli ve etkileşimli.', example: 'htop', tip: 'apt install htop' },
    { cmd: 'kill', cat: 'Süreç', en: 'Kill', tr: 'Süreçi sonlandır (sinyal gönder)', origin: 'kill = öldürmek — aslında sürece sinyal yollar; varsayılan SIGTERM.', example: 'kill -15 1234', tip: '-9 SIGKILL son çare.' },
    { cmd: 'killall', cat: 'Süreç', en: 'Kill All', tr: 'Ada göre tümünü sonlandır', origin: 'kill + all. İsme göre süreçleri sinyaler.', example: 'killall firefox', tip: 'Yanlış isimde tehlikeli olabilir.' },
    { cmd: 'pkill', cat: 'Süreç', en: 'Process Kill', tr: 'Desene göre sonlandır', origin: 'process kill. İsim desenine göre.', example: 'pkill -f "python app.py"', tip: 'pgrep ile önce bulun.' },
    { cmd: 'pgrep', cat: 'Süreç', en: 'Process Grep', tr: 'Süreç ara', origin: 'process + grep. PID bulur.', example: 'pgrep -a ssh', tip: 'kill öncesi teşhis.' },
    { cmd: 'nice', cat: 'Süreç', en: 'Nice', tr: 'Öncelik ayarla (nezaket)', origin: 'nice = nazik. CPU önceliğini “nezaket skoru” ile ayarlar; yüksek nice = daha az öncelikli.', example: 'nice -n 19 uzun_is', tip: 'Arka plan batch işleri için.' },
    { cmd: 'renice', cat: 'Süreç', en: 'Re-nice', tr: 'Önceliği yeniden ayarla', origin: 'running süreçte nice değerini değiştir.', example: 'sudo renice -n 5 -p 1234', tip: 'Prod’da gürültülü süreci sakinleştirir.' },
    { cmd: 'jobs', cat: 'Süreç', en: 'Jobs', tr: 'İşler (shell arka plan)', origin: 'job = iş. Shell’in arka plan işlerini listeler.', example: 'jobs', tip: 'Ctrl+Z, bg, fg ile birlikte.' },
    { cmd: 'bg', cat: 'Süreç', en: 'Background', tr: 'Arka plana al', origin: 'background = arka plan.', example: 'bg', tip: 'Duraklatılmış işi arka planda sürdürür.' },
    { cmd: 'fg', cat: 'Süreç', en: 'Foreground', tr: 'Öne getir', origin: 'foreground = ön plan.', example: 'fg', tip: 'Arka plan işini tekrar klavyeye bağlar.' },
    { cmd: 'nohup', cat: 'Süreç', en: 'No Hang Up', tr: 'Kopunca ölme', origin: 'no hang up — terminal kapanınca SIGHUP yeme.', example: 'nohup ./job.sh &', tip: 'Çıktı nohup.out’a gider.' },

    // —— Sistem & disk ——
    { cmd: 'uname', cat: 'Sistem', en: 'Unix Name', tr: 'Sistem / kernel adı', origin: 'Unix name. Kernel ve mimari bilgisi.', example: 'uname -a', tip: '-a hepsini basar.' },
    { cmd: 'hostname', cat: 'Sistem', en: 'Hostname', tr: 'Makine adı', origin: 'host name = ana bilgisayar adı.', example: 'hostname', tip: 'hostnamectl modern alternatif.' },
    { cmd: 'uptime', cat: 'Sistem', en: 'Uptime', tr: 'Açık kalma süresi', origin: 'up + time. Ne zamandır açık + load average.', example: 'uptime', tip: 'Load: 1/5/15 dk ortalaması.' },
    { cmd: 'date', cat: 'Sistem', en: 'Date', tr: 'Tarih / saat', origin: 'date = tarih.', example: 'date +%F', tip: 'Log damgası için ideal.' },
    { cmd: 'cal', cat: 'Sistem', en: 'Calendar', tr: 'Takvim', origin: 'calendar’ın kısası.', example: 'cal', tip: 'cal 2026 yıl takvimi.' },
    { cmd: 'df', cat: 'Disk', en: 'Disk Free', tr: 'Boş disk alanı', origin: 'disk free. Dosya sistemlerinin doluluk oranı.', example: 'df -h', tip: 'df -i inode doluluğu.' },
    { cmd: 'du', cat: 'Disk', en: 'Disk Usage', tr: 'Disk kullanımı', origin: 'disk usage. Dizinlerin kapladığı alan.', example: 'du -sh *', tip: 'df “partition”, du “klasör” sorar.' },
    { cmd: 'mount', cat: 'Disk', en: 'Mount', tr: 'Bağla / tak', origin: 'mount = dağa tırmanmak / (cihazı) bağlamak. Dosya sistemini ağaca ekler.', example: 'mount | column -t', tip: 'lsblk ile birlikte kullanın.' },
    { cmd: 'umount', cat: 'Disk', en: 'Unmount', tr: 'Ayır / çıkar', origin: 'un-mount. (Yazım umount — n yok, tarihî.)', example: 'sudo umount /mnt/usb', tip: 'Busy ise fuser/lsof ile kim kullanıyor bakın.' },
    { cmd: 'lsblk', cat: 'Disk', en: 'List Block devices', tr: 'Blok cihazları listele', origin: 'list block. Disk/partisyon ağacı.', example: 'lsblk -f', tip: 'UUID ve FS tipi için -f.' },
    { cmd: 'fdisk', cat: 'Disk', en: 'Format / Fixed Disk', tr: 'Disk bölümleme', origin: 'fixed disk üzerinde partition tablosu düzenler.', example: 'sudo fdisk -l', tip: 'Yıkıcı — lab dışında dikkat.' },
    { cmd: 'free', cat: 'Sistem', en: 'Free', tr: 'Boş bellek', origin: 'free memory. RAM/swap özeti.', example: 'free -h', tip: 'buff/cache “boşa gitmiş” değildir.' },
    { cmd: 'lsof', cat: 'Sistem', en: 'List Open Files', tr: 'Açık dosyaları listele', origin: 'list open files. Hangi süreç hangi dosya/portu tutuyor.', example: 'sudo lsof -i :80', tip: 'Disk dolu ama dosya silinmiş: lsof +L1' },
    { cmd: 'strace', cat: 'Sistem', en: 'System call Trace', tr: 'Sistem çağrısı izle', origin: 'sys(call) + trace. Sürecin kernel’e yaptığı çağrıları gösterir.', example: 'strace -e openat ls', tip: '“Permission denied” kök nedeni için.' },
    { cmd: 'dmesg', cat: 'Sistem', en: 'Display Message', tr: 'Çekirdek mesajları', origin: 'display message (kernel ring buffer). Donanım/driver/OOM izleri.', example: 'dmesg -T | tail', tip: 'Panic sonrası ilk bakılacak yerlerden.' },
    { cmd: 'journalctl', cat: 'Sistem', en: 'Journal Control', tr: 'Systemd günlüğü', origin: 'systemd journal’ını kontrol/oku.', example: 'journalctl -u ssh -n 50', tip: '-f canlı, -p err hata seviyesi.' },
    { cmd: 'systemctl', cat: 'Sistem', en: 'System Control', tr: 'Sistem / servis kontrolü', origin: 'systemd birimlerini yönetir: start/stop/status/enable…', example: 'systemctl status ssh', tip: 'enable = boot’ta aç.' },
    { cmd: 'service', cat: 'Sistem', en: 'Service', tr: 'Servis (eski sarmalayıcı)', origin: 'SysV uyumlu sarmalayıcı; çoğu yerde systemctl’e yönlendirir.', example: 'service ssh status', tip: 'Yeni alışkanlık: systemctl.' },

    // —— Arşiv & zaman ——
    { cmd: 'tar', cat: 'Arşiv', en: 'Tape Archive', tr: 'Bant arşivi / paketle', origin: 'Eski manyetik teyplere (tape) arşivlemek için doğdu; bugün .tar dosyası.', example: 'tar -czvf a.tar.gz klasor/', tip: 'c create, x extract, z gzip, f file, v verbose.' },
    { cmd: 'gzip', cat: 'Arşiv', en: 'GNU Zip', tr: 'GNU sıkıştırma', origin: 'GNU + zip. .gz üretir.', example: 'gzip -k dosya', tip: 'tar -z ile birlikte sık kullanılır.' },
    { cmd: 'gunzip', cat: 'Arşiv', en: 'GNU Unzip', tr: 'gz aç', origin: 'gzip’in tersi.', example: 'gunzip dosya.gz', tip: 'gzip -d ile aynı.' },
    { cmd: 'zip', cat: 'Arşiv', en: 'Zip', tr: 'Zip arşivi', origin: 'PKZIP formatı; Windows dünyasıyla uyumlu.', example: 'zip -r a.zip klasor', tip: 'unzip ile açılır.' },
    { cmd: 'unzip', cat: 'Arşiv', en: 'Unzip', tr: 'Zip aç', origin: 'un + zip.', example: 'unzip a.zip -d /tmp/out', tip: '-l sadece listele.' },
    { cmd: 'rsync', cat: 'Arşiv', en: 'Remote Sync', tr: 'Uzaktan eşitle', origin: 'remote + sync. Delta kopya; yedek ve deploy efsanesi.', example: 'rsync -avz src/ dest/', tip: '--delete hedefi kaynak gibi yapar — dikkat.' },
    { cmd: 'crontab', cat: 'Zaman', en: 'Cron Table', tr: 'Zamanlanmış görev tablosu', origin: 'chronos (Yunanca zaman) → cron. table = tablo.', example: 'crontab -e', tip: 'Format: dk saat gün ay hafta komut' },
    { cmd: 'at', cat: 'Zaman', en: 'At', tr: 'Şu saatte bir kez çalıştır', origin: 'at (o saatte). Tek seferlik zamanlama.', example: 'at now + 5 minutes', tip: 'Tekrarlayan işler için cron.' },

    // —— Ağ ——
    { cmd: 'ip', cat: 'Ağ', en: 'Internet Protocol toolkit', tr: 'IP / ağ yapılandırma', origin: 'iproute2 ailesi; ifconfig’in moderni.', example: 'ip addr', tip: 'ip route, ip link…' },
    { cmd: 'ifconfig', cat: 'Ağ', en: 'Interface Config', tr: 'Arayüz yapılandır (eski)', origin: 'interface + config. Birçok distroda deprecated.', example: 'ifconfig', tip: 'Yerine: ip addr' },
    { cmd: 'ss', cat: 'Ağ', en: 'Socket Statistics', tr: 'Soket istatistikleri', origin: 'socket stats. netstat’ın moderni.', example: 'ss -tulpn', tip: 'Dinleyen port teşhisi.' },
    { cmd: 'netstat', cat: 'Ağ', en: 'Network Statistics', tr: 'Ağ istatistikleri', origin: 'network + statistics. Eski ama hâlâ anılır.', example: 'netstat -tulpn', tip: 'Yerine ss tercih edin.' },
    { cmd: 'ping', cat: 'Ağ', en: 'Packet Internet Groper', tr: 'Ulaşılabilirlik yokla', origin: 'sonar “ping” sesinden; paket ile “orada mısın?”', example: 'ping -c 4 1.1.1.1', tip: 'DNS mi ağ mı ayırır.' },
    { cmd: 'traceroute', cat: 'Ağ', en: 'Trace Route', tr: 'Rotayı izle', origin: 'trace + route. Paketin geçtiği hop’ları gösterir.', example: 'traceroute example.com', tip: 'Windows: tracert' },
    { cmd: 'curl', cat: 'Ağ', en: 'Client URL', tr: 'URL istemcisi', origin: 'client for URLs. HTTP/FTP… veri çek/gönder.', example: 'curl -I https://example.com', tip: '-v debug, -O kaydet.' },
    { cmd: 'wget', cat: 'Ağ', en: 'Web Get', tr: 'Web’den indir', origin: 'world wide web + get. Dosya indirmeye odaklı.', example: 'wget https://example.com/file', tip: 'Recursive site aynası da yapabilir.' },
    { cmd: 'scp', cat: 'Ağ', en: 'Secure Copy', tr: 'Güvenli kopyala', origin: 'secure + cp. SSH üzerinden dosya kopyalar.', example: 'scp file user@host:/tmp/', tip: 'Çok dosya/dizin için rsync veya scp -r.' },
    { cmd: 'ssh', cat: 'Ağ', en: 'Secure Shell', tr: 'Güvenli kabuk', origin: 'secure shell. Şifreli uzak terminal.', example: 'ssh user@host', tip: 'Anahtar: ssh-keygen, ssh-copy-id' },
    { cmd: 'nc', cat: 'Ağ', en: 'Netcat', tr: 'Ağ kedisi / İsviçre çakısı', origin: 'net + cat. TCP/UDP ile oku-yaz; “ağın cat’i”.', example: 'nc -zv host 22', tip: 'Port yoklama ve basit transfer.' },
    { cmd: 'dig', cat: 'Ağ', en: 'Domain Information Groper', tr: 'DNS sorgu aracı', origin: 'domain information groper — DNS kayıtlarını yoklar.', example: 'dig example.com +short', tip: 'nslookup’a göre daha net.' },
    { cmd: 'nslookup', cat: 'Ağ', en: 'Name Server Lookup', tr: 'Ad sunucusu sorgula', origin: 'name server + lookup.', example: 'nslookup example.com', tip: 'Script için dig tercih edilir.' },
    { cmd: 'nmap', cat: 'Güvenlik', en: 'Network Mapper', tr: 'Ağ haritalayıcı', origin: 'network mapper. Port/servis keşfi.', example: 'nmap -sV 127.0.0.1', tip: 'Yalnızca yetkili hedeflerde.' },
    { cmd: 'tcpdump', cat: 'Güvenlik', en: 'TCP Dump', tr: 'TCP/paket dökümü', origin: 'TCP (ve diğer) paketleri “dök” (dump).', example: 'sudo tcpdump -i any port 80', tip: 'Wireshark ile .pcap analiz.' },

    // —— Editör & geliştirme ——
    { cmd: 'nano', cat: 'Editör', en: 'Nano’s ANOther editor', tr: 'Basit metin editörü', origin: 'Pico’nun özgür yeniden yazımı; “another editor” kelime oyunu.', example: 'nano dosya.txt', tip: 'Ctrl+O kaydet, Ctrl+X çık.' },
    { cmd: 'vi', cat: 'Editör', en: 'Visual Interface', tr: 'Görsel arayüzlü editör', origin: 'ex satır editörünün “visual” modu → vi.', example: 'vi dosya', tip: 'Esc :q! panik çıkışı.' },
    { cmd: 'vim', cat: 'Editör', en: 'Vi IMproved', tr: 'Geliştirilmiş vi', origin: 'vi improved.', example: 'vim dosya', tip: 'vimtutor öğrenme için.' },
    { cmd: 'emacs', cat: 'Editör', en: 'Editor MACroS', tr: 'Makrolu editör', origin: 'editor macros. Vi ile efsane rekabet.', example: 'emacs dosya', tip: 'Ctrl+X Ctrl+C çıkış.' },
    { cmd: 'gcc', cat: 'Geliştirme', en: 'GNU Compiler Collection', tr: 'GNU derleyici koleksiyonu', origin: 'Önce GNU C Compiler’dı; sonra çok dilli collection oldu.', example: 'gcc -o hi hi.c', tip: '-Wall uyarıları açın.' },
    { cmd: 'make', cat: 'Geliştirme', en: 'Make', tr: 'Derleme otomasyonu', origin: 'make = yapmak. Makefile kurallarına göre hedef üretir.', example: 'make && make install', tip: 'Bağımlılık ve yeniden derleme yönetir.' },
    { cmd: 'python3', cat: 'Geliştirme', en: 'Python 3', tr: 'Python 3 yorumlayıcı', origin: 'Monty Python’dan esinlenen dil; sürüm 3.', example: 'python3 script.py', tip: 'Shebang: #!/usr/bin/env python3' },
    { cmd: 'perl', cat: 'Geliştirme', en: 'Practical Extraction and Report Language', tr: 'Metin işleme dili', origin: 'Practical Extraction and Report Language (veya Pathologically Eclectic Rubbish Lister — şaka açılımı).', example: 'perl -v', tip: 'Klasik admin one-liner’ları.' },

    // —— Paket & yardım ——
    { cmd: 'apt', cat: 'Paket', en: 'Advanced Package Tool', tr: 'Gelişmiş paket aracı', origin: 'Debian/Ubuntu paket yöneticisi arayüzü.', example: 'sudo apt update && sudo apt install curl', tip: 'update katalog, upgrade paketler.' },
    { cmd: 'dpkg', cat: 'Paket', en: 'Debian Package', tr: 'Debian paket aracı', origin: 'Debian .deb paketlerini düşük seviyede yönetir.', example: 'dpkg -l | grep curl', tip: 'Bağımlılık için apt üst katmandır.' },
    { cmd: 'yum', cat: 'Paket', en: 'Yellowdog Updater Modified', tr: 'RHEL/CentOS paket (eski)', origin: 'Yellow Dog Linux’tan gelen isim.', example: 'yum install wget', tip: 'Yenisi: dnf' },
    { cmd: 'dnf', cat: 'Paket', en: 'Dandified YUM', tr: 'YUM’un moderni', origin: 'dandified yum — Fedora/RHEL yeni nesil.', example: 'sudo dnf install htop', tip: 'RHEL 8+ varsayılan.' },
    { cmd: 'man', cat: 'Yardım', en: 'Manual', tr: 'Kılavuz sayfası', origin: 'manual pages. Unix belgelendirme geleneği.', example: 'man ls', tip: 'q çık, / kelime ara.' },
    { cmd: 'info', cat: 'Yardım', en: 'Info', tr: 'Info belgesi', origin: 'GNU info hiper metin kılavuzları.', example: 'info coreutils', tip: 'Bazı GNU araçlarında man’den zengin.' },
    { cmd: 'whatis', cat: 'Yardım', en: 'What Is', tr: 'Bu nedir? (tek satır)', origin: 'what is — man’in kısa özeti.', example: 'whatis chmod', tip: 'apropos ile konu ara.' },
    { cmd: 'apropos', cat: 'Yardım', en: 'Apropos', tr: 'Konuyla ilgili komutlar', origin: 'Fransızca/Latince “ile ilgili”. man veritabanında anahtar kelime arar.', example: 'apropos directory', tip: 'Ne komut olduğunu bilmiyorsanız.' },
    { cmd: 'which', cat: 'Yardım', en: 'Which', tr: 'Hangisi? (yol)', origin: 'which = hangisi. PATH’te komutun tam yolunu gösterir.', example: 'which python3', tip: 'type -a daha kapsamlı olabilir.' },
    { cmd: 'whereis', cat: 'Yardım', en: 'Where Is', tr: 'Nerede? (binary/man/source)', origin: 'where is — binary, kaynak, man konumları.', example: 'whereis ls', tip: 'which’ten geniş.' },
    { cmd: 'type', cat: 'Yardım', en: 'Type', tr: 'Tür / kaynak', origin: 'Komut alias mı, builtin mı, dosya mı?', example: 'type ls', tip: 'Shell builtin teşhisi.' },
    { cmd: 'help', cat: 'Yardım', en: 'Help', tr: 'Yardım (builtin)', origin: 'Bash yerleşik komutları için yardım.', example: 'help cd', tip: 'cd için man değil help.' },
    { cmd: 'history', cat: 'Yardım', en: 'History', tr: 'Geçmiş', origin: 'history = tarihçe. Yazılan komutlar.', example: 'history | grep ssh', tip: 'Ctrl+R etkileşimli arama.' },
    { cmd: 'clear', cat: 'Yardım', en: 'Clear', tr: 'Ekranı temizle', origin: 'clear = temizle.', example: 'clear', tip: 'Ctrl+L çoğu shell’de aynı.' },
    { cmd: 'echo', cat: 'Yardım', en: 'Echo', tr: 'Yankı / yazdır', origin: 'echo = yankı. Argümanları ekrana basar.', example: 'echo $HOME', tip: 'Script debug ve değişken kontrol.' },
    { cmd: 'printf', cat: 'Yardım', en: 'Print Formatted', tr: 'Biçimli yazdır', origin: 'C’deki printf gibi biçimli çıktı.', example: 'printf "%s\\n" merhaba', tip: 'echo’dan daha öngörülebilir.' },
    { cmd: 'basename', cat: 'Dosya', en: 'Base Name', tr: 'Taban ad', origin: 'yoldan dosya adını ayıklar.', example: 'basename /a/b/c.txt', tip: 'Script’te dosya adı için.' },
    { cmd: 'dirname', cat: 'Dosya', en: 'Directory Name', tr: 'Dizin adı', origin: 'yoldan dizin kısmını alır.', example: 'dirname /a/b/c.txt', tip: 'basename’in eşi.' },
    { cmd: 'realpath', cat: 'Dosya', en: 'Real Path', tr: 'Gerçek yol', origin: 'symlink’leri çözerek mutlak yolu basar.', example: 'realpath ./x', tip: 'Script’te belirsiz yolları netleştirir.' },
    { cmd: 'file', cat: 'Dosya', en: 'File', tr: 'Dosya türünü söyle', origin: 'İçeriğe bakarak tür tahmin eder (uzantıya güvenmez).', example: 'file /bin/ls', tip: 'ELF mi script mi ayırır.' },
    { cmd: 'stat', cat: 'Dosya', en: 'Status', tr: 'Inode / durum bilgisi', origin: 'file status — boyut, inode, zamanlar, izinler.', example: 'stat dosya', tip: 'ls -l’den daha teknik.' },
    { cmd: 'alias', cat: 'Shell', en: 'Alias', tr: 'Takma ad', origin: 'alias = takma ad. Kısa komut kısayolu.', example: "alias ll='ls -la'", tip: '~/.bashrc içine yazın.' },
    { cmd: 'export', cat: 'Shell', en: 'Export', tr: 'Dışa aktar (ortam değişkeni)', origin: 'Değişkeni alt süreçlere miras bırak.', example: 'export PATH="$PATH:/opt/bin"', tip: 'Kalıcılık için bashrc/profile.' },
    { cmd: 'env', cat: 'Shell', en: 'Environment', tr: 'Ortam', origin: 'environment variables listeler / ile komut çalıştırır.', example: 'env | grep PATH', tip: 'Shebang: #!/usr/bin/env bash' },
    { cmd: 'xargs', cat: 'Shell', en: 'X Arguments', tr: 'Standart girdiyi argümana çevir', origin: 'execute with arguments. Pipe’dan gelen satırları komut argümanı yapar.', example: 'find . -name "*.log" | xargs rm', tip: 'Boşluklu adlarda -0 / find -print0.', aliases: ['argüman yap', 'pipe argüman'] },

    // —— Güç / oturum ——
    { cmd: 'reboot', cat: 'Sistem', en: 'Reboot', tr: 'Yeniden başlat', origin: 're- (yeniden) + boot (açılış/önyükleme). Sistemi kapatıp tekrar açar.', example: 'sudo reboot', tip: 'Eşdeğer: sudo systemctl reboot · acil: sudo reboot -f', aliases: ['yeniden başlat', 'yeniden başlatma', 'yenidenbaslat', 'restart', 'sistemi yeniden başlat', 'makineyi yeniden başlat', 'bilgisayarı yeniden başlat', 'reboot et', 'sistemi restart et', 'cold boot', 'warm boot'] },
    { cmd: 'shutdown', cat: 'Sistem', en: 'Shut Down', tr: 'Kapat / kapanışı zamanla', origin: 'shut down = kapatmak. Güvenli kapanış veya zamanlanmış reboot.', example: 'sudo shutdown -h now', tip: 'shutdown -r now = yeniden başlat · -c iptal', aliases: ['kapat', 'kapatma', 'sistemi kapat', 'bilgisayarı kapat', 'shutdown', 'power off zamanla', 'kaç dakika sonra kapat'] },
    { cmd: 'poweroff', cat: 'Sistem', en: 'Power Off', tr: 'Gücü kes / kapat', origin: 'power off = elektriği kes. Makineyi kapatır.', example: 'sudo poweroff', tip: 'halt / poweroff / shutdown -h benzer iş', aliases: ['gücü kapat', 'elektriği kes', 'power off', 'pc kapat', 'pcyi kapat'] },
    { cmd: 'halt', cat: 'Sistem', en: 'Halt', tr: 'Durdur', origin: 'halt = durdurmak. CPU’yu durdurur; çoğu sistemde poweroff’a yönlenir.', example: 'sudo halt', tip: 'Modern distrolarda poweroff ile yakın', aliases: ['durdur', 'sistemi durdur', 'halt et'] },
    { cmd: 'systemctl reboot', cat: 'Sistem', en: 'Systemctl Reboot', tr: 'Systemd ile yeniden başlat', origin: 'systemctl + reboot birimi/hedefi.', example: 'sudo systemctl reboot', tip: 'systemd’li sistemlerde tercih edilen yol', aliases: ['yeniden başlat', 'yeniden başlatma', 'systemd reboot', 'servisleri düzgün kapatıp aç'] },
    { cmd: 'systemctl poweroff', cat: 'Sistem', en: 'Systemctl Poweroff', tr: 'Systemd ile kapat', origin: 'systemctl + poweroff.', example: 'sudo systemctl poweroff', tip: 'Grafik “Shut Down” düğmesinin CLI hali', aliases: ['kapat', 'sistemi kapat', 'systemd kapat'] },
];

/* Türkçe / günlük dil → arama eşlemeleri (komut adları ve serbest ifadeler) */
window.SEARCH_PHRASES = {
    'yeniden başlat': ['reboot', 'systemctl reboot', 'shutdown'],
    'yeniden başlatma': ['reboot', 'systemctl reboot', 'shutdown'],
    'yenidenbaslat': ['reboot'],
    'restart': ['reboot', 'systemctl reboot'],
    'sistemi yeniden': ['reboot'],
    'makineyi yeniden': ['reboot'],
    'bilgisayarı yeniden': ['reboot'],
    'kapat': ['shutdown', 'poweroff', 'halt', 'systemctl poweroff'],
    'kapatma': ['shutdown', 'poweroff'],
    'sistemi kapat': ['shutdown', 'poweroff', 'systemctl poweroff'],
    'bilgisayarı kapat': ['shutdown', 'poweroff'],
    'gücü kapat': ['poweroff'],
    'power off': ['poweroff'],
    'listele': ['ls', 'll'],
    'dosya listele': ['ls'],
    'klasör değiştir': ['cd'],
    'dizin değiştir': ['cd'],
    'nereye': ['pwd'],
    'neredeyim': ['pwd'],
    'bul': ['find', 'grep', 'locate'],
    'ara': ['grep', 'find', 'apropos'],
    'metin ara': ['grep'],
    'içinde ara': ['grep'],
    'kopyala': ['cp', 'scp', 'rsync'],
    'kopyalamak': ['cp'],
    'taşı': ['mv'],
    'taşımak': ['mv'],
    'yeniden adlandır': ['mv'],
    'isim değiştir': ['mv'],
    'sil': ['rm'],
    'silmek': ['rm'],
    'kaldır': ['rm', 'apt'],
    'oluştur': ['touch', 'mkdir'],
    'klasör oluştur': ['mkdir'],
    'dizin oluştur': ['mkdir'],
    'izin': ['chmod'],
    'izin ver': ['chmod'],
    'izin değiştir': ['chmod'],
    'yetki': ['chmod', 'sudo', 'chown'],
    'sahip değiştir': ['chown'],
    'süreç': ['ps', 'top', 'htop'],
    'process': ['ps', 'top'],
    'çalışan program': ['ps', 'top'],
    'öldür': ['kill', 'killall', 'pkill'],
    'sonlandır': ['kill'],
    'zorla kapat süreç': ['kill'],
    'bellek': ['free'],
    'ram': ['free'],
    'disk dolu': ['df', 'du'],
    'disk alanı': ['df', 'du'],
    'boş alan': ['df'],
    'ne kadar yer': ['du', 'df'],
    'paket kur': ['apt', 'dnf', 'yum'],
    'program kur': ['apt'],
    'güncelle': ['apt'],
    'servis': ['systemctl', 'service'],
    'servisi başlat': ['systemctl'],
    'servisi durdur': ['systemctl'],
    'log': ['journalctl', 'tail', 'less'],
    'günlük': ['journalctl'],
    'log bak': ['journalctl', 'tail'],
    'bağlan': ['ssh'],
    'uzak bağlantı': ['ssh'],
    'indir': ['wget', 'curl'],
    'dosya indir': ['wget', 'curl'],
    'ağ testi': ['ping'],
    'ulaşabiliyor mu': ['ping'],
    'port açık mı': ['ss', 'nmap', 'nc'],
    'hangi port': ['ss', 'netstat'],
    'sıkıştır': ['tar', 'gzip', 'zip'],
    'arşivle': ['tar'],
    'aç arşiv': ['tar', 'unzip', 'gunzip'],
    'yedek': ['tar', 'rsync', 'crontab'],
    'zamanla': ['crontab', 'at'],
    'otomatik çalıştır': ['crontab'],
    'zamanlanmış görev': ['crontab'],
    'yardım': ['man', 'help', 'apropos'],
    'kılavuz': ['man'],
    'ekran temizle': ['clear'],
    'temizle': ['clear'],
    'kimim': ['whoami', 'id'],
    'kullanıcı kim': ['whoami', 'id'],
    'şifre değiştir': ['passwd'],
    'parola': ['passwd'],
    'düzenle': ['nano', 'vim', 'vi'],
    'dosya düzenle': ['nano', 'vim'],
    'yazı yaz': ['nano'],
    'firewall': ['iptables', 'nft'],
    'güvenlik duvarı': ['iptables'],
    'dns bak': ['dig', 'nslookup'],
    'ip adresim': ['ip'],
    'ip nedir': ['ip'],
    'rota': ['ip', 'traceroute'],
    'yol izle': ['traceroute'],
    'kullanıcı değiştir': ['su', 'sudo'],
    'yönetici olarak': ['sudo'],
    'root ol': ['sudo', 'su'],
};

window.CMD_CATEGORIES = ['Tümü', ...Array.from(new Set(window.COMMANDS.map(c => c.cat)))];

/** Komutlara aliases alanını SEARCH_PHRASES’ten de zenginleştir */
(function enrichAliases() {
    const byCmd = {};
    Object.entries(window.SEARCH_PHRASES || {}).forEach(([phrase, cmds]) => {
        cmds.forEach(cmd => {
            if (!byCmd[cmd]) byCmd[cmd] = [];
            byCmd[cmd].push(phrase);
        });
    });
    (window.COMMANDS || []).forEach(c => {
        const extra = byCmd[c.cmd] || [];
        c.aliases = Array.from(new Set([...(c.aliases || []), ...extra, c.tr]));
    });
})();
