/* Mülakat antrenmanı — role göre soru bankası */
window.INTERVIEW_EXTRA = [

/* —— Sıfırdan / ortak temel —— */
{ id: 'ix-s0', tracks: ['sifirdan', 'devops', 'redhat', 'soc', 'backend'], level: 'baslangic', tag: 'Temel',
  q: 'Linux nedir? Kernel ile işletim sistemi farkını bir cümlede ayır.',
  a: 'Linux dar anlamda çekirdektir. İşletim sistemi = kernel + userspace (GNU araçları, init, paket yöneticisi, servisler). Dağıtımlar bu paketi farklı felsefelerle sunar.' },
{ id: 'ix-s1', tracks: ['sifirdan', 'devops', 'redhat', 'backend'], level: 'baslangic', tag: 'Temel',
  q: 'pwd, cd, ls ne işe yarar? Bir junior’a nasıl anlatırsın?',
  a: 'pwd: neredeyim. cd: dizine geç. ls: içeriği listele. Navigasyon üçlüsü; her teşhis “önce nerede olduğumu bil” ile başlar.' },
{ id: 'ix-s2', tracks: ['sifirdan', 'redhat', 'soc'], level: 'orta', tag: 'Yetki',
  q: 'root ile normal kullanıcı farkı nedir? Neden günlük işte root kullanılmaz?',
  a: 'root (UID 0) sınırsız yetki. Hata ve malware etkisi maksimize olur. Least privilege: normal kullanıcı + gerektiğinde sudo.' },
{ id: 'ix-s3', tracks: ['sifirdan', 'devops', 'redhat'], level: 'orta', tag: 'İzin',
  q: 'chmod 755 ne demek? 644 ile farkı?',
  a: '755: rwxr-xr-x — sahip tam, diğerleri oku+çalıştır (script/dizin). 644: rw-r--r-- — dosya için tipik; çalıştırma biti yok.' },
{ id: 'ix-s4', tracks: ['sifirdan', 'soc', 'blueteam'], level: 'ileri', tag: 'Yetki',
  q: 'SUID bit ne işe yarar? Güvenlik riski nedir?',
  a: 'Dosya sahibi yetkisiyle çalıştırır (örn. passwd). Yanlış SUID binary privilege escalation vektörüdür; envanter ve minimal yüzey şart.' },

/* —— DevOps —— */
{ id: 'ix-d0', tracks: ['devops', 'sre', 'cloud', 'backend'], level: 'baslangic', tag: 'Konteyner',
  q: 'Konteyner ile VM farkı nedir?',
  a: 'VM kendi kernel’ini taşır (hipervizör). Konteyner host kernel’ini paylaşır; namespace + cgroup ile izole proses. Daha hafif, daha yoğun; izolasyon modeli farklıdır.' },
{ id: 'ix-d1', tracks: ['devops', 'sre', 'cloud'], level: 'orta', tag: 'Docker',
  q: 'Dockerfile’da multi-stage build neden kullanılır?',
  a: 'Derleme araçlarını runtime imajından ayırır: daha küçük imaj, daha az CVE yüzeyi, daha hızlı pull. Secret ve build cache de daha temiz yönetilir.' },
{ id: 'ix-d2', tracks: ['devops', 'sre'], level: 'orta', tag: 'CI/CD',
  q: 'CI ile CD farkı nedir? Continuous Delivery vs Deployment?',
  a: 'CI: her değişikliği entegre/test et. CD (Delivery): paketi ortamlara taşı, kapı olabilir. Continuous Deployment: green build otomatik prod’a gider.' },
{ id: 'ix-d3', tracks: ['devops', 'sre', 'cloud'], level: 'ileri', tag: 'K8s',
  q: 'Kubernetes’te Deployment, Pod, Service ilişkisi?',
  a: 'Pod en küçük çalıştırma birimi. Deployment replica ve rolling update yönetir. Service, değişen Pod IP’lerine sabit erişim (ClusterIP/NodePort/LB) sağlar.' },
{ id: 'ix-d4', tracks: ['devops', 'sre'], level: 'ileri', tag: 'K8s',
  q: 'CrashLoopBackOff gördün. İlk 4 adımın?',
  a: '1) kubectl describe (Events) 2) logs / previous 3) config/secret/mount 4) resources/OOM/probe. Hipotez kur, rastgele restart etme.' },
{ id: 'ix-d5', tracks: ['devops', 'cloud'], level: 'orta', tag: 'IaC',
  q: 'Terraform state neden kritik? Remote state şart mı?',
  a: 'State kaynak kimlik haritasıdır. Kaybolursa duplicate/silme riski. Ekip ve CI için remote state + locking zorunlu sayılır.' },
{ id: 'ix-d6', tracks: ['devops', 'sre', 'backend'], level: 'orta', tag: 'Git',
  q: 'Trunk-based development nedir? Uzun lived branch neden sorun?',
  a: 'Kısa ömürlü branch + sık merge ana hatta. Uzun branch merge cehennemi, drift ve geç entegrasyon üretir; feature flag ile risk yönetilir.' },
{ id: 'ix-d7', tracks: ['devops', 'sre', 'cloud'], level: 'ileri', tag: 'Supply chain',
  q: 'CI pipeline’da secret nasıl taşınır / taşınmaz?',
  a: 'Platform secret + maskeli log + OIDC/kısa ömürlü credential. YAML’a gömme, fork PR’a secret verme, echo ile debug yok. Image’a bake etme.' },

/* —— SRE —— */
{ id: 'ix-r0', tracks: ['sre', 'devops'], level: 'orta', tag: 'SLO',
  q: 'SLI, SLO, error budget nedir?',
  a: 'SLI ölçülen sinyal (örn. başarı oranı). SLO hedef. Error budget ihlalde hız vs güvenilirlik trade-off’unu yönetir; feature freeze tetikleyebilir.' },
{ id: 'ix-r1', tracks: ['sre', 'soc', 'blueteam'], level: 'orta', tag: 'Alert',
  q: 'İyi bir alert’in özellikleri nelerdir?',
  a: 'Actionable, nadir, anlaşılır, runbook’lu, ownership net. Symptom bazlı tercih (kullanıcı etkisi); gürültülü cause alert’ler yorgunluk yaratır.' },
{ id: 'ix-r2', tracks: ['sre', 'redhat', 'devops'], level: 'ileri', tag: 'Kriz',
  q: 'Prod’da yanlış deploy. İlk 3 aksiyon?',
  a: '1) Etkiyi ölç + iletişimi aç 2) Trafiği kaydır veya rollback 3) Kanıt topla (log, metrics, change id) sonra RCA.' },
{ id: 'ix-r3', tracks: ['sre', 'devops'], level: 'ileri', tag: 'GitOps',
  q: 'GitOps ne kazandırır? Hotfix borcu nasıl yönetilir?',
  a: 'Desired state Git’te; agent reconcile eder, drift görünür. Hotfix hemen Git’e geri yazılır; aksi halde snowflake doğar.' },
{ id: 'ix-r4', tracks: ['sre', 'cloud'], level: 'ileri', tag: 'Kapasite',
  q: 'Latency mi saturation mı bakarsın? Ne zaman hangisi?',
  a: 'Kullanıcı etkisi: latency/error. Kaynak: utilization/saturation. İkisini bağlayan hipotez (USE/RED) doğru katmanı seçtirir.' },

/* —— Red Hat / Sysadmin —— */
{ id: 'ix-h0', tracks: ['redhat', 'sifirdan', 'backend'], level: 'baslangic', tag: 'Paket',
  q: 'dnf/yum ile apt farkını bilmek neden önemli?',
  a: 'Aynı iş (paket kur/güncelle) farklı distro araçlarıyla. Kavram ortaktır; komut ve repo modeli değişir. RHEL dünyasında dnf + subscription/repo bilinci gerekir.' },
{ id: 'ix-h1', tracks: ['redhat', 'devops', 'sre'], level: 'orta', tag: 'systemd',
  q: 'systemctl enable ile start farkı? unit dosyası nerede?',
  a: 'start: şimdi çalıştır. enable: boot’ta aç. Unit’ler /usr/lib/systemd/system ve /etc/systemd/system (override). daemon-reload unutulmaz.' },
{ id: 'ix-h2', tracks: ['redhat', 'blueteam'], level: 'ileri', tag: 'SELinux',
  q: 'SELinux Enforcing’de access denied. Disabled yapmak neden yanlış refleks?',
  a: 'MAC katmanını öldürürsün. Doğrusu: ausearch/audit2why ile nedeni bul, context düzelt veya kural ekle; learn/permissive geçici teşhis için.' },
{ id: 'ix-h3', tracks: ['redhat', 'sre'], level: 'orta', tag: 'LVM',
  q: 'Disk doldu, LVM var. Büyütme sırası?',
  a: 'Hipervizör/cloud volume büyüt → OS’ta lsblk → pvresize/vgextend → lvextend → filesystem grow (resize2fs/xfs_growfs). Önce df -h ve df -i.' },
{ id: 'ix-h4', tracks: ['redhat', 'devops'], level: 'orta', tag: 'Ansible',
  q: 'Ansible idempotent ne demek? Agentless ne kazandırır?',
  a: 'Aynı playbook tekrar çalışınca istenen state’e yaklaşır, bozmadan. Agentless SSH ile yönetim; agent bakımı azalır, inventory ve yetki modeli kritikleşir.' },
{ id: 'ix-h5', tracks: ['redhat', 'soc', 'blueteam'], level: 'orta', tag: 'SSH',
  q: 'sshd sertleştirmede minimum 4 madde?',
  a: 'PermitRootLogin no, PasswordAuthentication no, PubkeyAuthentication yes, AllowUsers/grup. sshd -t + console hazırlığı; kendini kilitleme riski.' },

/* —— SOC —— */
{ id: 'ix-c0', tracks: ['soc', 'blueteam', 'redteam'], level: 'baslangic', tag: 'Tespit',
  q: 'SOC’ta triage nedir? False positive ile nasıl başa çıkarsın?',
  a: 'Alert’i önceliklendirip doğrulama. FP’de kuralı körleme kapatma; tuning, suppress ile context, detection as code. Kanıt ve timeline tut.' },
{ id: 'ix-c1', tracks: ['soc', 'blueteam'], level: 'orta', tag: 'Log',
  q: 'Linux’ta şüpheli login için nereye bakarsın?',
  a: 'auth.log/secure, journalctl, last/lastb, ausearch USER_LOGIN, sshd config, authorized_keys değişiklikleri, yeni cron/systemd timer.' },
{ id: 'ix-c2', tracks: ['soc', 'redteam', 'blueteam'], level: 'orta', tag: 'Ağ',
  q: 'Connection refused vs timed out — güvenlik açısından ne anlatır?',
  a: 'Refused: hedefte dinleyen yok (RST). Timed out: DROP/filtre veya yol yok. Firewall politikası ve lateral movement teşhisinde kritik ayrım.' },
{ id: 'ix-c3', tracks: ['soc', 'blueteam'], level: 'ileri', tag: 'IR',
  q: 'Host compromise şüphesi. İlk izolasyon adımların? Kanıtı nasıl bozmazsın?',
  a: 'Ağ kısıtı / quarantine, credential revoke, volatile memory varsa önce topla, sonra disk imajı. Saat senkronu, chain of custody, rebuild kararı ile “temizle-umut et” ayrımı.' },
{ id: 'ix-c4', tracks: ['soc', 'sre'], level: 'orta', tag: 'SIEM',
  q: 'Use case yazarken neyi ölçersin?',
  a: 'Teknik sinyal + iş etkisi + false positive maliyeti + veri kaynağı kalitesi. Alert = soru; use case = hipotez + sorgu + aksiyon.' },

/* —— Red Team —— */
{ id: 'ix-t0', tracks: ['redteam', 'soc'], level: 'baslangic', tag: 'Etik',
  q: 'Pentest’e başlamadan önce ne şart?',
  a: 'Yazılı kapsam (RoE), izinli hedefler, zaman penceresi, iletişim, veri işleme kuralları. İzinsiz tarama suçtur.' },
{ id: 'ix-t1', tracks: ['redteam', 'soc', 'blueteam'], level: 'orta', tag: 'Recon',
  q: 'Nmap -sS ile -sT farkı? filtered ne demek?',
  a: 'SYN half-open (genelde root), Connect full handshake. filtered: yanıt yok veya ICMP prohibit — kapalı demek değil, ACL/firewall olabilir.' },
{ id: 'ix-t2', tracks: ['redteam'], level: 'ileri', tag: 'AD',
  q: 'Kerberoasting kısaca nedir? Savunma tarafı ne yapar?',
  a: 'SPN’li hesap ticket’larını offline kırmaya çalışma. Savunma: güçlü servis hesabı parolaları / gMSA, detection (anormal TGS), tiering.' },
{ id: 'ix-t3', tracks: ['redteam', 'blueteam'], level: 'ileri', tag: 'Privesc',
  q: 'Linux privesc’te ilk baktığın 5 yer?',
  a: 'SUID/SGID, sudo -l, cron/timer, yazılabilir servis dosyaları, capability, kernel/CTF similar misconfig, container escape sinyalleri.' },
{ id: 'ix-t4', tracks: ['redteam', 'soc'], level: 'orta', tag: 'Web',
  q: 'SQLi bulgusunu nasıl doğrular ve abartmadan raporlarsın?',
  a: 'Minimal PoC, etki (oku/yaz/RCE?), veri sınıfı, CVSS+iş etkisi, yeniden üretim adımları. Otomatik araca kör güvenme; Burp ile manuel doğrula.' },

/* —— Blue Team —— */
{ id: 'ix-b0', tracks: ['blueteam', 'soc', 'redhat'], level: 'orta', tag: 'Hardening',
  q: 'Attack surface envanteri nasıl çıkarılır?',
  a: 'ss -tulnp, çalışan servisler, paket listesi, kullanıcılar, açık share’ler, container portları. Gereksizi kapat; minimal imaj.' },
{ id: 'ix-b1', tracks: ['blueteam', 'devops', 'cloud'], level: 'orta', tag: 'TLS',
  q: 'Sertifika yenileme P1 olmasın diye ne yaparsın?',
  a: 'ACME otomasyon, 30/14/7 gün alert, staging dry-run, reload otomasyonu, tek kişiye bağlı süreç yok, takvim drift kontrolü.' },
{ id: 'ix-b2', tracks: ['blueteam', 'devops'], level: 'ileri', tag: 'K8s güvenlik',
  q: 'Pod Security / NetworkPolicy neden default allow tehlikelidir?',
  a: 'Lateral movement ve escape sonrası yayılım kolaylaşır. Default deny + gerekli allow, non-root, drop caps, readOnlyRootFilesystem, image allow-list.' },
{ id: 'ix-b3', tracks: ['blueteam', 'soc'], level: 'ileri', tag: 'Defense',
  q: 'Defense in depth’i bir örnekle anlat.',
  a: 'Edge SG + host firewall + SSH key-only + SELinux + app TLS + audit/Falco + yedek. Tek kontrol yetmez; katmanlar birbirini telafi eder.' },

/* —— Cloud —— */
{ id: 'ix-cl0', tracks: ['cloud', 'devops', 'sre'], level: 'orta', tag: 'IAM',
  q: 'Uzun ömürlü access key yerine ne tercih edersin?',
  a: 'Instance/workload identity, OIDC federation, kısa ömürlü STS. Key rotate ve least privilege; CI’da static key anti-pattern.' },
{ id: 'ix-cl1', tracks: ['cloud', 'blueteam', 'soc'], level: 'ileri', tag: 'Metadata',
  q: 'Cloud instance metadata SSRF riski nedir?',
  a: 'Uygulama SSRF ile 169.254.169.254’ten credential çalınabilir. IMDSv2/hop limit, SG, egress kontrol, app URL allow-list.' },
{ id: 'ix-cl2', tracks: ['cloud', 'devops'], level: 'orta', tag: 'Ağ',
  q: 'Security Group ile host firewall ilişkisi?',
  a: 'SG hypervisor/edge filtre; host nftables/ufw ikinci katman. İkisini de varsayma; debug’da her iki katmana bak.' },
{ id: 'ix-cl3', tracks: ['cloud', 'sre'], level: 'orta', tag: 'Disk',
  q: 'Cloud disk büyüttün ama df değişmedi. Neden?',
  a: 'Volume hypervisor’da büyüdü; OS’ta partition/LVM/FS grow edilmedi. lsblk → growpart/pvresize → lvextend → resize FS.' },

/* —— Backend —— */
{ id: 'ix-be0', tracks: ['backend', 'devops'], level: 'baslangic', tag: 'Process',
  q: 'Uygulaman port dinlemiyor. Nasıl teşhis edersin?',
  a: 'Process ayakta mı (ps/systemctl), ss -tlnp doğru bind mi, firewall, app log, env/config, health endpoint. Connection refused vs timeout ayır.' },
{ id: 'ix-be1', tracks: ['backend', 'devops', 'sre'], level: 'orta', tag: 'DB',
  q: 'Postgres “too many connections” — ne yaparsın?',
  a: 'Mevcut bağlantıları gör (pg_stat_activity), pool (PgBouncer), max_connections, leak’li app, idle in transaction. Kör restart son çare.' },
{ id: 'ix-be2', tracks: ['backend', 'devops'], level: 'orta', tag: 'Log',
  q: '12-factor’e göre log nasıl olmalı?',
  a: 'stdout/stderr event stream, yapılandırılmış (JSON), correlation id. Dosyaya özel log daemon; konteynerde özellikle.' },
{ id: 'ix-be3', tracks: ['backend', 'sifirdan'], level: 'baslangic', tag: 'PATH',
  q: './script çalışıyor da script çalışmıyor. Neden?',
  a: 'PATH’te . yok (güvenlik). Ya ./script ya da PATH’e ekle (genelde eklenmez). İzin + shebang da kontrol et.' },

/* —— Senaryo / behavioral —— */
{ id: 'ix-x0', tracks: ['devops', 'sre', 'redhat', 'soc', 'cloud'], level: 'ileri', tag: 'Senaryo',
  q: '“Google’a Enter’a bastığında ne olur?” — Linux gözüyle 60 sn’de anlat.',
  a: 'DNS (resolv/nss) → TCP handshake → TLS → HTTP. Kernel netfilter, socket, userspace resolver. Katman katman konuş; ezber paragraf değil.' },
{ id: 'ix-x1', tracks: ['sre', 'devops', 'soc'], level: 'ileri', tag: 'Behavioral',
  q: 'Bilmediğin bir üretim sorununda ne yaparsın?',
  a: 'Kapsamı sor, hipotez kur, katmanı izole et (app/host/net/dep), kanıt topla, iletişim kur, rollback/mitigate, not al. “Bilmiyorum ama şöyle bakacağım” senior cevap.' },
{ id: 'ix-x2', tracks: ['redteam', 'blueteam', 'soc'], level: 'ileri', tag: 'Behavioral',
  q: 'Purple team nedir? Neden değerlidir?',
  a: 'Red bulguları blue tespit/iyileştirme ile birlikte çalışır. Sadece skor değil, detection gap kapatma; kurum öğrenir.' },
{ id: 'ix-x3', tracks: ['devops', 'sre', 'redhat', 'backend'], level: 'orta', tag: 'Behavioral',
  q: 'Senior ile junior farkı sence nedir? (Linux/ops bağlamında)',
  a: 'Junior komut çalıştırır. Senior hipotez kurar, blast radius düşünür, kanıtla konuşur, sistemi daha dayanıklı bırakır ve bilgiyi paylaşır.' }
];
