/* Kali Linux Arsenal — resmi metapaketlere dayalı araç ansiklopedisi
   Kaynak: https://www.kali.org/docs/general-use/metapackages/ ve kali-tools-* bağımlılıkları
   Yalnızca yazılı yetkili lab / pentest kapsamı için. */
(function () {
    function T(name, tr, what, example, more) {
        return Object.assign({
            name,
            tr,
            what,
            example: example || name + ' -h',
            aliases: [tr, name]
        }, more || {});
    }

    window.KALI_ARSENAL = {
        source: 'Kali Linux resmi metapaketleri (kali-tools-*) · kali.org',
        warning: 'Bu araçlar yalnızca size ait laboratuvarda veya yazılı sözleşme/izin kapsamındaki sistemlerde kullanılabilir. İzinsiz tarama ve sızma girişimi suçtur.',
        installHint: 'Kategori kurmak: sudo apt update && sudo apt install kali-tools-<kategori>\nHepsini istemek (çok büyük): sudo apt install kali-linux-everything\nVarsayılan masaüstü seti: kali-linux-default',
        categories: [
            {
                id: 'top10',
                meta: 'kali-tools-top10',
                title: 'Top 10',
                trTitle: 'En kritik 10 araç',
                desc: 'Kali’nin “mutlaka bil” listesi. Çoğu pentest senaryosunun omurgası buradadır.',
                phase: 'Genel',
                tools: [
                    T('nmap', 'Ağ haritalama / port tarama', 'Host, açık port, servis ve OS keşfi. SYN/connect/UDP taramaları, NSE script’leri.', 'nmap -sV -sC -oA scan target', { phase: 'Keşif', osi: 'L3–L4' }),
                    T('burpsuite', 'HTTP ara proxy (Burp)', 'Tarayıcı trafiğini yakala, değiştir, tekrarla; web zafiyet testi platformu.', 'burpsuite', { phase: 'Web', osi: 'L7' }),
                    T('metasploit-framework', 'Exploit çerçevesi (MSF)', 'Exploit, payload, post-modül kütüphanesi; msfconsole ile yönetilir.', 'msfconsole', { phase: 'Sömürü' }),
                    T('sqlmap', 'SQL injection otomasyonu', 'Boolean/time/union/error tabanlı SQLi tespiti ve DB enumeration.', 'sqlmap -u "http://lab/?id=1" --batch --dbs', { phase: 'Web', osi: 'L7' }),
                    T('hydra', 'Çevrimiçi parola brute-force', 'SSH, FTP, HTTP form vb. protokoller üzerinde sözlük/brute saldırısı.', 'hydra -L users.txt -P pass.txt ssh://target', { phase: 'Kimlik' }),
                    T('john', 'John the Ripper — hash kırma', 'Offline parola hash crack (wordlist, rules, incremental).', 'john --wordlist=/usr/share/wordlists/rockyou.txt hashes.txt', { phase: 'Kimlik' }),
                    T('aircrack-ng', 'Wi-Fi (802.11) saldırı paketi', 'Capture, handshake, WEP/WPA kırma araç ailesi (airmon, airodump, aireplay…).', 'airmon-ng start wlan0', { phase: 'Kablosuz', osi: 'L2' }),
                    T('wireshark', 'Paket analiz (GUI)', 'L2–L7 protokol decode; pcap inceleme, filtreler, TLS handshake görünürlüğü.', 'wireshark', { phase: 'Sniff', osi: 'L2–L7' }),
                    T('responder', 'LLMNR/NBT-NS/mDNS zehirleme', 'İç ağda isim çözümleme zehirleyerek hash/kimlik bilgisi yakalar.', 'sudo responder -I eth0 -wd', { phase: 'İç ağ' }),
                    T('netexec', 'Ağ yürütme (eski CrackMapExec)', 'SMB/WinRM/LDAP vb. üzerinde spray, enum, komut çalıştırma iskeleti.', 'nxc smb 10.0.0.0/24', { phase: 'Lateral' })
                ]
            },
            {
                id: 'info',
                meta: 'kali-tools-information-gathering',
                title: 'Information Gathering',
                trTitle: 'Bilgi toplama & OSINT',
                desc: 'Hedefi tanımadan saldırmak körlüktür. DNS, SMB, SNMP, SSL, pasif OSINT burada.',
                phase: 'Keşif',
                tools: [
                    T('nmap', 'Port / servis tarayıcı', 'Aktif ağ keşfinin standardı.', 'nmap -Pn -sV target'),
                    T('zenmap', 'Nmap GUI', 'Nmap’in grafik arayüzü; topoloji görünümü.', 'zenmap'),
                    T('masscan', 'Çok hızlı port tarayıcı', 'İnternet ölçeğinde asenkron SYN tarama (dikkat: gürültülü).', 'sudo masscan -p1-65535 target --rate 1000'),
                    T('unicornscan', 'Asenkron tarayıcı', 'Klasik hızlı tarayıcılardan; nmap/masscan yanında nadir kullanılır.', 'unicornscan target:a'),
                    T('hping3', 'Paket üretici / firewall testi', 'Özel TCP/UDP/ICMP paketleri; firewall ve idle scan deneyleri.', 'hping3 -S -p 80 target'),
                    T('fping', 'Çoklu host ping', 'Ağ segmentinde kim ayakta — paralel ICMP.', 'fping -a -g 192.168.1.0/24'),
                    T('arping', 'ARP ile canlılık', 'L2’de host var mı (aynı broadcast domain).', 'arping -c 3 192.168.1.1'),
                    T('netdiscover', 'ARP keşif', 'Pasif/aktif ARP ile yerel ağ host keşfi.', 'sudo netdiscover -i eth0'),
                    T('nbtscan', 'NetBIOS tarama', 'Windows isim/servis bilgisi (eski ağlar).', 'nbtscan 192.168.1.0/24'),
                    T('enum4linux', 'SMB/Windows enum', 'Paylaşım, kullanıcı, grup enumeration (Samba/Windows).', 'enum4linux -a target'),
                    T('smbmap', 'SMB paylaşım haritası', 'Paylaşımlar ve izinler.', 'smbmap -H target'),
                    T('dnsenum', 'DNS enumeration', 'Zone, MX, NS, brute subdomain.', 'dnsenum example.com'),
                    T('dnsrecon', 'DNS keşif', 'Çoklu DNS kayıt ve zone transfer denemeleri.', 'dnsrecon -d example.com'),
                    T('dnsmap', 'Subdomain brute', 'Sözlükle alt alan adı keşfi.', 'dnsmap example.com'),
                    T('dnstracer', 'DNS iz sürücü', 'Kayıtların hangi sunucuya kadar izi.', 'dnstracer www.example.com'),
                    T('dnswalk', 'DNS zone yürüyüşü', 'Zone tutarlılığı / transfer analizi.', 'dnswalk example.com.'),
                    T('fierce', 'DNS / ağ keşif', 'Kurumsal DNS ve bitişik ağ aralığı tahmini.', 'fierce -dns example.com'),
                    T('theharvester', 'OSINT e-posta/host', 'Arama motorları ve kaynaklardan e-posta, alt domain toplar.', 'theHarvester -d example.com -b all'),
                    T('recon-ng', 'OSINT framework', 'Modüler keşif iskeleti (API key’lerle güçlenir).', 'recon-ng'),
                    T('maltego', 'Bağıntı / grafik OSINT', 'Varlıklar arası ilişki görselleştirme (Community/CE).', 'maltego'),
                    T('metagoofil', 'Metadata OSINT', 'Herkese açık dokümanlardan metadata çıkarır.', 'metagoofil -d example.com -t pdf'),
                    T('dmitry', 'Deepmagic Information Gathering', 'Whois, e-posta, subdomain, port — klasik hepsi bir arada.', 'dmitry -winse example.com'),
                    T('legion', 'Otomatik keşif GUI', 'Nmap vb. üzerinde otomatize edilmiş keşif arayüzü.', 'legion'),
                    T('ike-scan', 'IPsec/IKE keşif', 'VPN gateway IKE fingerprint.', 'ike-scan target'),
                    T('onesixtyone', 'SNMP tarayıcı', 'Community string brute / SNMP keşif.', 'onesixtyone -c community.txt target'),
                    T('snmpcheck', 'SNMP enum', 'SNMP üzerinden sistem bilgisi toplama.', 'snmp-check target'),
                    T('smtp-user-enum', 'SMTP kullanıcı enum', 'VRFY/EXPN/RCPT ile kullanıcı adı sızdırma testi.', 'smtp-user-enum -M VRFY -U users.txt -t target'),
                    T('sslscan', 'SSL/TLS tarama', 'Cipher, protokol, zayıf yapılandırma.', 'sslscan target:443'),
                    T('sslyze', 'SSL/TLS analiz', 'Derin TLS yapılandırma testi.', 'sslyze target.com'),
                    T('ssldump', 'SSL trafik dökümü', 'SSL oturumlarını analiz (anahtar varsa decrypt).', 'ssldump -i eth0'),
                    T('sslyze', 'TLS denetim', 'Modern TLS güvenlik denetimi.', 'sslyze --regular target.com'),
                    T('wafw00f', 'WAF tespiti', 'Web Application Firewall var mı, hangisi?', 'wafw00f https://target'),
                    T('p0f', 'Pasif OS fingerprint', 'Trafiği izleyerek OS tahmini (aktif tarama yok).', 'sudo p0f -i eth0'),
                    T('firewalk', 'Firewall ACL keşif', 'TTL oyunuyla ACL kural tahmini.', 'firewalk -S 1-1024 -i eth0 gateway target'),
                    T('fragrouter', 'Fragmentation testi', 'IDS kaçınma / fragment yönlendirme deneyleri.', 'fragrouter -i eth0'),
                    T('0trace', 'Hop izi (firewall dostu)', 'traceroute benzeri ama farklı teknik.', '0trace eth0 target'),
                    T('intrace', 'Idle scan tarzı iz', 'TCP idle tabanlı path keşfi.', 'intrace -h target'),
                    T('lbd', 'Load Balancer Detector', 'DNS/HTTP load balancer var mı?', 'lbd example.com'),
                    T('urlcrazy', 'Typosquatting üretimi', 'Domain yazım hatası varyasyonları.', 'urlcrazy example.com'),
                    T('twofi', 'Twitter OSINT (eski)', 'Sosyal medya kelime listesi üretimi (API değişimleri etkiler).', 'twofi -u user'),
                    T('swaks', 'SMTP test İsviçre çakısı', 'E-posta protokolünü elle test.', 'swaks --to a@b.com --server mail'),
                    T('braa', 'SNMP tarayıcı', 'Hızlı SNMP scanning.', 'braa public@target'),
                    T('netmask', 'Netmask / ağ hesabı', 'Adres ve mask yardımcıları.', 'netmask -s 192.168.1.0/24'),
                    T('ncat', 'Nmap netcat', 'Gelişmiş netcat (ssl, proxy, listen).', 'ncat -lvp 4444'),
                    T('qsslcaudit', 'SSL istemci denetimi', 'İstemci tarafı SSL zafiyet testleri.', 'qsslcaudit'),
                    T('tlssled', 'TLS tarayıcı', 'SSL/TLS güvenlik taraması.', 'tlssled target 443'),
                    T('ftester', 'Firewall test suite', 'Firewall kural ve IDS tepki testleri.', 'ftest'),
                    T('irpas', 'Yönlendirme protokol saldırı seti', 'CDP, IRDP vb. eski protokol istismar yardımcıları.', 'irdpresponder'),
                    T('thc-ipv6', 'IPv6 saldırı araçları', 'IPv6 keşif ve DoS/test araç ailesi.', 'alive6 eth0')
                ]
            },
            {
                id: 'vuln',
                meta: 'kali-tools-vulnerability',
                title: 'Vulnerability Analysis',
                trTitle: 'Zafiyet analizi',
                desc: 'Bilinen zafiyet taraması, CISCO/VoIP testleri, privesc checklist’leri.',
                phase: 'Değerlendirme',
                tools: [
                    T('nikto', 'Web sunucu tarayıcı', 'Eski yazılım, tehlikeli dosya, misconfig imzaları.', 'nikto -h http://target'),
                    T('gvm', 'Greenbone / OpenVAS', 'Kurumsal zafiyet tarama yönetimi (GVM).', 'gvm-setup'),
                    T('lynis', 'Sistem sertleştirme denetimi', 'Linux/Unix security auditing.', 'sudo lynis audit system'),
                    T('unix-privesc-check', 'Unix privesc kontrol listesi', 'Yanlış izin, SUID, cron vb. tarar.', 'unix-privesc-check standard'),
                    T('peass', 'PEASS / LinPEAS / WinPEAS', 'Privilege escalation enumeration script ailesi.', 'linpeas.sh'),
                    T('legion', 'Otomatik keşif+zafiyet GUI', 'Tarama orkestrasyonu.', 'legion'),
                    T('nmap', 'NSE zafiyet script’leri', 'vuln kategorisi script’leriyle imza tarama.', 'nmap --script vuln target'),
                    T('siege', 'HTTP yük / stres', 'DoS değil; kapasite ve timeout davranışı testi.', 'siege -c20 -t1M http://target/'),
                    T('slowhttptest', 'Yavaş HTTP DoS testi', 'Slowloris tarzı uygulamalı test (lab!).', 'slowhttptest -c 1000 -H -g -o out -i 10 -r 200 -t GET -u http://target'),
                    T('thc-ssl-dos', 'SSL renegotiation DoS', 'SSL CPU tüketimi testi.', 'thc-ssl-dos target'),
                    T('bed', 'Protocol fuzzer (BED)', 'Basit protokol fuzzing.', 'bed -s HTTP -t target'),
                    T('sfuzz', 'Simple fuzzer', 'Ağ protokolü fuzz.', 'sfuzz -T'),
                    T('spike', 'SPIKE fuzzer', 'Klasik ağ fuzzing framework.', 'generic_listen_tcp'),
                    T('afl++', 'American Fuzzy Lop++', 'Coverage-guided binary fuzzing.', 'afl-fuzz -i in -o out -- ./prog @@'),
                    T('t50', 'Paket enjeksiyon stres', 'Çok protokollü traffic generator.', 't50 --flood target'),
                    T('yersinia', 'L2 protokol saldırı', 'STP, DHCP, CDP vb. katman 2 testleri.', 'yersinia -G'),
                    T('cisco-torch', 'Cisco keşif', 'Cisco cihaz fingerprint / tarama.', 'cisco-torch -A target'),
                    T('cisco-auditing-tool', 'Cisco audit', 'Cisco parola/community testleri.', 'CAT'),
                    T('cisco-global-exploiter', 'Cisco exploit yardımcı', 'Bilinen Cisco zafiyetleri için yardımcı.', 'cge.pl'),
                    T('cisco-ocs', 'Cisco scanner', 'Cisco özel tarama.', 'cisco-ocs'),
                    T('copy-router-config', 'Cisco config kopyalama testi', 'TFTP üzerinden config alma senaryoları.', 'copy-router-config.pl'),
                    T('dhcpig', 'DHCP exhaustion', 'DHCP starvation DoS testi.', 'dhcpig eth0'),
                    T('voiphopper', 'VLAN hopping (VoIP)', 'VoIP VLAN’a sızma testleri.', 'voiphopper -i eth0')
                ]
            },
            {
                id: 'web',
                meta: 'kali-tools-web',
                title: 'Web Application',
                trTitle: 'Web uygulama analizi',
                desc: 'Proxy, crawler, SQLi/XSS/CMDi, CMS tarayıcıları, SSL araçları.',
                phase: 'Web',
                tools: [
                    T('burpsuite', 'Burp Suite', 'Intercepting proxy, repeater, intruder, scanner (edition’a göre).', 'burpsuite'),
                    T('zaproxy', 'OWASP ZAP', 'Açık kaynak web proxy + otomatik tarayıcı.', 'zaproxy'),
                    T('sqlmap', 'SQLi otomasyon', 'SQL injection tespit ve istismar.', 'sqlmap -u URL --batch'),
                    T('nikto', 'Web sunucu imza tarama', 'CGI/misconfig imzaları.', 'nikto -h URL'),
                    T('wpscan', 'WordPress tarayıcı', 'Eklenti/tema/kullanıcı/CVE keşfi.', 'wpscan --url http://target'),
                    T('joomscan', 'Joomla tarayıcı', 'Joomla zafiyet ve sürüm tespiti.', 'joomscan -u http://target'),
                    T('whatweb', 'Teknoloji fingerprint', 'CMS, framework, sunucu imzası.', 'whatweb http://target'),
                    T('dirb', 'Dizin brute-force', 'Wordlist ile gizli path keşfi.', 'dirb http://target /usr/share/wordlists/dirb/common.txt'),
                    T('dirbuster', 'Dizin brute (GUI)', 'Dirb’in grafik/çok iş parçacıklı hali.', 'dirbuster'),
                    T('wfuzz', 'Web fuzzer', 'Parametre/path fuzzing.', 'wfuzz -c -z file,wordlist --hc 404 http://t/FUZZ'),
                    T('ffuf', 'Hızlı web fuzzer', 'Go tabanlı modern fuzz (ayrı paket olarak da sık kurulur).', 'ffuf -u http://t/FUZZ -w wordlist'),
                    T('gobuster', 'Dizin/DNS/vhost brute', 'Hızlı busting.', 'gobuster dir -u http://t -w wordlist'),
                    T('hakrawler', 'JS/HTML crawler', 'Hızlı endpoint keşfi.', 'echo http://t | hakrawler'),
                    T('commix', 'OS command injection', 'Komut enjeksiyonu otomasyonu.', 'commix --url="http://t/page?cmd=INJECT_HERE"'),
                    T('xsser', 'XSS framework', 'Cross-site scripting testleri.', 'xsser --url http://t'),
                    T('beef-xss', 'Browser Exploitation Framework', 'XSS ile tarayıcı hook / client-side post.', 'beef-xss'),
                    T('wapiti', 'Web zafiyet tarayıcı', 'Siyah kutu web scanner.', 'wapiti -u http://target'),
                    T('skipfish', 'Aktif web tarayıcı', 'Google kaynaklı (eski) aktif scanner.', 'skipfish -o out http://target'),
                    T('uniscan', 'Web scanner', 'RFI/LFI/RSS vb. kontroller.', 'uniscan -u http://target -qweds'),
                    T('dotdotpwn', 'Directory traversal fuzzer', 'Path traversal otomasyonu.', 'dotdotpwn -m http -h target'),
                    T('davtest', 'WebDAV test', 'WebDAV yükleme/izin testleri.', 'davtest -url http://target'),
                    T('cadaver', 'WebDAV istemci', 'DAV üzerinde dosya işlemleri.', 'cadaver http://target'),
                    T('padbuster', 'Padding oracle', 'CBC padding oracle exploit yardımcısı.', 'padbuster URL ciphertext 8'),
                    T('jsql-injection', 'jSQL Injection GUI', 'Grafik SQLi aracı.', 'jsql'),
                    T('sqlninja', 'MSSQL injection', 'Microsoft SQL odaklı istismar.', 'sqlninja -m t'),
                    T('sqlsus', 'MySQL injection', 'MySQL SQLi aracı.', 'sqlsus'),
                    T('sqldict', 'DB parola sözlüğü', 'Veritabanı parola saldırı yardımcı.', 'sqldict'),
                    T('oscanner', 'Oracle scanner', 'Oracle DB enumeration.', 'oscanner -s target'),
                    T('sidguesser', 'Oracle SID guess', 'Oracle SID brute.', 'sidguesser -i target'),
                    T('tnscmd10g', 'Oracle TNS', 'TNS listener komutları.', 'tnscmd10g version -h target'),
                    T('apache-users', 'Apache kullanıcı enum', 'Apache userdir keşfi.', 'apache-users -h target'),
                    T('eyewitness', 'Ekran görüntüsü + rapor', 'URL listesinin screenshot’ı.', 'eyewitness --web -f urls.txt'),
                    T('cutycapt', 'Web screenshot', 'Sayfa görüntüsü alır.', 'cutycapt --url=http://t --out=t.png'),
                    T('httrack', 'Site aynası', 'Web sitesini indir/kopyala.', 'httrack http://target -O ./mirror'),
                    T('mitmproxy', 'İnteraktif TLS proxy', 'CLI/TUI HTTP(S) MITM (lab sertifikası ile).', 'mitmproxy'),
                    T('sslsplit', 'SSL MITM', 'TLS bağlantılarını ayırıp loglar (yetkili lab).', 'sslsplit'),
                    T('sslsniff', 'SSL sniff', 'Eski SSL MITM aracı.', 'sslsniff'),
                    T('sslscan', 'TLS tarama', 'Cipher/protokol.', 'sslscan target:443'),
                    T('sslyze', 'TLS denetim', 'Derin TLS analizi.', 'sslyze target'),
                    T('sslh', 'Protokol mux', 'Aynı portta SSH/HTTPS paylaşımı (kaçınma/altyapı).', 'sslh'),
                    T('proxychains4', 'Proxy zinciri', 'Araç trafiğini proxy üzerinden yönlendir.', 'proxychains4 nmap target'),
                    T('weevely', 'PHP webshell', 'Stealth PHP backdoor yönetimi (yetkili).', 'weevely generate pass shell.php'),
                    T('webacoo', 'Web backdoor', 'Web shell aracı.', 'webacoo'),
                    T('laudanum', 'Web shell koleksiyonu', 'Hazır ASP/PHP/JSP shell’ler.', 'ls /usr/share/laudanum'),
                    T('webshells', 'Webshell paketleri', 'Çeşitli dilde örnek shell’ler.', 'ls /usr/share/webshells'),
                    T('nishang', 'PowerShell offensive', 'Windows/PowerShell post & client-side script’ler.', 'ls /usr/share/nishang'),
                    T('jboss-autopwn', 'JBoss istismar yardımcı', 'JBoss deployment saldırı senaryoları.', 'jboss-autopwn'),
                    T('paros', 'Eski web proxy', 'Klasik proxy (Burp/ZAP tercih).', 'paros'),
                    T('webscarab', 'OWASP WebScarab', 'Eski web proxy framework.', 'webscarab'),
                    T('watobo', 'Web pentest framework', 'Ruby tabanlı web güvenlik iskeleti.', 'watobo'),
                    T('owasp-mantra-ff', 'Mantra tarayıcı', 'Güvenlik testleri için Firefox paketi.', 'mantra'),
                    T('httprint', 'Web sunucu fingerprint', 'HTTP imza ile sunucu tespiti.', 'httprint -h target'),
                    T('ferret-sidejack', 'Sidejacking', 'Oturum çerez yakalama senaryoları.', 'ferret'),
                    T('hamster-sidejack', 'Sidejack proxy', 'Ferret ile birlikte oturum kullanımı.', 'hamster'),
                    T('heartleech', 'Heartbleed istismar', 'CVE-2014-0160 bellek sızıntısı testi.', 'heartleech target'),
                    T('patator', 'Modüler brute-force', 'Çok protokollü esnek brute framework.', 'patator http_fuzz ...'),
                    T('medusa', 'Paralel login brute', 'Hydra benzeri online cracker.', 'medusa -h target -u admin -P pass.txt -M http'),
                    T('hydra', 'Online brute-force', 'HTTP form dahil çok protokol.', 'hydra -L u -P p http-post-form ...'),
                    T('ncrack', 'Ağ authentication crack', 'Nmap ailesinden auth brute.', 'ncrack -p 22 target'),
                    T('siege', 'HTTP yük testi', 'Performans / dayanıklılık.', 'siege URL'),
                    T('slowhttptest', 'Slow HTTP DoS', 'Yavaş istek DoS testi.', 'slowhttptest -u URL'),
                    T('thc-ssl-dos', 'SSL DoS', 'Renegotiation ile CPU DoS.', 'thc-ssl-dos target'),
                    T('redsocks', 'TCP→proxy yönlendirici', 'Transparent proxy yardımcı.', 'redsocks'),
                    T('proxytunnel', 'Proxy üzerinden tünel', 'HTTP CONNECT tüneli.', 'proxytunnel'),
                    T('stunnel4', 'TLS sarmalayıcı', 'Düz protokolü TLS içine al.', 'stunnel'),
                    T('sqlitebrowser', 'SQLite GUI', 'Yerel DB inceleme.', 'sqlitebrowser'),
                    T('default-mysql-server', 'MySQL/MariaDB sunucu', 'Lab DB kurulum bağımlılığı.', 'sudo systemctl start mysql')
                ]
            },
            {
                id: 'database',
                meta: 'kali-tools-database',
                title: 'Database Assessment',
                trTitle: 'Veritabanı değerlendirme',
                desc: 'SQL/Oracle/MSSQL odaklı keşif ve injection araçları.',
                phase: 'Veritabanı',
                tools: [
                    T('sqlmap', 'SQLi otomasyon', 'En güçlü genel SQLi aracı.', 'sqlmap -u URL --dbs'),
                    T('jsql-injection', 'jSQL GUI', 'Grafik injection istemcisi.', 'jsql'),
                    T('sqlninja', 'MSSQL odaklı', 'xp_cmdshell senaryoları vb.', 'sqlninja'),
                    T('sqlsus', 'MySQL odaklı', 'MySQL injection aracı.', 'sqlsus'),
                    T('sqldict', 'DB sözlük saldırısı', 'Veritabanı hesap brute.', 'sqldict'),
                    T('oscanner', 'Oracle enum', 'Oracle kullanıcı/servis keşfi.', 'oscanner -s host'),
                    T('sidguesser', 'Oracle SID', 'SID brute-force.', 'sidguesser -i host'),
                    T('tnscmd10g', 'TNS komutları', 'Oracle listener ile konuşma.', 'tnscmd10g status -h host'),
                    T('mdbtools', 'Access MDB araçları', 'Eski Access DB okuma.', 'mdb-tables file.mdb'),
                    T('sqlitebrowser', 'SQLite tarayıcı', 'GUI ile sqlite inceleme.', 'sqlitebrowser db.sqlite')
                ]
            },
            {
                id: 'passwords',
                meta: 'kali-tools-passwords',
                title: 'Password Attacks',
                trTitle: 'Parola saldırıları',
                desc: 'Online brute, offline hash crack, wordlist üretimi, Windows SAM/NTDS yardımcıları.',
                phase: 'Kimlik bilgisi',
                tools: [
                    T('hydra', 'Online brute', 'Çok protokol paralel brute.', 'hydra -L u -P p ssh://t'),
                    T('medusa', 'Online brute', 'Hydra alternatifi.', 'medusa -h t -u admin -P p.txt -M ssh'),
                    T('ncrack', 'Auth cracker', 'SSH/RDP vb.', 'ncrack -p 3389 t'),
                    T('patator', 'Modüler brute', 'Esnek ve log’lu.', 'patator ssh_login ...'),
                    T('john', 'JtR hash crack', 'CPU hash kırma efsanesi.', 'john hashes.txt'),
                    T('johnny', 'John GUI', 'John the Ripper arayüzü.', 'johnny'),
                    T('hashcat', 'GPU hash crack', 'Dünya standardı hızlı cracker.', 'hashcat -m 0 hashes.txt wordlist'),
                    T('hashcat-utils', 'Hashcat yardımcıları', 'Wordlist/mask işleme.', 'combinator.bin'),
                    T('hash-identifier', 'Hash tipi tahmin', 'Hash hangi algoritma?', 'hash-identifier'),
                    T('hashid', 'Hash ID', 'Hash kimliği (Python).', 'hashid hash'),
                    T('ophcrack', 'Windows LM/NT rainbow', 'Rainbow table ile Windows parola.', 'ophcrack'),
                    T('rainbowcrack', 'Rainbow crack', 'Zaman-bellek takası tabloları.', 'rcrack *.rt -h hash'),
                    T('crunch', 'Wordlist üret', 'Charset’ten sözlük üretir.', 'crunch 6 6 0123456789 -o n.txt'),
                    T('cewl', 'Siteden sözlük', 'Hedef siteden kelime toplar.', 'cewl http://target -w words.txt'),
                    T('cupp', 'Profil sözlüğü', 'Kişi bilgilerinden wordlist (ayrı paket sık).', 'cupp -i'),
                    T('rsmangler', 'Wordlist mangling', 'Mevcut listeyi varyasyonlar.', 'rsmangler --file words.txt'),
                    T('seclists', 'Hazır wordlist/payload', 'Daniel Miessler’in efsane listeleri.', 'ls /usr/share/seclists'),
                    T('wordlists', 'Kali wordlist meta', 'rockyou vb. paketler.', 'ls /usr/share/wordlists'),
                    T('maskprocessor', 'Mask wordlist', 'Hashcat mask üretimi.', 'mp64.bin ?d?d?d?d'),
                    T('statsprocessor', 'Markov wordlist', 'İstatistiksel parola üretimi.', 'sp64.bin'),
                    T('pack / pack2', 'Password Analysis', 'Wordlist analiz ve kural üret.', 'policygen'),
                    T('pipal', 'Parola istatistik', 'Listelerin istatistiksel analizi.', 'pipal passwords.txt'),
                    T('fcrackzip', 'ZIP parola', 'Şifreli zip kırma.', 'fcrackzip -u -D -p wordlist.zip'),
                    T('rarcrack', 'RAR parola', 'RAR arşiv brute.', 'rarcrack file.rar'),
                    T('pdfcrack', 'PDF parola', 'PDF açma parolası.', 'pdfcrack -f file.pdf'),
                    T('truecrack', 'TrueCrypt/VeraCrypt', 'Konteyner parola denemeleri.', 'truecrack'),
                    T('chntpw', 'Windows SAM reset', 'Offline Windows parola sıfırlama (disk mount).', 'chntpw SAM'),
                    T('samdump2', 'SAM dökümü', 'Windows SAM hash çıkarma.', 'samdump2 SYSTEM SAM'),
                    T('creddump7', 'Windows credential dump', 'Registry’den kimlik bilgisi.', 'pwdump.py'),
                    T('mimikatz', 'Windows bellek/kimlik', 'LS / LSASS odaklı (Windows’ta çalışır).', 'mimikatz'),
                    T('passing-the-hash', 'PtH araçları', 'NTLM hash ile kimlik doğrulama senaryoları.', 'pth-winexe'),
                    T('gpp-decrypt', 'GPP parola çöz', 'Groups.xml cpassword decrypt.', 'gpp-decrypt cpassword'),
                    T('polenum', 'Password policy enum', 'SMB üzerinden parola politikası.', 'polenum -u u -p p -d t'),
                    T('sucrack', 'su brute', 'Yerel su parola denemesi.', 'sucrack wordlist'),
                    T('cmospwd', 'CMOS/BIOS parola', 'Eski BIOS parola kurtarma.', 'cmospwd'),
                    T('crackle', 'BLE crack', 'Bluetooth LE temporary key.', 'crackle -i cap.pcap'),
                    T('cisco-auditing-tool', 'Cisco parola audit', 'Cisco cihaz parola testleri.', 'CAT'),
                    T('thc-pptp-bruter', 'PPTP brute', 'PPTP VPN parola.', 'thc-pptp-bruter'),
                    T('sipcrack', 'SIP parola', 'VoIP SIP auth crack.', 'sipcrack'),
                    T('sipvicious', 'SIP audit paketi', 'SIP scanner/cracker ailesi.', 'svmap'),
                    T('freerdp3-x11', 'RDP istemci', 'Uzak masaüstü bağlantısı (lab).', 'xfreerdp /u:u /p:p /v:host'),
                    T('smbmap', 'SMB erişim haritası', 'Paylaşım izinleri.', 'smbmap -H t -u u -p p')
                ]
            },
            {
                id: 'wireless',
                meta: 'kali-tools-wireless',
                title: 'Wireless',
                trTitle: 'Kablosuz (Wi-Fi + BT + RFID + SDR)',
                desc: 'Üst metapaket; alt kırılımlar: 802.11, Bluetooth, RFID, SDR.',
                phase: 'Kablosuz',
                tools: [
                    T('aircrack-ng', 'Wi-Fi paket ailesi', 'Monitor mode, capture, PTW/WPA crack.', 'aircrack-ng -w wordlist capture.cap'),
                    T('wifite', 'Otomatik Wi-Fi saldırı', 'WEP/WPA/WPS senaryolarını otomatize eder.', 'sudo wifite'),
                    T('airgeddon', 'Wi-Fi menü framework', 'All-in-one bash menü.', 'sudo airgeddon'),
                    T('kismet', 'Kablosuz IDS / sniffer', 'Wi-Fi keşif ve intrusion detection.', 'kismet'),
                    T('reaver', 'WPS PIN brute', 'WPS PIN saldırısı.', 'reaver -i mon0 -b BSSID'),
                    T('bully', 'WPS saldırı', 'Reaver alternatifi.', 'bully mon0 -b BSSID'),
                    T('pixiewps', 'WPS pixie-dust', 'Offline WPS zafiyet istismarı.', 'pixiewps ...'),
                    T('cowpatty', 'WPA-PSK crack', 'Dictionary attack on handshake.', 'cowpatty -f dict -r cap -s ESSID'),
                    T('fern-wifi-cracker', 'Wi-Fi GUI cracker', 'Grafik WEP/WPA aracı.', 'fern-wifi-cracker'),
                    T('mdk3 / mdk4', 'Wi-Fi stres / DoS test', 'Beacon flood, deauth vb. (lab!).', 'mdk4 mon0 d'),
                    T('macchanger', 'MAC değiştir', 'Arayüz MAC spoof.', 'sudo macchanger -r wlan0'),
                    T('hostapd-wpe', 'Sahte AP (WPE)', 'Enterprise Wi-Fi credential yakalama lab’ı.', 'hostapd-wpe conf'),
                    T('freeradius-wpe', 'RADIUS WPE', 'Wireless PKE credential.', 'freeradius-wpe'),
                    T('asleap', 'LEAP/PPTP challenge', 'MS-CHAPv2 crack yardımcı.', 'asleap'),
                    T('eapmd5pass', 'EAP-MD5 crack', 'Kablosuz EAP-MD5.', 'eapmd5pass'),
                    T('wifi-honey', 'Honey AP', 'Tuzak erişim noktası senaryoları.', 'wifi-honey'),
                    T('hashcat', 'WPA hash GPU crack', 'Handshake’i hashcat formatında kır.', 'hashcat -m 22000 ...')
                ]
            },
            {
                id: 'wifi80211',
                meta: 'kali-tools-802-11',
                title: '802.11',
                trTitle: 'Wi-Fi (802.11) özel',
                desc: 'Sadece Wi-Fi katmanı araçları (wireless meta’nın alt kümesi).',
                phase: 'Wi-Fi',
                tools: [
                    T('aircrack-ng', 'Aircrack paketi', 'airmon-ng, airodump-ng, aireplay-ng, aircrack-ng.', 'airodump-ng mon0'),
                    T('iw', 'nl80211 kablosuz CLI', 'Modern wireless yapılandırma.', 'iw dev'),
                    T('kismet', 'Kismet', 'Keşif + IDS.', 'kismet'),
                    T('wifite', 'Wifite', 'Otomasyon.', 'sudo wifite'),
                    T('airgeddon', 'Airgeddon', 'Menü framework.', 'sudo airgeddon'),
                    T('reaver', 'Reaver WPS', 'WPS PIN.', 'reaver -i mon0 -b XX'),
                    T('bully', 'Bully WPS', 'WPS.', 'bully'),
                    T('pixiewps', 'Pixie Dust', 'Offline WPS.', 'pixiewps'),
                    T('mdk4', 'MDK4', '802.11 stress.', 'mdk4'),
                    T('mdk3', 'MDK3', 'Eski stress aracı.', 'mdk3'),
                    T('fern-wifi-cracker', 'Fern', 'GUI.', 'fern-wifi-cracker'),
                    T('cowpatty', 'coWPAtty', 'WPA dict.', 'cowpatty'),
                    T('asleap', 'asleap', 'LEAP.', 'asleap'),
                    T('eapmd5pass', 'eapmd5pass', 'EAP-MD5.', 'eapmd5pass'),
                    T('hostapd-wpe', 'hostapd-wpe', 'Evil AP.', 'hostapd-wpe'),
                    T('freeradius-wpe', 'freeradius-wpe', 'RADIUS WPE.', 'freeradius-wpe'),
                    T('macchanger', 'MAC changer', 'Spoof.', 'macchanger'),
                    T('wifi-honey', 'WiFi Honey', 'Honey pot AP.', 'wifi-honey'),
                    T('hashcat', 'Hashcat', 'GPU crack.', 'hashcat')
                ]
            },
            {
                id: 'bluetooth',
                meta: 'kali-tools-bluetooth',
                title: 'Bluetooth',
                trTitle: 'Bluetooth saldırı / keşif',
                desc: 'Klasik BT ve BLE keşif, spoof, sniff yardımcıları.',
                phase: 'Bluetooth',
                tools: [
                    T('bluez', 'Linux Bluetooth yığını', 'hciconfig/bluetoothctl altyapısı.', 'bluetoothctl'),
                    T('btscanner', 'BT scanner', 'Cihaz keşfi.', 'btscanner'),
                    T('bluelog', 'BT logger', 'Görülen cihazları loglar.', 'bluelog'),
                    T('blueranger', 'Mesafe tahmini', 'RSSI ile yaklaşma.', 'blueranger'),
                    T('bluesnarfer', 'Bluesnarfing', 'Eski OBEX veri çekme testleri.', 'bluesnarfer'),
                    T('redfang', 'Non-discoverable bulma', 'Gizli BT cihaz avı.', 'fang'),
                    T('spooftooph', 'BT spoof', 'Bluetooth kimlik spoof.', 'spooftooph'),
                    T('crackle', 'BLE crack', 'BLE temporary key.', 'crackle'),
                    T('ubertooth', 'Ubertooth araçları', '2.4 GHz BT sniff donanımı yazılımı.', 'ubertooth-util'),
                    T('blue-hydra', 'Blue Hydra', 'BT keşif UI/backend.', 'blue_hydra'),
                    T('bluez-hcidump', 'HCI dump', 'HCI paket dökümü.', 'hcidump')
                ]
            },
            {
                id: 'rfid',
                meta: 'kali-tools-rfid',
                title: 'RFID',
                trTitle: 'RFID / NFC',
                desc: 'Kart klonlama, NFC araçları (donanım gerektirir).',
                phase: 'RFID',
                tools: [
                    T('mfcuk', 'MIFARE cracking', 'Darkside vb. MIFARE classic saldırıları.', 'mfcuk'),
                    T('mfoc', 'MIFARE nested', 'Nested attack ile key recovery.', 'mfoc'),
                    T('mfterm', 'MIFARE terminal', 'Kart ile etkileşim.', 'mfterm'),
                    T('proxmark3', 'Proxmark3 suite', 'RFID/NFC laboratuvarının kralı (donanım).', 'pm3'),
                    T('libnfc', 'NFC kütüphane araçları', 'nfc-list vb.', 'nfc-list')
                ]
            },
            {
                id: 'sdr',
                meta: 'kali-tools-sdr',
                title: 'SDR',
                trTitle: 'Yazılım tanımlı radyo',
                desc: 'RTL-SDR / HackRF ekosistemi — spektrum dinleme ve protokol analizi.',
                phase: 'SDR',
                tools: [
                    T('gnuradio', 'GNU Radio', 'SDR akış grafiği framework.', 'gnuradio-companion'),
                    T('gqrx-sdr', 'GQRX', 'Spektrum dinleyici GUI.', 'gqrx'),
                    T('rtl-sdr', 'RTL-SDR araçları', 'Ucuz DVB-T dongle ile RF.', 'rtl_test'),
                    T('hackrf', 'HackRF tools', 'Half-duplex transceiver araçları.', 'hackrf_info'),
                    T('kalibrate-rtl', 'GSM kalibrasyon', 'RTL ile GSM kanal kalibrasyonu.', 'kal'),
                    T('multimon-ng', 'Dijital modem decode', 'POCSAG, FLEX vb. decode.', 'multimon-ng'),
                    T('dump1090', 'ADS-B uçak izleme', '1090 MHz uçak konumları.', 'dump1090'),
                    T('inspectrum', 'Spektrum görüntüleyici', 'RF kayıt analizi.', 'inspectrum')
                ]
            },
            {
                id: 'exploit',
                meta: 'kali-tools-exploitation',
                title: 'Exploitation',
                trTitle: 'Sömürü (exploitation)',
                desc: 'Exploit framework’leri ve yardımcı üreticiler.',
                phase: 'Sömürü',
                tools: [
                    T('metasploit-framework', 'Metasploit', 'Exploit/payload/post ekosistemi.', 'msfconsole'),
                    T('armitage', 'Metasploit GUI', 'Görsel MSF ön yüzü (bakım durumu değişebilir).', 'armitage'),
                    T('exploitdb', 'Exploit-DB', 'searchsploit ile yerel exploit arşivi.', 'searchsploit apache'),
                    T('searchsploit', 'Exploit ara', 'Exploit-DB offline arama.', 'searchsploit wordpress 5.'),
                    T('msfpc', 'MSF payload creator', 'Hızlı payload üretimi.', 'msfpc windows'),
                    T('set', 'Social-Engineer Toolkit', 'Phishing / client-side menüleri.', 'setoolkit'),
                    T('beef-xss', 'BeEF', 'Tarayıcı hook framework.', 'beef-xss'),
                    T('sqlmap', 'SQLi exploit', 'Web→DB sömürü.', 'sqlmap -u URL --os-shell'),
                    T('shellnoob', 'Shellcode helper', 'Shellcode dönüştürme/oyun alanı.', 'shellnoob'),
                    T('termineter', 'Smart meter (AMI)', 'Ölçüm cihazı protokol testleri.', 'termineter')
                ]
            },
            {
                id: 'sniff',
                meta: 'kali-tools-sniffing-spoofing',
                title: 'Sniffing & Spoofing',
                trTitle: 'Dinleme & taklit',
                desc: 'MITM, ARP spoof, DNS spoof, protokol enjeksiyon.',
                phase: 'MITM',
                tools: [
                    T('wireshark', 'Wireshark', 'GUI paket analiz.', 'wireshark'),
                    T('tshark', 'TShark', 'Wireshark CLI.', 'tshark -i eth0'),
                    T('tcpdump', 'tcpdump', 'Klasik paket yakalama.', 'tcpdump -i eth0 -w out.pcap'),
                    T('bettercap', 'Bettercap', 'Modern MITM framework (ARP/DNS/HTTP).', 'sudo bettercap -iface eth0'),
                    T('ettercap-graphical', 'Ettercap', 'Klasik MITM GUI/text.', 'ettercap -G'),
                    T('dsniff', 'dsniff paketi', 'urlsnarf, msgsnarf, arpspoof…', 'arpspoof -i eth0 -t victim gateway'),
                    T('responder', 'Responder', 'LLMNR/NBT-NS zehirleme.', 'sudo responder -I eth0'),
                    T('mitmproxy', 'mitmproxy', 'HTTP(S) interaktif MITM.', 'mitmproxy'),
                    T('sslsplit', 'sslsplit', 'TLS ayırma/log.', 'sslsplit'),
                    T('sslsniff', 'sslsniff', 'Eski SSL MITM.', 'sslsniff'),
                    T('dnschef', 'DNS proxy/spoof', 'Sahte DNS yanıtları.', 'dnschef'),
                    T('macchanger', 'MAC spoof', 'Donanım adresi değiştir.', 'macchanger -r eth0'),
                    T('netsniff-ng', 'netsniff-ng', 'Yüksek performans sniffer toolkit.', 'netsniff-ng'),
                    T('tcpflow', 'TCP akış birleştir', 'PCAP’ten stream recreate.', 'tcpflow -r file.pcap'),
                    T('tcpreplay', 'Trafik tekrar oynat', 'pcap’i ağa bas.', 'tcpreplay -i eth0 file.pcap'),
                    T('driftnet', 'Görüntü yakala', 'Ağdaki görselleri gösterir.', 'driftnet -i eth0'),
                    T('darkstat', 'Trafik istatistik', 'Web arayüzlü traffic stats.', 'darkstat -i eth0'),
                    T('hexinject', 'Hex paket enjekte', 'Ham paket enjeksiyon.', 'hexinject'),
                    T('isr-evilgrade', 'Evilgrade', 'Yazılım güncelleme MITM.', 'evilgrade'),
                    T('sniffjoke', 'IDS evasion', 'Trafik manipülasyonu ile IDS yanıltma deneyi.', 'sniffjoke'),
                    T('rebind', 'DNS rebinding yardımcı', 'Rebiding saldırı lab araçları.', 'rebind'),
                    T('fiked', 'Fake IKE daemon', 'VPN IKE MITM deneyleri.', 'fiked'),
                    T('above', 'Above', 'Ağ keşif/sniff yardımcı (paket).', 'above'),
                    T('wifi-honey', 'Honey AP', 'Kablosuz tuzak.', 'wifi-honey'),
                    T('ferret-sidejack', 'Sidejack ferret', 'Çerez yakalama.', 'ferret'),
                    T('hamster-sidejack', 'Sidejack hamster', 'Yakalanan oturumu kullan.', 'hamster')
                ]
            },
            {
                id: 'post',
                meta: 'kali-tools-post-exploitation',
                title: 'Post Exploitation',
                trTitle: 'Sömürü sonrası',
                desc: 'Tünel, webshell, Windows post, pivot.',
                phase: 'Post',
                tools: [
                    T('mimikatz', 'Mimikatz', 'Windows kimlik bilgisi / ticket.', 'mimikatz'),
                    T('powersploit', 'PowerSploit', 'PowerShell post-ex modülleri.', 'ls /usr/share/windows-resources/powersploit'),
                    T('nishang', 'Nishang', 'PowerShell offensive framework.', 'ls /usr/share/nishang'),
                    T('veil', 'Veil-Evasion', 'AV bypass payload üretimi (lab).', 'veil'),
                    T('shellter', 'Shellter', 'Windows PE dinamik shellcode enjeksiyon.', 'shellter'),
                    T('weevely', 'Weevely PHP shell', 'HTTP üzerinden post-ex.', 'weevely'),
                    T('webacoo', 'Webacoo', 'Web backdoor.', 'webacoo'),
                    T('laudanum', 'Laudanum', 'Hazır webshell seti.', 'ls /usr/share/laudanum'),
                    T('proxychains4', 'ProxyChains', 'Pivot trafiğini zincirle.', 'proxychains4 bash'),
                    T('iodine', 'DNS tünel', 'DNS üzerinden IP tüneli.', 'iodine'),
                    T('dns2tcp', 'DNS2TCP', 'DNS tünel başka implementasyon.', 'dns2tcpd'),
                    T('ptunnel', 'ICMP tünel', 'Ping üzerinden tünel.', 'ptunnel'),
                    T('udptunnel', 'UDP tünel', 'UDP encapsulation.', 'udptunnel'),
                    T('pwnat', 'NAT traversal', 'NAT arkasından bağlantı teknikleri.', 'pwnat'),
                    T('proxytunnel', 'HTTP CONNECT tünel', 'Kurumsal proxy üzerinden.', 'proxytunnel'),
                    T('stunnel4', 'TLS wrap', 'Servisi TLS ile sarmala.', 'stunnel'),
                    T('sslh', 'Protocol multiplexer', '443 üzerinde SSH+HTTPS.', 'sslh'),
                    T('sbd', 'Secure backdoor', 'Netcat benzeri şifreli.', 'sbd'),
                    T('dbd', 'dbd', 'Netcat benzeri başka implementasyon.', 'dbd'),
                    T('cymothoa', 'Process injection backdoor', 'Linux process’e shell enjekte (lab).', 'cymothoa'),
                    T('exe2hexbat', 'EXE→hex/bat', 'Transfer için dönüştürücü.', 'exe2hexbat'),
                    T('miredo', 'Teredo IPv6', 'IPv6 tünel istemcisi.', 'miredo')
                ]
            },
            {
                id: 'social',
                meta: 'kali-tools-social-engineering',
                title: 'Social Engineering',
                trTitle: 'Sosyal mühendislik',
                desc: 'Phishing, client-side, tarayıcı hook — etik kurallar çok sıkı.',
                phase: 'İnsan',
                tools: [
                    T('set', 'Social-Engineer Toolkit', 'Phishing şablonları, payload menüleri.', 'setoolkit'),
                    T('beef-xss', 'BeEF', 'XSS hook sonrası tarayıcı kontrolü.', 'beef-xss'),
                    T('maltego', 'Maltego', 'İnsan/org bağıntı haritası.', 'maltego'),
                    T('msfpc', 'Hızlı payload', 'SET/MSF ile birlikte kullanılan üretici.', 'msfpc'),
                    T('veil', 'Payload gizleme', 'AV evasion deneyleri.', 'veil')
                ]
            },
            {
                id: 're',
                meta: 'kali-tools-reverse-engineering',
                title: 'Reverse Engineering',
                trTitle: 'Tersine mühendislik',
                desc: 'Disassembler, debugger, decompiler, firmware.',
                phase: 'RE',
                tools: [
                    T('radare2', 'radare2 / r2', 'Açık kaynak reverse engineering framework.', 'r2 ./binary'),
                    T('gdb', 'GNU Debugger', 'Native debug.', 'gdb ./prog'),
                    T('edb-debugger', 'EDB', 'Qt tabanlı debugger.', 'edb'),
                    T('ollydbg', 'OllyDbg (Wine)', 'Klasik Windows usermode debugger.', 'ollydbg'),
                    T('jadx', 'JADX', 'Android APK/Java decompiler.', 'jadx-gui app.apk'),
                    T('apktool', 'APKTool', 'APK decode/rebuild.', 'apktool d app.apk'),
                    T('bytecode-viewer', 'Bytecode Viewer', 'Java bytecode GUI.', 'bytecode-viewer'),
                    T('binwalk', 'Binwalk', 'Firmware kes / carve / analiz.', 'binwalk -e firmware.bin'),
                    T('binwalk3', 'Binwalk3', 'Yeni nesil binwalk.', 'binwalk3'),
                    T('nasm', 'NASM', 'Assembler.', 'nasm -f elf64 x.asm'),
                    T('python3-capstone', 'Capstone', 'Disassembly framework (Python).', 'python3 -c "import capstone"'),
                    T('ghidra', 'Ghidra (sık eklenir)', 'NSA kaynaklı RE suite — Kali’ye ayrıca kurulabilir.', 'ghidra')
                ]
            },
            {
                id: 'forensics',
                meta: 'kali-tools-forensics',
                title: 'Forensics',
                trTitle: 'Adli bilişim',
                desc: 'Disk imajı, bellek, dosya kurtarma, timeline, malware triage.',
                phase: 'Forensics',
                tools: [
                    T('autopsy', 'Autopsy', 'Sleuth Kit GUI — disk adli analizi.', 'autopsy'),
                    T('sleuthkit', 'The Sleuth Kit', 'CLI forensics (fls, icat…).', 'fls -r image.dd'),
                    T('foremost', 'Foremost', 'File carving.', 'foremost -i disk.dd'),
                    T('binwalk', 'Firmware/file carve', 'Gömülü dosya bulma.', 'binwalk -e file'),
                    T('bulk-extractor', 'Bulk Extractor', 'E-posta, URL, CC carve.', 'bulk_extractor -o out disk.dd'),
                    T('guymager', 'Guymager', 'Forensic imaging GUI.', 'guymager'),
                    T('dc3dd', 'DC3-DD', 'Adli dd (hash’li).', 'dc3dd if=/dev/sdX of=img.dd hash=sha256'),
                    T('dcfldd', 'DCFLDD', 'Hash’li dd.', 'dcfldd if=/dev/sdX of=img.dd'),
                    T('ddrescue', 'GNU ddrescue', 'Hasarlı diskten kurtarma kopyası.', 'ddrescue /dev/sdX image.map'),
                    T('ewf-tools', 'EWF (E01) araçları', 'Expert Witness Format.', 'ewfacquire'),
                    T('plaso', 'Plaso / log2timeline', 'Süper timeline üretimi.', 'log2timeline.py'),
                    T('volatility3', 'Volatility 3', 'Bellek (RAM) forensics — sık kurulur.', 'vol -f mem.raw windows.info'),
                    T('chkrootkit', 'Rootkit ara', 'Bilinen rootkit imzaları.', 'sudo chkrootkit'),
                    T('rkhunter', 'Rootkit Hunter', 'Rootkit/malware kontrol (ayrı paket).', 'sudo rkhunter -c'),
                    T('exifprobe', 'EXIF incele', 'Görüntü metadata.', 'exifprobe img.jpg'),
                    T('exiv2', 'Exiv2', 'Metadata okuma/yazma.', 'exiv2 img.jpg'),
                    T('pdf-parser', 'PDF parser', 'PDF yapısı / javascript.', 'pdf-parser.py file.pdf'),
                    T('pdfid', 'PDFID', 'PDF’de şüpheli keyword.', 'pdfid.py file.pdf'),
                    T('reglookup', 'Windows registry', 'Registry hive okuma.', 'reglookup SAM'),
                    T('pasco', 'IE history', 'index.dat analizi.', 'pasco index.dat'),
                    T('galleta', 'Cookie analizi', 'Eski IE cookie.', 'galleta'),
                    T('dumpzilla', 'Firefox dump', 'FF profil adli.', 'dumpzilla.py'),
                    T('memdump', 'Bellek dökümü yardımcı', 'Process memory dump.', 'memdump'),
                    T('hashdeep', 'Recursive hashing', 'Bütünlük envanteri.', 'hashdeep -r /mnt'),
                    T('md5deep', 'md5deep ailesi', 'Toplu hash.', 'md5deep -r /mnt'),
                    T('inetsim', 'Ağ simülasyonu', 'Malware lab için sahte servisler.', 'inetsim'),
                    T('radare2', 'RE forensics', 'Binary triage.', 'r2 suspicious.bin'),
                    T('steghide', 'Steganografi', 'Gizlenmiş veri (crypto-stego paketinde).', 'steghide extract -sf file.jpg')
                ]
            },
            {
                id: 'reporting',
                meta: 'kali-tools-reporting',
                title: 'Reporting',
                trTitle: 'Raporlama',
                desc: 'Bulguları belgelemek — pentest’in müşteriye görünen yüzü.',
                phase: 'Rapor',
                tools: [
                    T('cutycapt', 'Screenshot', 'Kanıt ekran görüntüsü.', 'cutycapt --url=... --out=p.png'),
                    T('recordmydesktop', 'Masaüstü kayıt', 'Demo videosu.', 'recordmydesktop'),
                    T('dos2unix', 'Rapor metin düzeltme', 'Satır sonu uyumu.', 'dos2unix report.txt'),
                    T('faraday', 'Faraday (sık kullanılır)', 'Collaborative pentest IDE — ayrıca kurulabilir.', 'faraday'),
                    T('dradis', 'Dradis Framework', 'Bulgu yönetimi / rapor.', 'dradis')
                ]
            },
            {
                id: 'crypto',
                meta: 'kali-tools-crypto-stego',
                title: 'Crypto & Stego',
                trTitle: 'Kriptografi & steganografi',
                desc: 'Gizli veri, şifreleme, disk/image stego.',
                phase: 'Crypto',
                tools: [
                    T('steghide', 'Steghide', 'Dosyaya veri gizle/çıkar.', 'steghide extract -sf img.jpg'),
                    T('stegosuite', 'Stegosuite', 'GUI stego.', 'stegosuite'),
                    T('stegsnow', 'Stegsnow', 'Whitespace steganography.', 'stegsnow'),
                    T('aesfix', 'AES key find', 'Bellekte AES anahtarı ara.', 'aeskeyfind'),
                    T('aeskeyfind', 'AES keyfind', 'Memory image’dan key.', 'aeskeyfind mem.raw'),
                    T('ccrypt', 'ccrypt', 'Dosya şifreleme.', 'ccrypt file')
                ]
            },
            {
                id: 'fuzzing',
                meta: 'kali-tools-fuzzing',
                title: 'Fuzzing',
                trTitle: 'Fuzzing',
                desc: 'Protokol ve dosya fuzz — çökme avı.',
                phase: 'Fuzz',
                tools: [
                    T('afl++', 'AFL++', 'Coverage-guided fuzzing.', 'afl-fuzz -i in -o out -- ./target @@'),
                    T('sfuzz', 'sfuzz', 'Simple network fuzzer.', 'sfuzz'),
                    T('spike', 'SPIKE', 'Protocol fuzz blocks.', 'generic_send_tcp'),
                    T('bed', 'BED', 'Protocol fuzzer.', 'bed')
                ]
            },
            {
                id: 'voip',
                meta: 'kali-tools-voip',
                title: 'VoIP',
                trTitle: 'VoIP / SIP',
                desc: 'SIP/RTP keşif, flood ve parola testleri.',
                phase: 'VoIP',
                tools: [
                    T('sipvicious', 'SIPVicious', 'SIP sweep/crack/enum.', 'svmap'),
                    T('sipcrack', 'SIP crack', 'SIP auth brute.', 'sipcrack'),
                    T('sipp', 'SIPp', 'SIP trafik üretici / senaryo.', 'sipp'),
                    T('enumiax', 'IAX enum', 'Inter-Asterisk eXchange enum.', 'enumiax'),
                    T('rtpbreak', 'RTP kırıcı', 'RTP oturum analizi.', 'rtpbreak'),
                    T('wireshark', 'VoIP call analiz', 'Telephony menüsü ile çağrı dinleme (yasal!).', 'wireshark'),
                    T('nmap', 'SIP NSE', 'sip-methods vb. script’ler.', 'nmap -sU -p 5060 --script sip-* t')
                ]
            },
            {
                id: 'hardware',
                meta: 'kali-tools-hardware',
                title: 'Hardware',
                trTitle: 'Donanım hacking',
                desc: 'Gömülü sistem, UART/JTAG, firmware — çoğu ek donanım ister.',
                phase: 'Hardware',
                tools: [
                    T('binwalk', 'Firmware analiz', 'Kes, çıkar, imza bul.', 'binwalk -e fw.bin'),
                    T('flashrom', 'ROM okuma/yazma', 'BIOS/chip flash.', 'flashrom'),
                    T('openocd', 'On-Chip Debug', 'JTAG/SWD.', 'openocd'),
                    T('minicom', 'Seri konsol', 'UART erişim.', 'minicom -D /dev/ttyUSB0'),
                    T('screen', 'Seri alternatif', 'screen /dev/ttyUSB0 115200.', 'screen /dev/ttyUSB0 115200')
                ]
            },
            {
                id: 'gpu',
                meta: 'kali-tools-gpu',
                title: 'GPU',
                trTitle: 'GPU hızlandırmalı araçlar',
                desc: 'Hashcat vb. GPU’dan yararlanan paketler.',
                phase: 'GPU',
                tools: [
                    T('hashcat', 'Hashcat', 'GPU crack standardı.', 'hashcat -I'),
                    T('hashcat-utils', 'Hashcat utils', 'Yardımcılar.', 'combinator.bin')
                ]
            },
            {
                id: 'windows',
                meta: 'kali-tools-windows-resources',
                title: 'Windows Resources',
                trTitle: 'Windows kaynakları',
                desc: 'Windows hedeflerinde kullanılmak üzere Kali’de taşınan script/binary’ler.',
                phase: 'Windows',
                tools: [
                    T('mimikatz', 'Mimikatz', 'Windows kimlik.', 'ls /usr/share/windows-resources/mimikatz'),
                    T('powersploit', 'PowerSploit', 'PS post-ex.', 'ls /usr/share/windows-resources/powersploit'),
                    T('nishang', 'Nishang', 'PS framework.', 'ls /usr/share/nishang'),
                    T('binaries', 'Windows binaries', 'Çeşitli yardımcı exe’ler.', 'ls /usr/share/windows-resources')
                ]
            },
            {
                id: 'nist',
                meta: 'kali-tools-identify|protect|detect|respond|recover',
                title: 'NIST CSF hizalı',
                trTitle: 'Identify / Protect / Detect / Respond / Recover',
                desc: 'Kali’nin NIST Siber Güvenlik Çerçevesine map edilmiş metapaketleri — blue team odaklı da kullanılabilir.',
                phase: 'CSF',
                tools: [
                    T('kali-tools-identify', 'Identify meta', 'Varlık/risk tanımlama araç seti.', 'sudo apt install kali-tools-identify'),
                    T('kali-tools-protect', 'Protect meta', 'clamav, cryptsetup, fwbuilder…', 'sudo apt install kali-tools-protect'),
                    T('clamav', 'ClamAV antivirüs', 'Malware tarama.', 'clamscan -r /'),
                    T('cryptsetup', 'LUKS disk şifreleme', 'Koruma katmanı.', 'cryptsetup luksFormat'),
                    T('fwbuilder', 'Firewall Builder', 'Kural tasarım GUI.', 'fwbuilder'),
                    T('kali-tools-detect', 'Detect meta', 'Tespit araçları seti.', 'sudo apt install kali-tools-detect'),
                    T('kali-tools-respond', 'Respond meta', 'Olay müdahale seti (forensics bağımlı).', 'sudo apt install kali-tools-respond'),
                    T('kali-tools-recover', 'Recover meta', 'Kurtarma: ddrescue, extundelete…', 'sudo apt install kali-tools-recover'),
                    T('extundelete', 'ext kurtarma', 'Silinen dosya kurtarma.', 'extundelete'),
                    T('scrounge-ntfs', 'NTFS kurtarma', 'NTFS carve.', 'scrounge-ntfs')
                ]
            }
        ]
    };

    // düz liste + arama yardımcıları
    window.KALI_TOOLS_FLAT = [];
    window.KALI_ARSENAL.categories.forEach(cat => {
        (cat.tools || []).forEach(t => {
            window.KALI_TOOLS_FLAT.push(Object.assign({}, t, {
                category: cat.id,
                categoryTitle: cat.trTitle || cat.title,
                meta: cat.meta
            }));
        });
    });

    // Türkçe arama ifadeleri
    Object.assign(window.SEARCH_PHRASES || (window.SEARCH_PHRASES = {}), {
        'port tara': ['nmap', 'masscan'],
        'wifi kır': ['aircrack-ng', 'wifite', 'hashcat'],
        'wifi şifre': ['aircrack-ng', 'reaver', 'hashcat'],
        'web proxy': ['burpsuite', 'zaproxy', 'mitmproxy'],
        'sql injection': ['sqlmap', 'jsql-injection'],
        'wordpress tara': ['wpscan'],
        'parola kır': ['john', 'hashcat', 'hydra'],
        'hash kır': ['hashcat', 'john'],
        'exploit ara': ['searchsploit', 'exploitdb', 'metasploit-framework'],
        'metasploit': ['metasploit-framework', 'msfconsole'],
        'sosyal mühendislik': ['set', 'beef-xss'],
        'mitm': ['bettercap', 'ettercap-graphical', 'responder'],
        'paket yakala': ['wireshark', 'tcpdump', 'tshark'],
        'adli bilişim': ['autopsy', 'foremost', 'volatility3'],
        'firmware': ['binwalk'],
        'bluetooth tara': ['btscanner', 'bluez'],
        'kali araç': ['nmap', 'burpsuite', 'metasploit-framework']
    });
})();
